# Lesson plan data, lessons 42-62
P = {}
G = dict(initial=["b","c","d","f","g","h","j","k","l","m","n","p","r","s","t","v","w","y","z","bl","cl","fl","sl","br","cr","dr","fr","gr","tr","sk","sm","sn","sp","st","sw"], medial=["a","e","i","o","u"])
def g(final, extra_init=None):
    d = dict(initial=G['initial'][:], medial=G['medial'][:], final=final)
    if extra_init: d['initial'] = extra_init + d['initial']
    return d
P["42"] = dict(tag="FLSZ spelling rule: ff, ll, ss, zz",
 notes=["The FLSZ rule: when a one-syllable word has a short vowel followed by /f/, /l/, /s/ or /z/ at the end, the final letter is doubled (off, hill, miss, buzz). The doubled letter spells one sound.",
        "Word work today uses writing, because most manipulative letter sets have only one of each letter."],
 pa=dict(blend=["/ŏ/ /f/ (off)","/h/ /ĭ/ /l/ (hill)","/m/ /ĭ/ /s/ (miss)","/b/ /ŭ/ /z/ (buzz)"], segment=["puff (/p/ /ŭ/ /f/)","tell (/t/ /ĕ/ /l/)","kiss (/k/ /ĭ/ /s/)","fizz (/f/ /ĭ/ /z/)"]),
 bd=dict(chain="hill → fill → fell → tell → bell → bill → will → well → yell → sell → smell → spell → spill → still", grid=g(["ll","ff","ss","zz","t","n","d"])),
 intro=["Today we are learning a spelling rule. When a short word has a short vowel and ends with the sound /f/, /l/, /s/ or /z/, we usually double the last letter: off, hill, miss, buzz.",
        "The two letters spell one sound. When you read, say the sound once: /ŏf/, off. When you spell, remember the rule: FLSZ - f, l, s and z are doubled after a short vowel at the end of a word.",
        "Remember that some words are exceptions, such as bus, gas, yes and if."],
 gesture="Review the gestures for /f/, /l/, /s/ and /z/. Point out that /f/ and /s/ are quiet, /l/ and /z/ have the voice on.", soundwall="Add 'ff' under /f/, 'll' under /l/, 'ss' under /s/ and 'zz' under /z/.", formation=None,
 spell=dict(ido=["off"], wedo=["hill","miss","buzz","will"]),
 ww=dict(type="Word Work with Writing", chain="hill → fill → fell → tell → bell → bill → will → well → yell → sell → smell → spell"),
 text_spell=["I will get off the bus.","Jeff fell on the hill.","Do not miss the bell!"],
 chains=[["Onset-Rime Level: -ill","hill → fill → bill → will → still → spill"],["Onset-Rime Level: -ell","fell → tell → bell → well → yell → sell → smell"],["Onset-Rime Level: -uff","puff → huff → cuff → stuff"],["Phoneme Level: Intro Lesson","hill → fill → fell → tell → bell → bill → will → well → yell → sell → smell → spell"]],
 hf=dict(dolch=["will","well","off"], fry=["will","off"]), lists={"ff":["off","puff","huff","cuff","stuff","sniff","cliff","stiff"],"ll":["hill","fill","bell","tell","will","well","yell","sell","doll","dull","spell","smell","still","spill","drill"],"ss":["miss","kiss","mess","less","boss","fuss","pass","dress","cross","press","grass","class"],"zz":["buzz","fizz","jazz","fuzz"]})
P["43"] = dict(tag="-all, -oll, -ull",
 notes=["In -all, -oll and -ull the vowel does not say its short sound: all /orl/, roll /rōl/, pull /pool/. Teach them as chunks (word families). In Australian/NZ English -all sounds like /orl/."],
 pa=dict(blend=["/b/ /orl/ (ball)","/r/ /ō/ /l/ (roll)","/p/ /oo/ /l/ (pull)","/s/ /m/ /orl/ (small)"], segment=["call (/k/ /orl/)","doll (/d/ /ŏ/ /l/)","full (/f/ /oo/ /l/)","tall (/t/ /orl/)"]),
 bd=dict(chain="all → ball → call → fall → hall → mall → tall → wall → small → stall", grid=dict(initial=["b","c","f","h","m","t","w","sm","st","r","p","d"], medial=["all","oll","ull"], final=[])),
 intro=["We learned that L is doubled at the end of a word after a short vowel (bell, hill). Today we look at three special endings: -all, -oll and -ull. In these words the vowel does not say its usual short sound.",
        "-all says /orl/ as in ball and small. -oll usually says /ōl/ as in roll and troll (but doll has short o). -ull says /ool/ as in pull and full (but dull has short u). Read these endings as chunks."],
 gesture="Compare the vowel sounds: /orl/ (all), /ōl/ (roll), /ool/ (pull). Use the sound wall pictures.", soundwall="Add '-all' near /or/, '-oll' near /ō/ and '-ull' near /oo/ as chunk cards.", formation=None,
 spell=dict(ido=["ball"], wedo=["call","roll","pull","small"]),
 ww=dict(type="Word Work with Writing", chain="all → ball → call → fall → hall → mall → tall → wall → small → stall"),
 text_spell=["The ball is in the hall.","Pull the doll off the wall.","Can the small dog roll?"],
 chains=[["Onset-Rime Level: -all","all → ball → call → fall → hall → mall → tall → wall → small → stall"],["Onset-Rime Level: -oll","roll → poll → toll → troll → stroll"],["Onset-Rime Level: -ull","pull → full → bull → dull → gull"]],
 hf=dict(dolch=["all","call","fall","small","pull","go","no","so"], fry=["all","call","small"]), lists={"-all":["all","ball","call","fall","hall","mall","tall","wall","small","stall","squall"],"-oll":["roll","poll","toll","troll","stroll","doll"],"-ull":["pull","full","bull","dull","gull","hull","skull"]})
P["44"] = dict(tag="The grapheme CK spells /k/",
 notes=["CK is used right after a short vowel at the end of a one-syllable word (back, neck). After a consonant, use k (desk, milk). CK never begins a word."],
 pa=dict(blend=["/b/ /ă/ /k/ (back)","/r/ /ŏ/ /k/ (rock)","/p/ /ĭ/ /k/ (pick)","/t/ /r/ /ŭ/ /k/ (truck)"], segment=["sick (/s/ /ĭ/ /k/)","kick (/k/ /ĭ/ /k/)","clock (/k/ /l/ /ŏ/ /k/)","stick (/s/ /t/ /ĭ/ /k/)"]),
 bd=dict(chain="sick → sock → rock → lock → lick → pick → pack → back → black → block → clock → click → stick → stuck → truck", grid=g(["ck","t","p","n","d","g","ll","ss"])),
 intro=["Today we are learning about the letters CK. C and K both spell /k/. When they come together, they spell one sound, /k/, like at the end of duck.",
        "CK comes at the end of a word right after a short vowel, such as rock and black. If there is another consonant before the /k/, we use just K (desk, milk). CK never comes at the beginning of a word."],
 gesture="Review the /k/ gesture (tongue pulled back, quiet, quick).", soundwall="Add 'ck' under /k/ next to 'c' and 'k'.", formation=None,
 spell=dict(ido=["back"], wedo=["rock","pick","truck","clock"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="sick → sock → rock → lock → lick → pick → pack → back → black → block → clock"),
 text_spell=["The duck is on the rock.","Jack can kick the black ball.","Pick up the sock and the stick."],
 chains=[["Onset-Rime Level: -ack","back → pack → sack → tack → black → snack → track"],["Onset-Rime Level: -ick","sick → kick → lick → pick → tick → stick → trick → quick"],["Onset-Rime Level: -ock","rock → sock → lock → dock → block → clock"],["Phoneme Level: Intro Lesson","sick → sock → rock → lock → lick → pick → pack → back → black → block → clock"]],
 hf=dict(dolch=["black","pick"], fry=["back"]), lists={"ck /k/":["back","rock","sick","pick","truck","stick","quack","quick","clock","duck","kick","lock","sock","neck","deck","pack","black","block","snack","track","trick","stuck","check*"]})
P["45"] = dict(tag="The consonant digraph SH spells /sh/",
 notes=["Although students have learned double letters and CK, SH is the first grapheme that represents a sound that is different from either of its letters."],
 pa=dict(blend=["/f/ /ĭ/ /sh/ (fish)","/r/ /ŭ/ /sh/ (rush)","/sh/ /ĭ/ /p/ (ship)","/sh/ /ŭ/ /t/ (shut)"], segment=["shin (/sh/ /ĭ/ /n/)","shock (/sh/ /ŏ/ /k/)","dash (/d/ /ă/ /sh/)","brush (/b/ /r/ /ŭ/ /sh/)"]),
 bd=dict(chain="ship → shop → shot → shut → shun → shin → chin* → thin* → ", grid=g(["sh","ck","ll","ss","t","p","n","d"], ["sh"]), note="Use: ship → shop → shot → shut → shun → shin → shed → shell → shall → sham → slam → slash → flash → fish → dish → wish"),
 intro=["A consonant digraph is when two consonants come together to make one sound. You have already learned about a consonant digraph. We have talked about CK. When C and K are together at the end of a word, they make one sound, /k/.",
        "The two consonants S and H have their own sounds, /s/ and /h/. But when these consonants come together in words, they make one new sound, /sh/, like at the beginning of the word sheep.",
        "The consonant digraph SH can come at the beginning of a word, such as ship and shop. The consonant digraph SH can come at the end of a word, such as fish and wish."],
 gesture="To make the /sh/ sound, put your teeth together and round your lips like this... (model). Pull your tongue back toward the back of your mouth. Be sure your voice is off because this is a quiet sound (model finger in front of mouth in 'shh' fashion). The /sh/ sound is a continuous sound that can be stretched out (use continuous hand motion). Watch me /sh/. You try /sh/.",
 soundwall="Add grapheme card 'sh' to the consonant grid under the /sh/ picture card.", formation="Practise letter formation for sh.",
 read=dict(ido=["shed"], wedo=["shop","shut","shell","shock","fish","dish","flash","crash","shelf"]), spell=dict(ido=["ship"], wedo=["shin","shock","wish","brush"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="shin → ship → shop → shot → shock → sock → sick → sack → rack → rash → dash → cash → clash → crash → crush → brush → rush"),
 text_spell=["We went on a ship.","Will you shut the trash can lid?","She grabs a snack from the shelf."],
 chains=[["Onset-Rime Level: -ash","ash → bash → cash → dash → hash → gash → mash → lash → clash → crash → rash → sash → stash"],["Onset-Rime Level: -ush","rush → hush → gush → lush → blush → brush → crush → flush"],["Phoneme Level: Targeted (sh- /sh/)","shot → shut → shun → shin → ship → shop → shock → shack"],["Phoneme Level: Targeted (-sh /sh/)","fish → dish → dash → ash → cash → hash → bash → gash → gush → hush"],["Phoneme Level: Intro Lesson","shin → ship → shop → shot → shock → sock → sick → sack → rack → rash → dash → cash → clash → crash → crush → brush → rush"]],
 hf=dict(dolch=["she","we","wish"], fry=["she","we"]), lists={"sh- /sh/":["shed","shop","shut","shell","shock","shin","ship","shot","shun","shelf","shift","shrug","shred"],"-sh /sh/":["fish","dish","wish","flash","crash","brush","rush","cash","dash","mash","hush","blush","crush","fresh","splash","trash"]})
P["46"] = dict(tag="The consonant digraph TH spells voiced /th/",
 notes=["TH spells two sounds. Today's words use voiced /th/ (voice on) as in this and that. Unvoiced /th/ (thin, bath) is Lesson 47. Many high-frequency words use voiced th: the, this, that, them, then, than, they, their."],
 pa=dict(blend=["/th/ /ĭ/ /s/ (this)","/th/ /ă/ /t/ (that)","/th/ /ĕ/ /m/ (them)","/th/ /ĕ/ /n/ (then)"], segment=["than (/th/ /ă/ /n/)","that (/th/ /ă/ /t/)","this (/th/ /ĭ/ /s/)","them (/th/ /ĕ/ /m/)"]),
 bd=dict(chain="that → than → then → them → this → thus", grid=g(["t","n","m","s","sh","ck","ll"], ["th"])),
 intro=["We know that a consonant digraph is two consonants that come together to make one sound, like SH. Today we will learn the digraph TH. T and H together make a new sound.",
        "TH can spell two sounds. Today we learn the /th/ sound with your voice on, like in the words this and that. Put your tongue between your teeth and turn your voice on.",
        "TH comes at the beginning of many small words we use all the time: the, this, that, them, then, than. TH /th/ can also come at the end of a few words, such as with (in some accents) and smooth."],
 gesture="To make the voiced /th/ sound, put your tongue between your teeth and push air out with your voice on... (model). Feel the buzz on your tongue. /th/ is a continuous sound. Watch me /th/. You try /th/.",
 soundwall="Add 'th' under voiced /th/ (tongue between teeth).", formation="Practise letter formation for th.",
 spell=dict(ido=["this"], wedo=["that","them","then"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="that → than → then → them → this → thus"),
 text_spell=["This is that cat.","Then I met them.","Is this hat bigger than that hat?"],
 chains=[["Phoneme Level: Targeted (th- /th/)","that → than → then → them → this → thus"]],
 hf=dict(dolch=["this","that","them","then","than","they","their"], fry=["this","that","them","then","than","they","their"]), lists={"th /th/ (voiced)":["this","that","them","then","than","thus","the","they","their","with","smooth*","those*","these*"]})
P["47"] = dict(tag="The consonant digraph TH spells unvoiced /th/",
 notes=["The same digraph TH spells the quiet /th/ (voice off) in thin, bath, moth. Have students feel their throat to tell the two sounds apart."],
 pa=dict(blend=["/th/ /ĭ/ /n/ (thin)","/th/ /ĭ/ /k/ (thick)","/m/ /ŏ/ /th/ (moth)","/b/ /ă/ /th/ (bath)"], segment=["with (/w/ /ĭ/ /th/)","thud (/th/ /ŭ/ /d/)","cloth (/k/ /l/ /ŏ/ /th/)","froth (/f/ /r/ /ŏ/ /th/)"]),
 bd=dict(chain="thin → thick → think → thank → than → that → bath → path → math → moth → cloth → froth", grid=g(["th","n","ck","nk","t","sh","ll"], ["th"])),
 intro=["Yesterday we learned that TH spells the /th/ sound with the voice on, as in this and that. Today we will learn that TH can also spell a quiet /th/ sound, with the voice off, as in thin and thick.",
        "Put your tongue between your teeth and blow air out quietly - /th/. TH can come at the beginning of a word, such as thin and thick, or at the end of a word, such as with and moth."],
 gesture="To make the unvoiced /th/ sound, put your tongue between your teeth and blow air out with your voice off... (model). It is a quiet sound. /th/ is a continuous sound. Watch me /th/. You try /th/. Now compare: /th/ (this) with voice on, /th/ (thin) with voice off.",
 soundwall="Add 'th' under unvoiced /th/ (tongue between teeth).", formation=None,
 spell=dict(ido=["thin"], wedo=["thick","with","moth"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="thin → thick → think → thank → than → that → bath → path → math → moth → cloth"),
 text_spell=["The moth is thin.","Beth is with them.","I think that the bath is hot."],
 chains=[["Onset-Rime Level: -ath","bath → path → math"],["Onset-Rime Level: -oth","moth → cloth → froth → broth"],["Phoneme Level: Intro Lesson","thin → thick → think → thank → than → that → bath → path → math → moth → cloth"]],
 hf=dict(dolch=["with","were"], fry=["with","were"]), lists={"th /th/ (unvoiced)":["with","thud","thin","thick","maths","moth","cloth","froth","bath","path","thank","think","thump","tenth","broth","teeth*","thing*"]})
P["48"] = dict(tag="The consonant digraph CH spells /ch/",
 notes=["CH spells /ch/ at the beginning of a word (chip) and at the end after a consonant or vowel (much, bench, rich). After a short vowel at the end of a word the /ch/ is usually spelled TCH - Lesson 69. For now, students read rich, much, such as they appear."],
 pa=dict(blend=["/ch/ /ĭ/ /p/ (chip)","/ch/ /ĭ/ /n/ (chin)","/s/ /ŭ/ /ch/ (such)","/r/ /ĭ/ /ch/ (rich)"], segment=["chop (/ch/ /ŏ/ /p/)","much (/m/ /ŭ/ /ch/)","lunch (/l/ /ŭ/ /n/ /ch/)","chest (/ch/ /ĕ/ /s/ /t/)"]),
 bd=dict(chain="chip → chop → chap → chat → chest → check → chick → chin → chum → much → such → rich → inch → bench → lunch", grid=g(["ch","nch","ck","th","sh","st","t","p"], ["ch"])),
 intro=["We know that a consonant digraph is two consonants that come together to make one sound, like SH and TH. Today we will learn the digraph CH. C and H together make a new sound, /ch/, like at the beginning of chicken.",
        "CH can come at the beginning of a word, such as chip and chin. CH can also come at the end of a word, such as such and rich, and after N, such as bench and lunch."],
 gesture="To make the /ch/ sound, put your teeth together and round your lips, then pop the air out with your voice off... (model). /ch/ is a quick sound. It is like /j/ without the voice. Watch me /ch/. You try /ch/.",
 soundwall="Add 'ch' under /ch/ (tongue lifted).", formation="Practise letter formation for ch.",
 spell=dict(ido=["chop"], wedo=["chip","much","lunch","chest"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="chip → chop → chap → chat → chest → check → chick → chin → chum → much → such → rich → inch → bench → lunch"),
 text_spell=["Chad had chips at lunch.","Did Chuck chat with the chick?","The rich man has a big chest."],
 chains=[["Phoneme Level: Targeted (ch- /ch/)","chip → chop → chap → chat → chin → chum → check → chest"],["Phoneme Level: Targeted (-ch /ch/)","much → such → rich → inch → bench → lunch → munch → punch"],["Phoneme Level: Intro Lesson","chip → chop → chap → chat → chest → check → chick → chin → chum → much → such → rich → inch → bench → lunch"]],
 hf=dict(dolch=["much","such","talk","walk"], fry=["much","such"]), lists={"ch- /ch/":["chop","chip","chat","check","chest","chin","chum","chap","chick","chill","chest","chunk","champ"],"-ch /ch/":["much","inch","such","rich","lunch","bench","munch","punch","pinch","branch","crunch","which*","chunk"]})
P["49"] = dict(tag="Digraphs review 1: ck, sh, th, ch",
 notes=["Review lesson. Word work sorts words by digraph. Emphasise that each digraph is two letters, one sound."],
 pa=dict(blend=["/sh/ /ĕ/ /d/ (shed)","/w/ /ĭ/ /th/ (with)","/ch/ /ĭ/ /p/ (chip)","/b/ /ă/ /k/ (back)"], segment=["this (/th/ /ĭ/ /s/)","much (/m/ /ŭ/ /ch/)","flash (/f/ /l/ /ă/ /sh/)","shock (/sh/ /ŏ/ /k/)"]),
 bd=dict(chain="chip → ship → shop → chop → chap → chat → that → than → then → them → thick → chick → check → shed → shell", grid=g(["ck","sh","th","ch","ll","ss","t","p"], ["sh","th","ch"])),
 intro=["We have learned four consonant digraphs: CK /k/, SH /sh/, TH /th/ and /th/, and CH /ch/. A digraph is two letters that spell one sound. Today we practise reading and spelling words with all of them.",
        "When you see two consonants together, check: is it a digraph (one sound) or a cluster (two sounds)? sh-i-p (3 sounds), s-l-i-p (4 sounds)."],
 gesture="Review the gestures for /sh/, /th/, /th/ and /ch/.", soundwall="No new grapheme. Review ck, sh, th, ch on the sound wall.", formation=None,
 spell=dict(ido=["shed"], wedo=["with","chip","back","much"]),
 ww=dict(type="Word Sort", text="Read and sort the words by digraph: ck, sh, th, ch. Words: shed, with, this, chip, much, them, back, maths, flash, shock, checks, black, wish, than, chat, duck.", chain="chip → ship → shop → chop → chap → chat → that → than → then → them → thick → chick → check"),
 text_spell=["She will be back in a flash.","Beth and Chad chat on the bench.","We can see the ship from the shed."],
 chains=[["Phoneme Level: Mixed Digraphs","chip → ship → shop → chop → chap → chat → that → than → then → them → thick → chick → check"],["Onset-Rime Level: -ash / -ack","cash → dash → rash → rack → back → sack → shack"]],
 hf=dict(dolch=[], fry=[]), lists={"ck":["back","black","shock","checks","duck","sick","clock"],"sh":["shed","flash","wish","ship","shop","dish","rush"],"th":["with","this","them","than","maths","thin","bath"],"ch":["chip","much","chat","chest","lunch","such","rich"]})
P["50"] = dict(tag="The digraphs WH /w/ and PH /f/",
 notes=["WH spells /w/ at the beginning of words (when, which, whip). In who, WH spells /h/ (heart word, Lesson 54). PH spells /f/ in words from Greek (phone, graph)."],
 pa=dict(blend=["/w/ /ĕ/ /n/ (when)","/w/ /ĭ/ /p/ (whip)","/f/ /ĭ/ /l/ (Phil)","/g/ /r/ /ă/ /f/ (graph)"], segment=["which (/w/ /ĭ/ /ch/)","whisk (/w/ /ĭ/ /s/ /k/)","whiff (/w/ /ĭ/ /f/)","whack (/w/ /ă/ /k/)"]),
 bd=dict(chain="when → whip → whiff → whisk → whim → which → whack → wham → sham → shim → shin → chin → thin", grid=g(["n","p","ff","sk","m","ch","ck","ph"], ["wh","ph"])),
 intro=["Today we will learn two more digraphs. The digraph WH spells /w/, the same sound as W, like at the beginning of whip and when. WH comes at the beginning of a word. Many question words start with wh: what, when, which, where, why.",
        "The digraph PH spells /f/, the same sound as F, like in phone and graph. PH can come at the beginning or end of a word. Words with PH come from Greek."],
 gesture="Review the gestures for /w/ (lips rounded, voice on) and /f/ (teeth on lip, voice off).", soundwall="Add 'wh' under /w/ and 'ph' under /f/.", formation=None,
 spell=dict(ido=["when"], wedo=["whip","which","graph"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="when → whip → whiff → whisk → whim → which → whack → wham → sham → shin → chin"),
 text_spell=["When will Phil get the whisk?","Which graph is it?","Ralph can whip up a snack."],
 chains=[["Phoneme Level: Targeted (wh- /w/)","when → whip → whiff → whisk → whim → which → whack → wham"],["Phoneme Level: Intro Lesson","when → whip → whiff → whisk → whim → which → whack → wham → sham → shin → chin"]],
 hf=dict(dolch=["when","which","could","would","should"], fry=["when","which","could","would","should"]), lists={"wh /w/":["when","whip","whim","whiff","which","whack","whisk","wham","whisker","whiz"],"ph /f/":["Phil","graph","Steph","Ralph","phone*","dolphin*","photo*","Joseph"]})
P["51"] = dict(tag="The grapheme NG spells /ŋ/",
 notes=["NG spells one sound, /ŋ/, at the end of a word or syllable (sing, long). It is a nasal sound made at the back of the mouth. Do not say /n/ + /g/."],
 pa=dict(blend=["/s/ /ĭ/ /ŋ/ (sing)","/l/ /ŏ/ /ŋ/ (long)","/r/ /ĭ/ /ŋ/ (ring)","/s/ /w/ /ĭ/ /ŋ/ (swing)"], segment=["hang (/h/ /ă/ /ŋ/)","song (/s/ /ŏ/ /ŋ/)","thing (/th/ /ĭ/ /ŋ/)","bring (/b/ /r/ /ĭ/ /ŋ/)"]),
 bd=dict(chain="sing → ring → rang → hang → bang → bong → song → long → lung → rung → sung → sing → sting → string", grid=g(["ng","n","ck","sh","th","ch","t","g"], ["st","str","br","sw","sl","cl","fl"])),
 intro=["Today we are learning about the letters NG. N and G together spell one sound, /ŋ/, like at the end of ring. It is a nasal sound: the air goes through your nose.",
        "NG comes at the end of a word or syllable, such as king and long. NG never comes at the beginning of a word."],
 gesture="To make the /ŋ/ sound as in 'ring', pull the back of your tongue up to the back of the roof of your mouth and let your voice hum through your nose... (model). /ŋ/ is a continuous sound. Watch me /ŋŋŋ/. You try /ŋŋŋ/.",
 soundwall="Add 'ng' under /ŋ/ (tongue pulled back).", formation=None,
 spell=dict(ido=["sing"], wedo=["long","ring","thing","bring"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="sing → ring → rang → hang → bang → bong → song → long → lung → rung → sung → sting → string"),
 text_spell=["The king can sing a long song.","Bring the ring to the shop.","Did the bell ring at the wedding?"],
 chains=[["Onset-Rime Level: -ing","sing → ring → wing → king → thing → bring → swing → sting → string"],["Onset-Rime Level: -ang","hang → bang → rang → sang → fang → clang"],["Onset-Rime Level: -ong","long → song → gong → strong → prong"],["Onset-Rime Level: -ung","rung → lung → sung → hung → stung → swung"]],
 hf=dict(dolch=["long","sing","bring","thing","or","for"], fry=["long","thing","or","for"]), lists={"ng /ŋ/":["sing","hang","long","song","sang","ring","wing","thing","bring","swing","rung","king","bang","lung","strong","sting","string","gong","hung","clang"]})
P["52"] = dict(tag="The grapheme NK spells /ŋk/",
 notes=["In NK, the N spells /ŋ/ (not /n/) and the K spells /k/: pink = /p/ /ĭ/ /ŋ/ /k/. Count it as two sounds when segmenting. Some programs treat 'nk' as a unit for the visual drill, as UFLI does."],
 pa=dict(blend=["/p/ /ĭ/ /ŋ/ /k/ (pink)","/b/ /ă/ /ŋ/ /k/ (bank)","/s/ /ĭ/ /ŋ/ /k/ (sink)","/th/ /ĭ/ /ŋ/ /k/ (think)"], segment=["sunk (/s/ /ŭ/ /ŋ/ /k/)","drink (/d/ /r/ /ĭ/ /ŋ/ /k/)","trunk (/t/ /r/ /ŭ/ /ŋ/ /k/)","thank (/th/ /ă/ /ŋ/ /k/)"]),
 bd=dict(chain="pink → sink → link → wink → think → thank → bank → sank → sunk → dunk → junk → bunk → trunk → drunk → drink", grid=g(["nk","ng","ck","th","sh","ch","st","t"], ["th","sh","ch","dr","tr","st","cl","pl","sh"])),
 intro=["We learned that NG spells /ŋ/. Today we will look at NK. When N comes before K, the N spells /ŋ/ and the K spells /k/. So NK spells two sounds, /ŋ/ /k/, like at the end of pink.",
        "NK comes at the end of a word, such as pink and sunk. It never comes at the beginning of a word."],
 gesture="Say /ŋ/ (voice through the nose, tongue back) then /k/ (quick pop): /ŋk/. Watch me /ŋk/. You try /ŋk/.",
 soundwall="Add 'nk' under /ŋ/ with a note that k follows.", formation=None,
 spell=dict(ido=["pink"], wedo=["bank","think","drink","trunk"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="pink → sink → link → wink → think → thank → bank → sank → sunk → dunk → junk → bunk → trunk → drunk → drink"),
 text_spell=["The pink sock sank in the sink.","I think Frank can drink it.","Thank you for the junk in the trunk."],
 chains=[["Onset-Rime Level: -ink","pink → sink → link → wink → think → drink → stink → blink"],["Onset-Rime Level: -ank","bank → sank → tank → thank → drank → blank → plank → prank"],["Onset-Rime Level: -unk","sunk → dunk → junk → bunk → trunk → chunk → skunk"]],
 hf=dict(dolch=["think","thank","drink","there","where"], fry=["think","there","where"]), lists={"nk /ŋk/":["bank","think","sank","pink","stink","drink","frank","trunk","prank","sink","link","wink","tank","thank","blank","plank","sunk","junk","bunk","chunk","skunk","honk"]})
P["53"] = dict(tag="Digraphs review 2 (including three-consonant clusters: shr, thr, spl, str, scr)",
 notes=["Review of all digraphs plus words that begin with a digraph and a consonant (shrimp, three) or three consonants (splash, string)."],
 pa=dict(blend=["/sh/ /r/ /ĭ/ /m/ /p/ (shrimp)","/th/ /r/ /ĭ/ /l/ (thrill)","/s/ /t/ /r/ /ŏ/ /ŋ/ (strong)","/s/ /p/ /l/ /ă/ /sh/ (splash)"], segment=["shrug (/sh/ /r/ /ŭ/ /g/)","thrash (/th/ /r/ /ă/ /sh/)","string (/s/ /t/ /r/ /ĭ/ /ŋ/)","shrink (/sh/ /r/ /ĭ/ /ŋ/ /k/)"]),
 bd=dict(chain="shrug → shrub → shrimp → shrink → shrill → thrill → thrash → thrush → thrust → trust → strut → strum → string → strong → strand", grid=g(["ng","nk","ck","sh","th","ch","ll","mp","st","nd"], ["shr","thr","str","spl","scr","spr"])),
 intro=["We have learned the digraphs ck, sh, th, ch, wh, ph, ng and nk. Today we will read longer words. Some words start with a digraph and another consonant, such as shrimp (sh-r) and three (th-r). Some start with three consonants, such as splash (s-p-l) and string (s-t-r).",
        "Say every sound. A digraph is one sound; a cluster is two or three separate sounds."],
 gesture="Review /sh/, /th/, /ch/, /ŋ/.", soundwall="No new grapheme.", formation=None,
 spell=dict(ido=["shrimp"], wedo=["strong","splash","thrill","string"]),
 ww=dict(type="Word Sort", text="Read and sort the words by the digraph they contain: sh, th, ch, wh, ph, ng, nk. Words: shrimp, strong, shrug, thrash, thrill, champ, splash, string, when, graph, think, which, sting, thanks.", chain="shrug → shrub → shrimp → shrink → shrill → thrill → thrash → thrush → thrust → trust → strut → strum → string → strong"),
 text_spell=["I could not just shrug it off.","Should I toss the scraps in the sink?","The strong man can splash and swim."],
 chains=[["Phoneme Level: shr-/thr-","shrug → shrub → shrimp → shrink → shrill → thrill → thrash → thrush → thrust"],["Phoneme Level: str-/spl-/scr-","strap → strip → strum → strut → string → strong → splash → split → scrap → scrub"]],
 hf=dict(dolch=[], fry=[]), lists={"shr / thr":["shrimp","shrug","shrub","shrill","shrink","shred","thrash","thrill","throb","thrust","thrush","three*"],"spl / str / scr / spr":["splash","split","splint","string","strong","strap","strip","strum","scrap","scrub","script","sprint","spring","sprang"]})
P["54"] = dict(tag="The VCe pattern a_e spells /ā/",
 notes=["VCe = vowel, consonant, silent e. The silent e signals that the vowel says its long sound (its name). Teach the pattern by changing short-vowel words: cap → cape, mad → made.",
        "Word work uses writing or magnetic letters with a separate e tile."],
 pa=dict(blend=["/m/ /ā/ /d/ (made)","/k/ /ā/ /m/ (came)","/t/ /ā/ /k/ (take)","/g/ /ā/ /m/ (game)"], segment=["name (/n/ /ā/ /m/)","late (/l/ /ā/ /t/)","gave (/g/ /ā/ /v/)","skate (/s/ /k/ /ā/ /t/)"]),
 bd=dict(chain="mad → made → mate → male → sale → same → came → cane → cape → tape → take → bake → lake → late → gate", grid=dict(initial=["m","c","t","b","l","g","s","n","r","sk","sh","pl"], medial=["a"], final=["de","te","le","me","ne","pe","ke","ve","ze","d","t","m","n","p"])),
 intro=["We have learned that the letter A spells /ă/ as in cat. Today we will learn that A can also spell /ā/, the long A sound, which is the letter's name.",
        "Look at this word: cap. Now I add an e at the end: cape. The e at the end is silent, but it does a job: it tells the vowel to say its name. A, consonant, silent e - we call this the VCe pattern. c-a-p-e, cape. The vowel says /ā/.",
        "When you read a word with a vowel, one consonant and an e at the end, the vowel is long: made, same, take. When you spell, remember the silent e at the end."],
 gesture="To make the /ā/ sound as in 'acorn', start with your mouth open a little and glide to a smile... (model). Be sure your voice is on. /ā/ is a continuous sound. Watch me /āāā/. You try /āāā/.",
 soundwall="Add 'a_e' under /ā/ on the vowel valley.", formation=None,
 spell=dict(ido=["made"], wedo=["came","take","name","late"]),
 ww=dict(type="Word Work with Manipulative Letters (VCe)", chain="mad → made → mate → male → sale → same → came → cane → cape → tape → take → bake → lake → late → gate"),
 text_spell=["Jane made a cake.","Take the tape to the gate.","Dave came late to the game."],
 chains=[["Phoneme Level: short to long","cap → cape, mad → made, tap → tape, can → cane, rat → rate, plan → plane"],["Onset-Rime Level: -ake","bake → cake → lake → make → take → wake → shake → snake"],["Onset-Rime Level: -ame","came → game → name → same → tame → flame → shame"],["Phoneme Level: Intro Lesson","mad → made → mate → male → sale → same → came → cane → cape → tape → take → bake → lake → late → gate"]],
 hf=dict(dolch=["made","came","make","take","name","gave","who","here"], fry=["made","came","make","take","name"]), lists={"a_e /ā/":["made","came","make","same","take","name","gave","late","games","state","skate","cake","lake","bake","gate","plane","plate","shape","shake","snake","wave","cave","safe","tape","cape","whale","grape"]})
P["55"] = dict(tag="The VCe pattern i_e spells /ī/",
 pa=dict(blend=["/r/ /ī/ /d/ (ride)","/l/ /ī/ /k/ (like)","/t/ /ī/ /m/ (time)","/f/ /ī/ /v/ (five)"], segment=["side (/s/ /ī/ /d/)","mile (/m/ /ī/ /l/)","white (/w/ /ī/ /t/)","while (/w/ /ī/ /l/)"]),
 bd=dict(chain="bit → bite → kite → site → side → ride → hide → hive → five → fine → line → lime → time → dime → dine", grid=dict(initial=["b","k","s","r","h","f","l","t","d","m","w","wh","sl","sh","pr"], medial=["i"], final=["te","de","ve","ne","me","ke","le","pe","t","d","n","m"])),
 intro=["We learned that silent e makes A say its name: cape. Today we will learn that the VCe pattern works with I too. I, consonant, silent e: the I says /ī/, its name, like in kite.",
        "Look: bit. Add the silent e: bite. b-i-t-e, bite. The I is long. Words with i_e: ride, like, time, five."],
 gesture="To make the /ī/ sound as in 'ice cream', open your mouth wide and glide to a small smile... (model). Be sure your voice is on. /ī/ is a continuous sound. Watch me /īīī/. You try /īīī/.",
 soundwall="Add 'i_e' under /ī/ on the vowel valley.", formation=None,
 spell=dict(ido=["ride"], wedo=["like","time","five","white"]),
 ww=dict(type="Word Work with Manipulative Letters (VCe)", chain="bit → bite → kite → site → side → ride → hide → hive → five → fine → line → lime → time → dime"),
 text_spell=["Mike likes to ride his bike.","I will get my white kite.","Jake can dive by the slide."],
 chains=[["Phoneme Level: short to long","bit → bite, kit → kite, rid → ride, fin → fine, pin → pine, slid → slide"],["Onset-Rime Level: -ide","ride → side → hide → wide → tide → slide → bride → pride"],["Onset-Rime Level: -ine","fine → line → mine → nine → pine → vine → shine → spine"]],
 hf=dict(dolch=["like","ride","five","white","by","my"], fry=["like","ride","five","white","by","my"]), lists={"i_e /ī/":["fine","ride","like","side","line","time","five","mile","life","while","white","bike","kite","hide","wide","nine","pine","shine","slide","bride","dime","dive","drive","smile","prize","size","wipe"]})
P["56"] = dict(tag="The VCe pattern o_e spells /ō/",
 pa=dict(blend=["/r/ /ō/ /p/ (rope)","/n/ /ō/ /z/ (nose)","/h/ /ō/ /m/ (home)","/th/ /ō/ /z/ (those)"], segment=["note (/n/ /ō/ /t/)","rode (/r/ /ō/ /d/)","stove (/s/ /t/ /ō/ /v/)","globe (/g/ /l/ /ō/ /b/)"]),
 bd=dict(chain="hop → hope → rope → robe → rode → rose → nose → note → vote → cone → bone → tone → stone → stole → stove", grid=dict(initial=["h","r","n","v","c","b","t","st","gl","ph","cl","th","sm","wh"], medial=["o"], final=["pe","be","de","se","te","ne","le","ve","ke","me","p","b","d","t","n"])),
 intro=["We know the VCe pattern with a_e and i_e. Today we will learn o_e. O, consonant, silent e: the O says /ō/, its name, like in home.",
        "Look: hop. Add the silent e: hope. h-o-p-e, hope. Words with o_e: rope, nose, note, home."],
 gesture="To make the /ō/ sound as in 'open', round your lips and glide... (model). Be sure your voice is on. /ō/ is a continuous sound. Watch me /ōōō/. You try /ōōō/.",
 soundwall="Add 'o_e' under /ō/ on the vowel valley.", formation=None,
 spell=dict(ido=["rope"], wedo=["nose","home","note","those"]),
 ww=dict(type="Word Work with Manipulative Letters (VCe)", chain="hop → hope → rope → robe → rode → rose → nose → note → vote → cone → bone → tone → stone → stove"),
 text_spell=["The rope fell on the stone.","He is at home with a cold nose.","Did those men vote?"],
 chains=[["Phoneme Level: short to long","hop → hope, not → note, rob → robe, rod → rode, cod → code, glob → globe"],["Onset-Rime Level: -one","bone → cone → tone → zone → stone → phone → alone"],["Onset-Rime Level: -ose","nose → rose → hose → pose → those → close → chose"]],
 hf=dict(dolch=["home","those","close"], fry=["home","those"]), lists={"o_e /ō/":["rope","nose","note","rode","home","rose","those","phone","close","stove","globe","hope","bone","cone","stone","vote","joke","poke","smoke","broke","froze","drove","whole","hole","pole","code","robe"]})
P["57"] = dict(tag="VCe review 1 and e_e /ē/",
 notes=["e_e is rare (these, theme, eve, Pete, complete). Review a_e, i_e and o_e today as well."],
 pa=dict(blend=["/th/ /ē/ /z/ (these)","/th/ /ē/ /m/ (theme)","/ē/ /v/ (eve)","/p/ /ē/ /t/ (Pete)"], segment=["home (/h/ /ō/ /m/)","make (/m/ /ā/ /k/)","time (/t/ /ī/ /m/)","white (/w/ /ī/ /t/)"]),
 bd=dict(chain="mate → mite → mote → mute* → Pete → pete → pet → met → mete → meme → theme → these → eve → Steve", grid=dict(initial=["m","p","th","st","t","sh","wh","l","r"], medial=["a","e","i","o"], final=["te","me","se","ve","ke","ne","de","t","m","n"])),
 intro=["We have learned the VCe pattern with a_e, i_e and o_e. Today we will review those and learn e_e. E, consonant, silent e: the E says /ē/, its name, like in these.",
        "Not many words use e_e: these, theme, eve, Pete, Steve, complete. Most words with the /ē/ sound use other spellings that we will learn later."],
 gesture="To make the /ē/ sound as in 'eagle', smile wide with your teeth close together... (model). Be sure your voice is on. /ē/ is a continuous sound. Watch me /ēēē/. You try /ēēē/.",
 soundwall="Add 'e_e' under /ē/ on the vowel valley.", formation=None,
 spell=dict(ido=["these"], wedo=["theme","make","time","home"]),
 ww=dict(type="Word Work with Manipulative Letters (VCe)", chain="mat → mate → mite → mote → note → not → net → mete → theme → these"),
 text_spell=["Pete and I hike by the stone maze.","These five cats like to sit on the same rug.","What time will the shop close?"],
 chains=[["Phoneme Level: Vowel Changes (VCe)","mate → mite → mote → mete, cane → cone, fine → fane* → fone*"],["Phoneme Level: Mixed VCe","made → make → mike → mine → mine → nine → note → vote → vase → base → bake"]],
 hf=dict(dolch=["these"], fry=["these"]), lists={"e_e /ē/":["these","theme","eve","Pete","Steve","gene","scene*","complete*","athlete*","delete*"],"VCe review":["home","make","state","time","white","those","came","life","cake","five","note","game","mile","rope"]})
P["58"] = dict(tag="The VCe pattern u_e spells /ū/ and /yū/",
 notes=["u_e spells two sounds: /ū/ as in rule, flute, and /yū/ as in cute, mule, use. When reading, try /yū/ first; if it does not make a word, try /ū/."],
 pa=dict(blend=["/r/ /ū/ /l/ (rule)","/t/ /ū/ /b/ (tube)","/k/ /yū/ /t/ (cute)","/m/ /yū/ /l/ (mule)"], segment=["June (/j/ /ū/ /n/)","flute (/f/ /l/ /ū/ /t/)","use (/yū/ /z/)","mute (/m/ /yū/ /t/)"]),
 bd=dict(chain="cub → cube → tube → tune → dune → June → rule → rude → dude → duke → mute → cute → cut → cub", grid=dict(initial=["c","t","d","j","r","m","fl","pr","h","f"], medial=["u"], final=["be","ne","le","de","ke","te","me","se","b","n","t"])),
 intro=["We have learned the VCe pattern with a_e, i_e, o_e and e_e. Today we will learn u_e. U, consonant, silent e can spell two sounds.",
        "Sometimes u_e says /ū/ as in rule and flute. Sometimes u_e says /yū/ as in cute and mule. The /yū/ sound is the name of the letter U. When you read a u_e word, try /yū/ first; if it does not sound like a real word, try /ū/."],
 gesture="To make the /ū/ sound as in 'spoon', round your lips tightly... (model). To make /yū/ as in 'unicorn', start with /y/ and glide into /ū/. Both sounds have the voice on. Watch me /ū/, /yū/. You try.",
 soundwall="Add 'u_e' under /ū/ and under /yū/ on the vowel valley.", formation=None,
 spell=dict(ido=["rule"], wedo=["tube","cute","June","use"]),
 ww=dict(type="Word Work with Manipulative Letters (VCe)", chain="cub → cube → tube → tune → dune → June → rule → rude → dude → duke → mute → cute → cut"),
 text_spell=["Luke broke a rule.","Did you see that cute dog?","June can use the flute in tune."],
 chains=[["Phoneme Level: short to long","cub → cube, tub → tube, cut → cute, us → use, dun → dune, hug → huge"],["Onset-Rime Level: -une / -ute","tune → dune → June → prune, cute → mute → flute → brute"]],
 hf=dict(dolch=["use","one","once"], fry=["use","one"]), lists={"u_e /ū/":["rule","rude","tube","tune","flute","June","dune","duke","prune","brute","plume"],"u_e /yū/":["mule","cute","use","mute","cube","fuse","huge","muse","fume","puke"]})
P["59"] = dict(tag="VCe review 2 (all five vowels)",
 pa=dict(blend=["/m/ /ā/ /d/ (made)","/b/ /ō/ /n/ (bone)","/k/ /yū/ /b/ (cube)","/n/ /ā/ /m/ (name)"], segment=["grade (/g/ /r/ /ā/ /d/)","drove (/d/ /r/ /ō/ /v/)","chime (/ch/ /ī/ /m/)","these (/th/ /ē/ /z/)"]),
 bd=dict(chain="bake → bike → like → lime → time → tame → tone → bone → cone → cane → cape → cope → hope → hose → those → these", grid=dict(initial=["b","l","t","c","h","th","sh","wh","gr","dr","sl","st","sm","pl"], medial=["a","e","i","o","u"], final=["ke","me","ne","pe","se","de","te","ve","le","be","ze"])),
 intro=["We have learned the VCe pattern with all five vowels: a_e /ā/, i_e /ī/, o_e /ō/, e_e /ē/, u_e /ū/ /yū/. Today we practise reading and spelling all of them.",
        "When you see a vowel, one consonant and silent e at the end, the vowel says its name. Look at the vowel first, then read: sh-a-p-e, shape."],
 gesture="Review the long vowel gestures using the vowel valley.", soundwall="No new grapheme. Review all VCe cards.", formation=None,
 spell=dict(ido=["made"], wedo=["bone","cube","name","chime"]),
 ww=dict(type="Word Work with Manipulative Letters (VCe)", chain="bake → bike → like → lime → time → tame → tone → bone → cone → cane → cape → cope → hope → hose → those"),
 text_spell=["Jane gave Steve one white rose.","Should Luke bake the cake at home?","Those five mules ran up the slope."],
 chains=[["Phoneme Level: Vowel Changes (VCe)","bake → bike, cane → cone, cape → cope, tape → type*, mate → mite → mote → mute"]],
 hf=dict(dolch=[], fry=[]), lists={"VCe review":["made","bone","cube","name","grade","drove","chime","shines","eve","these","theme","June","tube","tune","cute","time","same","Steve","phone","plane","slide","smoke","whale","stone","plate"]})
P["60"] = dict(tag="_ce spells /s/ (soft c)",
 notes=["C spells /s/ when it is followed by e (also i and y - Lesson 117). Words ending in -ce: the e signals the soft c and often also makes the vowel long (race, ice), but not always (dance, fence, since)."],
 pa=dict(blend=["/r/ /ā/ /s/ (race)","/ī/ /s/ (ice)","/f/ /ā/ /s/ (face)","/p/ /l/ /ā/ /s/ (place)"], segment=["mice (/m/ /ī/ /s/)","nice (/n/ /ī/ /s/)","space (/s/ /p/ /ā/ /s/)","twice (/t/ /w/ /ī/ /s/)"]),
 bd=dict(chain="ice → rice → mice → nice → dice → price → prince → since → fence → hence → dance → lance → ace → race → face → place → space", grid=dict(initial=["r","m","n","d","pr","f","pl","sp","tr","l","tw","sl","gr","br"], medial=["a","i","o","u","e"], final=["ce","nce","ke","te","de","pe"])),
 intro=["We know that C spells /k/ as in cat. Today we will learn that C can also spell /s/. When C is followed by E, it spells /s/, like at the end of race and ice.",
        "-ce comes at the end of a word: race, nice, place. The e is silent. It tells the C to say /s/, and it often makes the vowel long: r-a-ce, race. In some words the vowel stays short: dance, fence."],
 gesture="Review the /s/ gesture.", soundwall="Add '_ce' (c) under /s/.", formation=None,
 spell=dict(ido=["race"], wedo=["ice","nice","face","place"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="ice → rice → mice → nice → dice → price → prince → since → fence → dance → ace → race → face → place → space"),
 text_spell=["I use a plate for my rice.","The mice ran to a nice place.","What is the price of the ice?"],
 chains=[["Onset-Rime Level: -ice","ice → rice → mice → nice → dice → price → slice → twice → spice"],["Onset-Rime Level: -ace","ace → race → face → place → space → lace → trace → grace"],["Onset-Rime Level: -nce","dance → fence → since → prince → chance → bounce*"]],
 hf=dict(dolch=["once"], fry=["once"]), lists={"_ce /s/":["pace","twice","face","race","place","space","trace","ice","mice","nice","price","rice","dice","slice","spice","lace","grace","dance","fence","since","prince","chance","glance","France"]})
P["61"] = dict(tag="_ge spells /j/ (soft g)",
 notes=["G spells /j/ when followed by e (also i and y - Lesson 117). Words ending in -ge: cage, page, huge. J is never used at the end of a word; -ge is used instead (and -dge after a short vowel, Lesson 70)."],
 pa=dict(blend=["/p/ /ā/ /j/ (page)","/ā/ /j/ (age)","/h/ /yū/ /j/ (huge)","/k/ /ā/ /j/ (cage)"], segment=["wage (/w/ /ā/ /j/)","stage (/s/ /t/ /ā/ /j/)","range (/r/ /ā/ /n/ /j/)","change (/ch/ /ā/ /n/ /j/)"]),
 bd=dict(chain="age → cage → page → wage → rage → stage → sage → sale → tale → tame → came → cave → cage → huge", grid=dict(initial=["c","p","w","r","st","s","h","ch","str","l","m","b","gr"], medial=["a","u","i","o"], final=["ge","nge","ce","ke","te","le","me","ve"])),
 intro=["We know that G spells /g/ as in goat. Today we will learn that G can also spell /j/. When G is followed by E, it usually spells /j/, like at the end of page and cage.",
        "-ge comes at the end of a word: cage, huge, stage. The e is silent. It tells the G to say /j/, and it usually makes the vowel long: c-a-ge, cage. After N the vowel stays short or changes: range, change, hinge.",
        "Remember: we never write J at the end of a word. We use -ge."],
 gesture="Review the /j/ gesture (teeth together, lips round, voice on, quick).", soundwall="Add '_ge' (g) under /j/.", formation=None,
 spell=dict(ido=["page"], wedo=["age","huge","cage","stage"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="age → cage → page → wage → rage → stage → sage → sale → tale → tame → came → cave → cage → huge"),
 text_spell=["Did Bruce like the rice?","The mice in that cage are huge.","The stage is a place where Grace shines."],
 chains=[["Onset-Rime Level: -age","age → cage → page → wage → rage → sage → stage"],["Onset-Rime Level: -nge","range → change → strange → hinge → plunge → lunge"]],
 hf=dict(dolch=[], fry=[]), lists={"_ge /j/":["page","age","huge","wage","cage","rage","stage","range","change","strange","hinge","plunge","lunge","fringe","large*","charge*","sponge"]})
P["62"] = dict(tag="VCe review 3 and VCe exceptions (have, give, love, come, some, done)",
 notes=["Some very common words look like VCe words but the vowel is short: have, give, live. Words ending in -ve always have an e (English words do not end in v). In come, some, love, done, none the O spells /ŭ/. Teach these as heart words."],
 pa=dict(blend=["/h/ /ă/ /v/ (have)","/s/ /ŭ/ /m/ (some)","/g/ /ĭ/ /v/ (give)","/l/ /ŭ/ /v/ (love)"], segment=["come (/k/ /ŭ/ /m/)","done (/d/ /ŭ/ /n/)","live (/l/ /ĭ/ /v/)","none (/n/ /ŭ/ /n/)"]),
 bd=dict(chain="bake → like → note → race → nice → cage → huge → have → give → live → love → dove → come → some → done → none", grid=dict(initial=["b","l","n","r","c","h","g","d","s","wh","th","sh"], medial=["a","i","o","u","e"], final=["ke","te","ce","ge","ve","me","ne"])),
 intro=["We have learned that the VCe pattern makes the vowel say its name: bake, like, note, and that -ce spells /s/ and -ge spells /j/. Today we review all of these.",
        "We will also learn some exceptions. Some VCe words do not follow the rule. In have, give and live the vowel is short. In come, some, love, dove, done and none the O spells /ŭ/. These words end in e because English words do not end in v, or because of their history. We learn them by heart."],
 gesture="Review long vowel gestures.", soundwall="Add the exception words to the heart word display.", formation=None,
 spell=dict(ido=["have"], wedo=["give","come","some","done"]),
 ww=dict(type="Word Sort", text="Read and sort the words: VCe long vowel (bake, like, note, race, cage, huge) or exception with a short/other vowel (have, give, live, love, come, some, done, none).", chain="bake → like → note → race → nice → cage → huge → have → give → live → love → dove → come → some → done → none"),
 text_spell=["Steve and Jane have to race home.","Did June give you these for a nice price?","Kate and Luke live close to the huge lake."],
 chains=[["Phoneme Level: Mixed VCe","bake → bike → like → life → wife → wipe → ripe → rope → hope → hole → whole"]],
 hf=dict(dolch=["have","give","live","come","some","love","done"], fry=["have","give","live","come","some"]), lists={"VCe exceptions":["have","some","give","love","dove","live","come","done","none","gone*","above*","glove","shove"],"VCe review":["bake","like","note","race","nice","cage","huge","make","time","those","these","cute","rule","place","stage"]})
