# Lesson plan data, lessons 1-20 (reconstructed in the UFLI Foundations format; AUS/NZ pronunciation)
P = {}
P["1"] = dict(tag="The grapheme A spells /ă/",
 notes=["This is the first core lesson. Only Steps 1, 5 and 7 are used. Steps 2-4 begin once a few graphemes are known.",
        "Use the sound wall mouth picture for /ă/ (apple). Watch for the /ă/ sound in cat (Australian/NZ short a)."],
 pa=dict(blend=["/ă/ /t/ (at)","/m/ /ă/ /t/ (mat)","/s/ /ă/ /t/ (sat)","/ă/ /m/ (am)"], segment=["at (/ă/ /t/)","sat (/s/ /ă/ /t/)","am (/ă/ /m/)","map (/m/ /ă/ /p/)"]),
 intro=["Today we are learning about the letter A. A is a vowel. The letter A spells the /ă/ sound like at the beginning of apple.",
        "A can come at the beginning of a word, such as at and as. A can also come in the middle of a word, such as cat and map."],
 gesture="To make the /ă/ sound as in 'apple', open your mouth wide like this... (model). Be sure your voice is on. Like all vowels, /ă/ is a continuous sound that can be stretched out (use continuous hand motion). Watch me /ăăă/. You try /ăăă/.",
 soundwall="Add 'a' under /ă/ on the vowel valley.", formation="Practise letter formation for uppercase A and lowercase a (see the letter formation animations in the slides).",
 read=dict(ido=[], wedo=[]), spell=dict(ido=[], wedo=[]),
 irr_teach_note="the: TH has not been introduced yet; E spells /ŭ/ (or /ē/ before a vowel). Learn the word 'by heart'.",
 hf=dict(dolch=["a","the"], fry=["a","the"]), lists={"a /ă/ (words to come)":["a"]})
P["2"] = dict(tag="The grapheme M spells /m/",
 notes=["Steps 2 (Visual Drill) begins today with the grapheme a. Auditory and blending drills begin in Lesson 5."],
 pa=dict(blend=["/m/ /ă/ /t/ (mat)","/m/ /ă/ /p/ (map)","/ă/ /m/ (am)","/m/ /ŏ/ /p/ (mop)"], segment=["mat (/m/ /ă/ /t/)","am (/ă/ /m/)","mad (/m/ /ă/ /d/)","gum (/g/ /ŭ/ /m/)"]),
 intro=["Today we are learning about the letter M. M is a consonant. The letter M spells the /m/ sound like at the beginning of mouse.",
        "M can come at the beginning of a word, such as mad and mop. M can also come at the end of a word, such as gum and him."],
 gesture="To make the /m/ sound as in 'mouse', put your lips together and hum like this... (model). Be sure your voice is on. /m/ is a continuous sound that can be stretched out (use continuous hand motion). Watch me /mmm/. You try /mmm/.",
 soundwall="Add 'm' under /m/ (lips together).", formation="Practise letter formation for uppercase M and lowercase m.",
 read=dict(ido=["am"], wedo=["ma","mam"]), spell=dict(ido=["am"], wedo=["ma"]),
 hf=dict(dolch=["am"], fry=["am"]), lists={"m /m/":["am","ma","mam"]})
P["3"] = dict(tag="The grapheme S spells /s/",
 pa=dict(blend=["/s/ /ă/ /t/ (sat)","/s/ /ă/ /m/ (Sam)","/ă/ /s/ (as)","/m/ /ă/ /s/ (mass)"], segment=["sat (/s/ /ă/ /t/)","Sam (/s/ /ă/ /m/)","sap (/s/ /ă/ /p/)","sip (/s/ /ĭ/ /p/)"]),
 intro=["Today we are learning about the letter S. S is a consonant. The letter S spells the /s/ sound like at the beginning of sun.",
        "S can come at the beginning of a word, such as sat and sip. S can also come at the end of a word, such as bus and gas."],
 gesture="To make the /s/ sound as in 'sun', put your teeth together, keep your lips open and push air through like a snake... (model). Your voice is off because this is a quiet sound. /s/ is a continuous sound that can be stretched out. Watch me /sss/. You try /sss/.",
 soundwall="Add 's' under /s/ (tongue behind top teeth).", formation="Practise letter formation for uppercase S and lowercase s.",
 read=dict(ido=["Sam"], wedo=["am","sam","mas"]), spell=dict(ido=["Sam"], wedo=["am"]),
 irr_teach_note="I: I spells /ī/, which has not been introduced yet. Temporarily irregular.",
 hf=dict(dolch=["I"], fry=["I"]), lists={"s /s/":["am","Sam","mass","as"]})
P["4"] = dict(tag="The grapheme T spells /t/",
 pa=dict(blend=["/ă/ /t/ (at)","/m/ /ă/ /t/ (mat)","/s/ /ă/ /t/ (sat)","/t/ /ă/ /p/ (tap)"], segment=["at (/ă/ /t/)","sat (/s/ /ă/ /t/)","tap (/t/ /ă/ /p/)","top (/t/ /ŏ/ /p/)"]),
 intro=["Today we are learning about the letter T. T is a consonant. The letter T spells the /t/ sound like at the beginning of tiger.",
        "T can come at the beginning of a word, such as tap and top. T can also come at the end of a word, such as at and sat."],
 gesture="To make the /t/ sound as in 'tiger', put the tip of your tongue behind your top teeth and pop the air out... (model). Your voice is off. /t/ is a quick, stop sound. Do not add /uh/ after it. Watch me /t/. You try /t/.",
 soundwall="Add 't' under /t/ (tongue behind top teeth).", formation="Practise letter formation for uppercase T and lowercase t.",
 spell=dict(ido=["at"], wedo=["mat","sat"]),
 ww=dict(type="Word Work with Manipulative Letters (introduction)", chain="at → mat → sat → at"),
 chains=[["Onset-Rime Level: -at","at → mat → sat"]],
 hf=dict(dolch=["at"], fry=["at"]), lists={"t /t/":["at","mat","sat","tam","Tam","tat","mast"]})
P["5"] = dict(tag="Blending VC and CVC words with a, m, s, t",
 notes=["Today is the first lesson with a full Word Work step. Lesson 5 explicitly teaches the routine for word work with manipulative letters (see the manual, pp. 16-17 and 30).",
        "Steps 3 (Auditory Drill) and 4 (Blending Drill) begin today."],
 pa=dict(blend=["/s/ /ă/ /t/ (sat)","/m/ /ă/ /t/ (mat)","/ă/ /m/ (am)","/t/ /ă/ /m/ (tam)"], segment=["at (/ă/ /t/)","mat (/m/ /ă/ /t/)","Sam (/s/ /ă/ /m/)","sat (/s/ /ă/ /t/)"]),
 bd=dict(chain="at → mat → sat → Sam → am → at", grid=dict(initial=["m","s","t"], medial=["a"], final=["t","m","s"])),
 intro=["We have learned four letters and their sounds: a, m, s, t. Today we will use them to read and spell words. Some words have a vowel and a consonant (VC), like at. Some words have a consonant, a vowel and a consonant (CVC), like mat.",
        "To read a word, we say each sound and then blend the sounds together: /mmmăăăt/, mat. To spell a word, we say the word, count the sounds, and write a letter for each sound."],
 gesture="Review the articulatory gestures for /ă/, /m/, /s/ and /t/ as needed.", soundwall="No new grapheme. Review a, m, s, t on the sound wall.", formation=None,
 read=dict(ido=["at"], wedo=["mat","sat","Sam","am","tam"]), spell=dict(ido=["mat"], wedo=["sat","at","am"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="at → mat → sat → sat → at → am → Sam"),
 text_spell=["I sat.","I am Sam."],
 chains=[["Onset-Rime Level: -at","at → mat → sat"],["Phoneme Level: Intro Lesson","at → mat → sat → sat → at → am → Sam"]],
 hf=dict(dolch=["and","am","at"], fry=["and","at"]), lists={"VC & CVC":["at","am","as","mat","sat","Sam","tam","mass"]})
P["6"] = dict(tag="The grapheme P spells /p/",
 pa=dict(blend=["/p/ /ă/ /t/ (pat)","/m/ /ă/ /p/ (map)","/t/ /ă/ /p/ (tap)","/s/ /ă/ /p/ (sap)"], segment=["pat (/p/ /ă/ /t/)","map (/m/ /ă/ /p/)","tap (/t/ /ă/ /p/)","Pam (/p/ /ă/ /m/)"]),
 bd=dict(chain="at → mat → sat → sap → tap → map → mat → pat", grid=dict(initial=["m","s","t","p"], medial=["a"], final=["t","m","s","p"])),
 intro=["Today we are learning about the letter P. P is a consonant. The letter P spells the /p/ sound like at the beginning of pig.",
        "P can come at the beginning of a word, such as pot and pig. P can also come at the end of a word, such as hop and nap."],
 gesture="To make the /p/ sound as in 'pig', put your lips together and pop them open with a puff of air... (model). Your voice is off. /p/ is a quick, stop sound. Watch me /p/. You try /p/.",
 soundwall="Add 'p' under /p/ (lips together).", formation="Practise letter formation for uppercase P and lowercase p.",
 spell=dict(ido=["map"], wedo=["tap","pat","sap"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="pat → mat → map → tap → sap → sat → pat"),
 text_spell=["I tap.","Pat sat."],
 chains=[["Onset-Rime Level: -ap","map → tap → sap"],["Onset-Rime Level: -at","pat → mat → sat"],["Phoneme Level: Intro Lesson","pat → mat → map → tap → sap → sat → pat"]],
 hf=dict(dolch=[], fry=[]), lists={"p /p/":["pat","Pat","Pam","pam","map","tap","sap","amp","pass"]})
P["7"] = dict(tag="The grapheme F spells /f/",
 pa=dict(blend=["/f/ /ă/ /t/ (fat)","/f/ /ă/ /s/ /t/ (fast)","/f/ /ĭ/ /t/ (fit)","/f/ /ŭ/ /n/ (fun)"], segment=["fat (/f/ /ă/ /t/)","fun (/f/ /ŭ/ /n/)","fit (/f/ /ĭ/ /t/)","if (/ĭ/ /f/)"]),
 bd=dict(chain="fat → mat → sat → pat → tat → fat → fast", grid=dict(initial=["f","m","s","t","p"], medial=["a"], final=["t","m","s","p"])),
 intro=["Today we are learning about the letter F. F is a consonant. The letter F spells the /f/ sound like at the beginning of fish.",
        "F can come at the beginning of a word, such as fun and fit. Later we will learn that /f/ at the end of a word is usually spelled ff (off)."],
 gesture="To make the /f/ sound as in 'fish', put your top teeth on your bottom lip and blow air out... (model). Your voice is off because this is a quiet sound. /f/ is a continuous sound that can be stretched out. Watch me /fff/. You try /fff/.",
 soundwall="Add 'f' under /f/ (teeth on lip).", formation="Practise letter formation for uppercase F and lowercase f.",
 spell=dict(ido=["fat"], wedo=["mat","at","sat"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="fat → mat → sat → pat → tap → map → sap"),
 text_spell=["I am fat.","Pat sat at a mat."],
 chains=[["Onset-Rime Level: -at","fat → mat → sat → pat"],["Phoneme Level: Intro Lesson","fat → mat → sat → pat → tap → map → sap"]],
 hf=dict(dolch=["a"], fry=["a"]), lists={"f /f/":["fat","fast","mast","past","tam","fast"]})
P["8"] = dict(tag="The grapheme I spells /ĭ/",
 pa=dict(blend=["/ĭ/ /t/ (it)","/s/ /ĭ/ /t/ (sit)","/f/ /ĭ/ /t/ (fit)","/p/ /ĭ/ /t/ (pit)"], segment=["it (/ĭ/ /t/)","sip (/s/ /ĭ/ /p/)","tip (/t/ /ĭ/ /p/)","Tim (/t/ /ĭ/ /m/)"]),
 bd=dict(chain="sat → sit → fit → pit → pat → mat → map → sap → sip → tip", grid=dict(initial=["f","p","t","s","m"], medial=["a","i"], final=["t","p","m","s"])),
 intro=["Today we are learning about the letter I. I is a vowel. The letter I spells the /ĭ/ sound like at the beginning of itch.",
        "I can come at the beginning of a word, such as in and if. I can also come in the middle of a word, such as fit and dip."],
 gesture="To make the /ĭ/ sound as in 'itch', open your mouth just a little and smile slightly... (model). Be sure your voice is on. /ĭ/ is a continuous sound that can be stretched out. Watch me /ĭĭĭ/. You try /ĭĭĭ/.",
 soundwall="Add 'i' under /ĭ/ on the vowel valley.", formation="Practise letter formation for uppercase I and lowercase i.",
 spell=dict(ido=["sit"], wedo=["it","fit","tip"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="sit → fit → pit → pat → sat → sit → sip → tip"),
 text_spell=["I sit.","Tim sat.","Pat is fit."],
 chains=[["Onset-Rime Level: -it","it → sit → fit → pit"],["Onset-Rime Level: -ip","sip → tip → pip"],["Phoneme Level: Intro Lesson","sit → fit → pit → pat → sat → sit → sip → tip"]],
 hf=dict(dolch=["it","if"], fry=["it","if"]), lists={"i /ĭ/":["it","if","is","sit","sip","fit","tip","pit","Tim","Pim","spit","fist"]})
P["9"] = dict(tag="The grapheme N spells /n/",
 pa=dict(blend=["/n/ /ă/ /p/ (nap)","/p/ /ĭ/ /n/ (pin)","/f/ /ĭ/ /n/ (fin)","/t/ /ĭ/ /n/ (tin)"], segment=["nap (/n/ /ă/ /p/)","in (/ĭ/ /n/)","pin (/p/ /ĭ/ /n/)","nip (/n/ /ĭ/ /p/)"]),
 bd=dict(chain="nap → tap → tip → tin → fin → pin → pan → man → mat", grid=dict(initial=["n","f","p","t","s","m"], medial=["a","i"], final=["n","t","p","m","s"])),
 intro=["Today we are learning about the letter N. N is a consonant. The letter N spells the /n/ sound like at the beginning of nose.",
        "N can come at the beginning of a word, such as nut and nod. N can also come at the end of a word, such as in and pin."],
 gesture="To make the /n/ sound as in 'nose', put the tip of your tongue behind your top teeth and let the air come out of your nose... (model). Be sure your voice is on. /n/ is a continuous sound. Watch me /nnn/. You try /nnn/.",
 soundwall="Add 'n' under /n/ (tongue behind top teeth).", formation="Practise letter formation for uppercase N and lowercase n.",
 spell=dict(ido=["nap"], wedo=["pin","in","tin"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="nap → tap → tip → tin → fin → pin → pit → pat → pan"),
 text_spell=["I nap.","Tim is in.","The pin is in the tin."],
 chains=[["Onset-Rime Level: -in","in → pin → fin → tin"],["Phoneme Level: Intro Lesson","nap → tap → tip → tin → fin → pin → pit → pat → pan"]],
 hf=dict(dolch=["in","an"], fry=["in"]), lists={"n /n/":["nap","nip","nit","in","pin","fin","tin","tan","pan","man","nan"]})
P["10"] = dict(tag="Reading and spelling CVC words with a and i",
 notes=["This is a practice lesson. There is no new grapheme. Provide lots of practice reading and spelling CVC words with a and i."],
 pa=dict(blend=["/t/ /ĭ/ /p/ (tip)","/n/ /ă/ /p/ (nap)","/f/ /ĭ/ /t/ (fit)","/p/ /ă/ /t/ (pat)"], segment=["sit (/s/ /ĭ/ /t/)","tin (/t/ /ĭ/ /n/)","sat (/s/ /ă/ /t/)","fan (/f/ /ă/ /n/)"]),
 bd=dict(chain="pit → pat → mat → man → tan → tin → fin → fit → sit → sip → tip → tap", grid=dict(initial=["p","m","t","f","s","n"], medial=["a","i"], final=["t","n","p","m","s"])),
 intro=["We have learned the letters a, i, f, m, n, p, s, t. Today we will practise reading and spelling words with the short vowels /ă/ and /ĭ/. Remember: say each sound, then blend the sounds together."],
 gesture="Review the articulatory gestures for /ă/ and /ĭ/. Have students feel the difference in mouth opening between /ă/ (wide) and /ĭ/ (small smile).", soundwall="No new grapheme today.", formation=None,
 spell=dict(ido=["tin"], wedo=["nap","sit","pat","fit"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="pit → pat → sat → sit → fit → fin → fan → man → mat"),
 text_spell=["I sit in it.","Tim and Nat nap.","Pat sat in the pit."],
 chains=[["Onset-Rime Level: -an","fan → man → pan → tan"],["Onset-Rime Level: -ip","sip → tip → nip → pip"],["Phoneme Level: Mixed Review","pit → pat → sat → sit → fit → fin → fan → man → mat"]],
 hf=dict(dolch=[], fry=[]), lists={"CVC a, i":["tip","nap","fit","sit","pat","sat","if","tin","in","tap","pin","fin","man","fan","pan"]})
P["11"] = dict(tag="Nasalized A: -am and -an",
 notes=["When /ă/ is followed by /m/ or /n/, the vowel sound changes a little - it becomes nasal. Students may hear it as a different vowel. Teach am and an as chunks."],
 pa=dict(blend=["/ă/ /m/ (am)","/s/ /ă/ /m/ (Sam)","/ă/ /n/ (an)","/f/ /ă/ /n/ (fan)"], segment=["am (/ă/ /m/)","Pam (/p/ /ă/ /m/)","an (/ă/ /n/)","man (/m/ /ă/ /n/)"]),
 bd=dict(chain="am → Sam → Pam → pan → man → fan → tan → tin → tip → tap → nap", grid=dict(initial=["s","p","m","f","t","n"], medial=["a","i"], final=["m","n","p","t"])),
 intro=["We know that A spells /ă/. When A comes right before M or N, the /ă/ sound changes a little. Listen: am, an. The air goes through the nose, so we call it nasalized A.",
        "Today we will read and spell words that end with -am, such as Sam and Pam, and words that end with -an, such as fan and tan."],
 gesture="Say /ă/ then /m/: /ăm/. Feel the air move through your nose at the end. Now /ă/ then /n/: /ăn/.", soundwall="Add 'am' and 'an' cards beside /ă/ as needed.", formation=None,
 spell=dict(ido=["am"], wedo=["Sam","an","fan","man"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="am → Sam → Pam → pan → man → fan → tan → an"),
 text_spell=["I am Pam.","Sam is a man.","Tam and Nan nap."],
 chains=[["Onset-Rime Level: -am","am → Sam → Pam → tam"],["Onset-Rime Level: -an","an → fan → man → pan → tan → nan"],["Phoneme Level: Intro Lesson","am → Sam → Pam → pan → man → fan → tan → an"]],
 hf=dict(dolch=["am","an","as"], fry=["an","as"]), lists={"-am":["am","Sam","Pam","tam","Tam"],"-an":["an","fan","man","pan","tan","nan","Nan"]})
P["12"] = dict(tag="The grapheme O spells /ŏ/",
 pa=dict(blend=["/ŏ/ /n/ (on)","/m/ /ŏ/ /p/ (mop)","/t/ /ŏ/ /p/ (top)","/n/ /ŏ/ /t/ (not)"], segment=["on (/ŏ/ /n/)","pop (/p/ /ŏ/ /p/)","top (/t/ /ŏ/ /p/)","tot (/t/ /ŏ/ /t/)"]),
 bd=dict(chain="mop → top → tip → tap → nap → nip → not → pot → pat → pan → pin", grid=dict(initial=["m","t","n","p","s","f"], medial=["a","i","o"], final=["p","t","n","m"])),
 intro=["Today we are learning about the letter O. O is a vowel. The letter O spells the /ŏ/ sound like at the beginning of octopus.",
        "O can come at the beginning of a word, such as on. O can also come in the middle of a word, such as top and mop."],
 gesture="To make the /ŏ/ sound as in 'octopus', open your mouth wide and round like an O... (model). Be sure your voice is on. /ŏ/ is a continuous sound that can be stretched out. Watch me /ŏŏŏ/. You try /ŏŏŏ/.",
 soundwall="Add 'o' under /ŏ/ on the vowel valley.", formation="Practise letter formation for uppercase O and lowercase o.",
 spell=dict(ido=["mop"], wedo=["on","top","not"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="on → in → tin → tan → tap → top → mop → pop → pot → not"),
 text_spell=["Tom is on top.","The mop is not in.","Pop sat on the mat."],
 chains=[["Onset-Rime Level: -op","mop → top → pop → sop"],["Onset-Rime Level: -ot","not → pot → tot"],["Phoneme Level: Intro Lesson","on → in → tin → tan → tap → top → mop → pop → pot → not"]],
 hf=dict(dolch=["on","not"], fry=["on","not"]), lists={"o /ŏ/":["on","mop","top","pop","pot","not","tot","Tom","sop","nop"]})
P["13"] = dict(tag="The grapheme D spells /d/",
 pa=dict(blend=["/d/ /ă/ /d/ (dad)","/d/ /ĭ/ /p/ (dip)","/m/ /ă/ /d/ (mad)","/d/ /ŏ/ /t/ (dot)"], segment=["dad (/d/ /ă/ /d/)","did (/d/ /ĭ/ /d/)","sad (/s/ /ă/ /d/)","pad (/p/ /ă/ /d/)"]),
 bd=dict(chain="dad → mad → sad → sat → sit → sip → dip → did → dim → dot → pot → pod", grid=dict(initial=["d","m","s","p","t","n","f"], medial=["a","i","o"], final=["d","t","p","m","n"])),
 intro=["Today we are learning about the letter D. D is a consonant. The letter D spells the /d/ sound like at the beginning of dog.",
        "D can come at the beginning of a word, such as dip and dad. D can also come at the end of a word, such as mad and pad."],
 gesture="To make the /d/ sound as in 'dog', put the tip of your tongue behind your top teeth and pop the air out with your voice on... (model). It is like /t/ but with the voice on. /d/ is a quick, stop sound. Watch me /d/. You try /d/.",
 soundwall="Add 'd' under /d/ (tongue behind top teeth).", formation="Practise letter formation for uppercase D and lowercase d.",
 spell=dict(ido=["dad"], wedo=["sad","dip","dot"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="dad → sad → mad → pad → pod → nod → not → dot → dip → did"),
 text_spell=["Dad did it.","The dot is on the pad.","Sid and Dan sat."],
 chains=[["Onset-Rime Level: -ad","dad → sad → mad → pad → tad"],["Onset-Rime Level: -ot","dot → not → pot → tot"],["Phoneme Level: Intro Lesson","dad → sad → mad → pad → pod → nod → not → dot → dip → did"]],
 hf=dict(dolch=["and","did"], fry=["and","did"]), lists={"d /d/":["dad","ad","sad","mad","pad","tad","dip","dim","did","dot","and","dad","nod","pod","Sid","Dan"]})
P["14"] = dict(tag="The grapheme C spells /k/",
 notes=["C spells /k/ before a, o and u (cat, cot, cup). The letter K is introduced in Lesson 22 for /k/ before i and e."],
 pa=dict(blend=["/k/ /ă/ /t/ (cat)","/k/ /ă/ /n/ (can)","/k/ /ŏ/ /t/ (cot)","/k/ /ă/ /p/ (cap)"], segment=["cat (/k/ /ă/ /t/)","cap (/k/ /ă/ /p/)","cod (/k/ /ŏ/ /d/)","can (/k/ /ă/ /n/)"]),
 bd=dict(chain="cat → mat → man → can → cap → cop → cot → cod → nod → not", grid=dict(initial=["c","m","d","s","p","t","n"], medial=["a","i","o"], final=["t","n","p","d","m"])),
 intro=["Today we are learning about the letter C. C is a consonant. The letter C spells the /k/ sound like at the beginning of cat.",
        "C comes at the beginning of a word before a, o or u, such as can and cat. C does not usually spell /k/ at the end of a word - we will learn other spellings later."],
 gesture="To make the /k/ sound as in 'kite', pull the back of your tongue up to the back of the roof of your mouth and pop the air out... (model). Your voice is off. /k/ is a quick, stop sound. Watch me /k/. You try /k/.",
 soundwall="Add 'c' under /k/ (tongue pulled back).", formation="Practise letter formation for uppercase C and lowercase c.",
 spell=dict(ido=["cat"], wedo=["can","cot","cap"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="cat → cot → cop → cap → can → cad → cod → con"),
 text_spell=["The cat can sit.","Dad can not nap.","Can the cat fit in the cot?"],
 chains=[["Onset-Rime Level: -an","can → man → pan → fan → tan"],["Onset-Rime Level: -ot","cot → not → dot → pot"],["Phoneme Level: Intro Lesson","cat → cot → cop → cap → can → cad → cod → con"]],
 hf=dict(dolch=["can"], fry=["can"]), lists={"c /k/":["cat","cap","can","cot","cod","con","cop","cam","Cam"]})
P["15"] = dict(tag="The grapheme U spells /ŭ/",
 pa=dict(blend=["/ŭ/ /p/ (up)","/s/ /ŭ/ /n/ (sun)","/k/ /ŭ/ /p/ (cup)","/m/ /ŭ/ /d/ (mud)"], segment=["us (/ŭ/ /s/)","nut (/n/ /ŭ/ /t/)","cut (/k/ /ŭ/ /t/)","pup (/p/ /ŭ/ /p/)"]),
 bd=dict(chain="sun → fun → fan → fin → pin → pun → pup → cup → cut → nut → not → nod → mud", grid=dict(initial=["s","f","p","c","n","m","d","t"], medial=["a","i","o","u"], final=["n","p","t","d","m","s"])),
 intro=["Today we are learning about the letter U. U is a vowel. The letter U spells the /ŭ/ sound like at the beginning of up.",
        "U can come at the beginning of a word, such as up and us. U can also come in the middle of a word, such as nut and fun."],
 gesture="To make the /ŭ/ sound as in 'up', open your mouth a little and relax your tongue and lips... (model). Be sure your voice is on. /ŭ/ is a continuous sound. Watch me /ŭŭŭ/. You try /ŭŭŭ/.",
 soundwall="Add 'u' under /ŭ/ on the vowel valley.", formation="Practise letter formation for uppercase U and lowercase u.",
 spell=dict(ido=["sun"], wedo=["up","cup","mud"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="up → cup → cut → nut → not → nod → mud → mad → mat → mut → nut"),
 text_spell=["The pup is in the mud.","I can cut it.","Mum and Dad do not nap."],
 chains=[["Onset-Rime Level: -up","up → cup → pup → sup"],["Onset-Rime Level: -ut","cut → nut → mut → tut"],["Phoneme Level: Intro Lesson","up → cup → cut → nut → not → nod → mud → mad → mat → mut → nut"]],
 hf=dict(dolch=["up","us","to","do"], fry=["up","to","do"]), lists={"u /ŭ/":["up","us","sun","fun","nut","cut","cup","mud","mum","pup","sum","tut","Mum"]})
P["16"] = dict(tag="The grapheme G spells /g/",
 pa=dict(blend=["/g/ /ŏ/ /t/ (got)","/d/ /ŏ/ /g/ (dog)","/p/ /ĭ/ /g/ (pig)","/g/ /ŭ/ /m/ (gum)"], segment=["gas (/g/ /ă/ /s/)","tag (/t/ /ă/ /g/)","dig (/d/ /ĭ/ /g/)","gut (/g/ /ŭ/ /t/)"]),
 bd=dict(chain="got → dot → dog → dig → pig → pit → pat → pan → pun → gun → gum → gut", grid=dict(initial=["g","d","p","t","c","m","s","n","f"], medial=["a","i","o","u"], final=["g","t","n","m","d","p"])),
 intro=["Today we are learning about the letter G. G is a consonant. The letter G spells the /g/ sound like at the beginning of goat.",
        "G can come at the beginning of a word, such as got and gas. G can also come at the end of a word, such as dog and tag."],
 gesture="To make the /g/ sound as in 'goat', pull the back of your tongue up to the back of the roof of your mouth and pop the air out with your voice on... (model). It is like /k/ with the voice on. /g/ is a quick, stop sound. Watch me /g/. You try /g/.",
 soundwall="Add 'g' under /g/ (tongue pulled back).", formation="Practise letter formation for uppercase G and lowercase g.",
 spell=dict(ido=["dog"], wedo=["gum","pig","got"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="got → dot → dog → dig → pig → gig → gag → gap → gas → gum"),
 text_spell=["The dog dug in the mud.","Gus got a mug.","Do not tag the pig."],
 chains=[["Onset-Rime Level: -ig","pig → dig → fig → gig"],["Onset-Rime Level: -ag","tag → gag → nag → sag"],["Phoneme Level: Intro Lesson","got → dot → dog → dig → pig → gig → gag → gap → gas → gum"]],
 hf=dict(dolch=["got"], fry=["got"]), lists={"g /g/":["got","gas","gap","gum","gut","gag","dog","tag","pig","dig","fig","fog","tug","mug","dug","Gus"]})
P["17"] = dict(tag="The grapheme B spells /b/",
 notes=["B and D are visually similar and often confused. Point out the differences in formation (b: line then bump; d: circle then line)."],
 pa=dict(blend=["/b/ /ă/ /t/ (bat)","/b/ /ĭ/ /g/ (big)","/t/ /ŭ/ /b/ (tub)","/k/ /ă/ /b/ (cab)"], segment=["bag (/b/ /ă/ /g/)","bus (/b/ /ŭ/ /s/)","sob (/s/ /ŏ/ /b/)","cub (/k/ /ŭ/ /b/)"]),
 bd=dict(chain="bat → bit → big → bug → bus → bud → bad → bag → bog → cob → cub → tub", grid=dict(initial=["b","c","t","d","g","m","s","p","n"], medial=["a","i","o","u"], final=["b","t","g","s","d","n"])),
 intro=["Today we are learning about the letter B. B is a consonant. The letter B spells the /b/ sound like at the beginning of bee.",
        "B can come at the beginning of a word, such as bat and big. B can also come at the end of a word, such as cab and tub."],
 gesture="To make the /b/ sound as in 'bee', put your lips together and pop them open with your voice on... (model). It is like /p/ but with the voice on. /b/ is a quick, stop sound. Watch me /b/. You try /b/.",
 soundwall="Add 'b' under /b/ (lips together).", formation="Practise letter formation for uppercase B and lowercase b. Contrast b and d.",
 spell=dict(ido=["bat"], wedo=["big","tub","bus"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="bat → bit → big → bug → bud → bad → bag → big → dig → dog → bog"),
 text_spell=["The bug is big.","Bob got a bat.","The cub is in the tub."],
 chains=[["Onset-Rime Level: -ug","bug → tug → dug → mug"],["Onset-Rime Level: -ub","cub → tub → sub → dub"],["Phoneme Level: Intro Lesson","bat → bit → big → bug → bud → bad → bag → big → dig → dog → bog"]],
 hf=dict(dolch=["but","big","of"], fry=["but","of"]), lists={"b /b/":["bat","bad","bag","big","bit","bin","bud","bug","bus","but","bob","cab","tub","cub","sob","mob","fib","Bob","bib"]})
P["18"] = dict(tag="The grapheme E spells /ĕ/",
 notes=["/ĕ/ and /ĭ/ sound similar. Use the mouth pictures: /ĕ/ has the mouth a little more open than /ĭ/."],
 pa=dict(blend=["/ĕ/ /d/ (Ed)","/t/ /ĕ/ /n/ (ten)","/g/ /ĕ/ /t/ (get)","/b/ /ĕ/ /d/ (bed)"], segment=["men (/m/ /ĕ/ /n/)","pet (/p/ /ĕ/ /t/)","beg (/b/ /ĕ/ /g/)","set (/s/ /ĕ/ /t/)"]),
 bd=dict(chain="pet → pat → pit → pot → put → pup → pep → pen → ten → tin → tan → men → met → set → sat", grid=dict(initial=["p","t","m","s","b","g","d","n","f"], medial=["a","e","i","o","u"], final=["t","n","g","d","p","s"])),
 intro=["Today we are learning about the letter E. E is a vowel. The letter E spells the /ĕ/ sound like at the beginning of edge.",
        "E can come at the beginning of a word, such as end and Ed. E can also come in the middle of a word, such as men and get."],
 gesture="To make the /ĕ/ sound as in 'edge', open your mouth a little wider than for /ĭ/ and keep your tongue relaxed... (model). Be sure your voice is on. /ĕ/ is a continuous sound. Watch me /ĕĕĕ/. You try /ĕĕĕ/.",
 soundwall="Add 'e' under /ĕ/ on the vowel valley.", formation="Practise letter formation for uppercase E and lowercase e.",
 spell=dict(ido=["ten"], wedo=["bed","get","pet"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="pet → pen → ten → tin → tan → men → met → set → sat → sit → bit → bet → bed"),
 text_spell=["Ted fed the pet.","Get the pen and the pad.","Ten men met at the den."],
 chains=[["Onset-Rime Level: -et","pet → set → get → met → net"],["Onset-Rime Level: -en","ten → pen → men → den"],["Phoneme Level: Intro Lesson","pet → pen → ten → tin → tan → men → met → set → sat → sit → bit → bet → bed"]],
 hf=dict(dolch=["get","ten"], fry=["get"]), lists={"e /ĕ/":["men","set","fed","ten","get","bed","pet","beg","pen","bet","net","den","Ed","end","Ted","Ben","peg"]})
P["19"] = dict(tag="Reading and spelling VC and CVC words with all five short vowels",
 notes=["This is a practice lesson for all short vowels. Use the vowel valley to compare the mouth positions of /ă/ /ĕ/ /ĭ/ /ŏ/ /ŭ/."],
 pa=dict(blend=["/m/ /ŭ/ /g/ (mug)","/b/ /ă/ /t/ (bat)","/s/ /ĕ/ /t/ (set)","/n/ /ŏ/ /t/ (not)"], segment=["bag (/b/ /ă/ /g/)","tip (/t/ /ĭ/ /p/)","dog (/d/ /ŏ/ /g/)","mud (/m/ /ŭ/ /d/)"]),
 bd=dict(chain="bat → bet → bit → but → bug → beg → big → bag → bog → dog → dig → dug → mug → mud", grid=dict(initial=["b","d","m","s","t","p","n","g","c","f"], medial=["a","e","i","o","u"], final=["t","g","d","n","p","m","s"])),
 intro=["We have learned all five short vowels: a /ă/, e /ĕ/, i /ĭ/, o /ŏ/, u /ŭ/. Every word has a vowel sound. Today we practise reading and spelling words with all of them.",
        "When you read, look at the vowel first and think about its sound; then say each sound and blend."],
 gesture="Review all five short vowel gestures using the vowel valley (mouth opens wider from /ĭ/ to /ĕ/ to /ă/; /ŏ/ round and open; /ŭ/ relaxed).", soundwall="No new grapheme today.", formation=None,
 spell=dict(ido=["bag"], wedo=["set","dog","mud","tip"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="bat → bet → bit → bin → ban → bun → bug → bag → beg → big → bog"),
 text_spell=["The bug is on the bed.","Ben can see the big dog.","Tim did not get the mug."],
 chains=[["Phoneme Level: Vowel Changes","bat → bet → bit → bot → but"],["Phoneme Level: Mixed Review","bat → bet → bit → bin → ban → bun → bug → bag → beg → big → bog"]],
 hf=dict(dolch=["see"], fry=["see"]), lists={"Mixed short vowels":["mug","bat","not","bag","us","and","tip","big","set","dog","mud","can","get","did","cut","pen","fog","sun"]})
P["20"] = dict(tag="The suffix -s spells /s/",
 notes=["-s is the first suffix (morpheme) students learn. Today the words end with quiet sounds (t, p, k), so -s says /s/. Lesson 21 covers -s /z/.",
        "Explain the meaning: adding -s to a noun means more than one (cat → cats); adding -s to a verb tells what one person or thing does (sit → sits)."],
 pa=dict(blend=["/k/ /ă/ /t/ /s/ (cats)","/m/ /ă/ /p/ /s/ (maps)","/t/ /ŏ/ /p/ /s/ (tops)","/n/ /ŭ/ /t/ /s/ (nuts)"], segment=["mats (/m/ /ă/ /t/ /s/)","pets (/p/ /ĕ/ /t/ /s/)","sits (/s/ /ĭ/ /t/ /s/)","cups (/k/ /ŭ/ /p/ /s/)"]),
 bd=dict(chain="cat → cats → mats → maps → naps → nets → nuts → cuts → cups → pups → pets → pots", grid=dict(initial=["c","m","n","p","s","t","b","d","g"], medial=["a","e","i","o","u"], final=["t","p","ts","ps","s"])),
 intro=["Today we will learn about the suffix -s. A suffix is a word part added to the end of a word. Adding -s changes what the word means.",
        "When we add -s to a naming word (a noun) it means more than one: one cat, two cats. When we add -s to an action word (a verb) it tells what one person does: I sit, he sits.",
        "After the quiet sounds /t/, /p/ and /k/, the suffix -s says /s/: cats, maps."],
 gesture="Review the /s/ gesture (teeth together, quiet air).", soundwall="Add '-s' under /s/.", formation=None,
 spell=dict(ido=["cats"], wedo=["maps","pets","nuts"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="cat → cats → mats → maps → naps → nets → pets → pots → tops → tips → sips"),
 text_spell=["The cats sit on the mats.","Dad pats the pups.","Tim gets the nuts and the cups."],
 chains=[["Morpheme Level: add -s","cat → cats, map → maps, net → nets, cup → cups"],["Phoneme Level: Intro Lesson","cat → cats → mats → maps → naps → nets → pets → pots → tops → tips → sips"]],
 hf=dict(dolch=["gets","sits"], fry=["its"]), lists={"-s /s/":["cats","maps","mats","nets","nuts","pats","gets","tops","sits","pots","cups","bats","sets","tips","pets","naps"]})
