# Lesson plan data, lessons 84-106
P = {}
INIT = ["b","c","d","f","g","h","j","k","l","m","n","p","r","s","t","v","w","y","z","bl","cl","fl","pl","sl","br","cr","dr","fr","gr","pr","tr","sc","sk","sn","sp","st","sw","sh","ch","th","wh"]
def g(medial, final, init=None): return dict(initial=init or INIT, medial=medial, final=final)
P["84"] = dict(tag="The vowel teams AI and AY spell /ā/",
 notes=["A vowel team is two or more letters that work together to spell one vowel sound. AI spells /ā/ at the beginning or in the middle of a word (aim, rain). AY spells /ā/ at the end of a word or syllable (day, playing).",
        "We now have four spellings of /ā/: a (open syllable), a_e, ai, ay."],
 pa=dict(blend=["/r/ /ā/ /n/ (rain)","/s/ /ā/ (say)","/w/ /ā/ /t/ (wait)","/p/ /l/ /ā/ (play)"], segment=["main (/m/ /ā/ /n/)","paint (/p/ /ā/ /n/ /t/)","stay (/s/ /t/ /ā/)","chain (/ch/ /ā/ /n/)"]),
 bd=dict(chain="rain → main → pain → paint → saint → sail → mail → tail → trail → train → brain → drain → day → play → clay → stay → tray", grid=g(["ai","ay","a"], ["n","nt","l","d","t","m",""], ["r","m","p","s","t","tr","br","dr","d","pl","cl","st","gr","ch","w"])),
 intro=["A vowel team is two or more letters that work together to make one sound. We have already learned some ways to spell /ā/: a in an open syllable (baby) and a_e (cake). Today we will learn two vowel teams that spell /ā/.",
        "AI spells /ā/ like in rain. AI comes at the beginning or in the middle of a word: aim, wait, paint. AY also spells /ā/ like in day. AY comes at the end of a word: say, play, stay.",
        "When you hear /ā/ at the end of a word, use AY. In the middle, use AI or a_e."],
 gesture="Review the /ā/ gesture.", soundwall="Add 'ai' and 'ay' under /ā/ on the vowel valley.", formation=None,
 spell=dict(ido=["rain"], wedo=["wait","say","play","paint"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="rain → main → pain → paint → saint → sail → mail → tail → trail → train → brain → drain"),
 text_spell=["Their friend will stay here today.","We will wait at the main gate today.","Can you water the plants if it does not rain?"],
 chains=[["Onset-Rime Level: -ain","rain → main → pain → gain → train → brain → drain → chain → plain"],["Onset-Rime Level: -ay","day → play → clay → stay → tray → way → may → say → pray → spray"],["Phoneme Level: ai or ay?","pay → paid → laid → lay → say → sail → tail → tray → stray → stain"]],
 hf=dict(dolch=["say","play","away","today","may"], fry=["say","play","away","may"]), lists={"ai /ā/":["rain","wait","main","paint","plain","train","brain","chain","tail","mail","sail","nail","rail","aim","afraid","raise","explain"],"ay /ā/":["say","away","way","may","stay","play","day","pay","tray","clay","spray","today","Sunday","playing","crayon","always*"]})
P["85"] = dict(tag="The vowel teams EE, EA and EY spell /ē/",
 notes=["EE and EA spell /ē/ at the beginning, middle or end of a word (eel, feet, see; eat, team, sea). EY spells /ē/ at the end of a word, often in two-syllable words (key, monkey, turkey).",
        "EA also spells /ĕ/ (head) and /ā/ (great) - Lessons 94 and 114."],
 pa=dict(blend=["/k/ /ē/ /p/ (keep)","/h/ /ē/ /t/ (heat)","/n/ /ē/ /d/ (need)","/ē/ /ch/ (each)"], segment=["seem (/s/ /ē/ /m/)","sleep (/s/ /l/ /ē/ /p/)","clean (/k/ /l/ /ē/ /n/)","leave (/l/ /ē/ /v/)"]),
 bd=dict(chain="see → seed → feed → feet → meet → meat → beat → bead → read → lead → leaf → leap → keep → deep → sleep → sweep → sweet", grid=g(["ee","ea","e"], ["d","t","p","f","m","n","ch","l",""], ["s","f","m","b","r","l","k","d","sl","sw","gr","tr","ch","t","h","n","st","cl","sp"])),
 intro=["We know that /ē/ can be spelled e in an open syllable (be, began) and e_e (these). Today we will learn three vowel teams that spell /ē/.",
        "EE spells /ē/ like in feet and see. EA spells /ē/ like in eat and team. Both can come at the beginning, middle or end of a word. EY spells /ē/ at the end of a word, like key and monkey. It is often at the end of a two-syllable word: mon-key, tur-key.",
        "When you spell /ē/ in the middle of a word, it could be ee or ea - you have to remember which."],
 gesture="Review the /ē/ gesture.", soundwall="Add 'ee', 'ea' and 'ey' under /ē/ on the vowel valley.", formation=None,
 spell=dict(ido=["keep"], wedo=["heat","need","eat","monkey"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="see → seed → feed → feet → meet → meat → beat → bead → read → lead → leaf → leap → keep → deep → sleep → sweep → sweet"),
 text_spell=["Can I please eat kidney beans with rice?","They put the green beans above the apples.","The queen was hidden among the forty bees."],
 chains=[["Onset-Rime Level: -eed / -eat","seed → feed → need → weed → speed; eat → beat → heat → meat → neat → seat → treat → wheat"],["Onset-Rime Level: -eep / -eam","keep → deep → jeep → peep → sleep → sweep → steep; team → beam → seam → cream → dream → steam"],["Syllable Level: -ey","monkey, turkey, hockey, donkey, valley, honey, money"]],
 hf=dict(dolch=["see","three","eat","green","keep","sleep","above","among"], fry=["see","three","eat","keep"]), lists={"ee /ē/":["keep","seem","need","tree","sleep","three","feet","meet","green","seed","feed","week","deep","sweet","street","queen","cheek","wheel","teeth","sheep"],"ea /ē/":["heat","eat","sea","each","read","leave","clean","team","beach","dream","cream","leaf","meat","peach","reach","teach","steam","please","sneak","wheat"],"ey /ē/":["monkey","turkey","hockey","key","donkey","valley","honey","money","kidney","chimney","jersey","journey"]})
P["86"] = dict(tag="The vowel teams OA, OW and OE spell /ō/",
 notes=["OA spells /ō/ at the beginning or middle of a word (oat, boat). OW spells /ō/ at the end of a word or syllable (show, grow, yellow) - OW also spells /ow/ (cow), Lesson 96. OE spells /ō/ at the end of a few words (toe, doe, goes)."],
 pa=dict(blend=["/r/ /ō/ /d/ (road)","/g/ /r/ /ō/ (grow)","/t/ /ō/ (toe)","/b/ /ō/ /t/ (boat)"], segment=["coast (/k/ /ō/ /s/ /t/)","coach (/k/ /ō/ /ch/)","show (/sh/ /ō/)","own (/ō/ /n/)"]),
 bd=dict(chain="boat → coat → goat → goal → foal → foam → roam → road → toad → load → loaf → low → slow → glow → grow → show → snow → blow", grid=g(["oa","ow","oe","o"], ["t","l","m","d","f","st","ch","n",""], ["b","c","g","f","r","t","l","sl","gl","gr","sh","sn","bl","fl","thr","cr","m","s"])),
 intro=["We know that /ō/ can be spelled o in an open syllable (go, cozy) and o_e (bone). Today we will learn three vowel teams that spell /ō/.",
        "OA spells /ō/ like in boat and road. OA comes at the beginning or in the middle of a word. OW spells /ō/ like in show and grow. OW comes at the end of a word or syllable, such as low, grown, yellow. OE spells /ō/ at the end of a few words: toe, hoe, doe, goes.",
        "OW can also spell another sound, /ow/ as in cow. We will learn that later. If /ō/ does not make a real word, try /ow/."],
 gesture="Review the /ō/ gesture.", soundwall="Add 'oa', 'ow' and 'oe' under /ō/ on the vowel valley.", formation=None,
 spell=dict(ido=["boat"], wedo=["road","grow","show","toe"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="boat → coat → goat → goal → foal → foam → roam → road → toad → load → loaf → low → slow → glow → grow → show → snow → blow"),
 text_spell=["He will row the boat to the coast again.","Take your coat with you, it is very cold today.","The coach asks Joe to play a game against Tom."],
 chains=[["Onset-Rime Level: -oat / -oad","boat → coat → goat → float → throat; road → toad → load"],["Onset-Rime Level: -ow","low → slow → glow → grow → show → snow → blow → flow → throw → crow"],["Syllable Level: -ow in 2 syllables","yellow, window, pillow, shadow, follow, elbow, arrow, rainbow"]],
 hf=dict(dolch=["grow","show","own","yellow","again","against"], fry=["grow","show","own"]), lists={"oa /ō/":["road","boat","toad","coast","coach","oat","oak","goat","soap","loaf","float","throat","toast","roast","cloak","goal","foam","groan"],"ow /ō/":["grow","low","show","own","grown","flown","window","yellow","slow","glow","snow","blow","throw","crow","flow","bowl","pillow","follow","shadow","elbow"],"oe /ō/":["toe","foe","hoe","doe","goes","toes","woe","Joe"]})
P["87"] = dict(tag="The vowel teams IE and IGH spell /ī/",
 notes=["IE spells /ī/ at the end of a few one-syllable words (pie, tie, lie, die). IGH spells /ī/ in the middle or at the end of a word (high, night, light); the gh is silent. IE also spells /ē/ (field, chief) - flexible reading."],
 pa=dict(blend=["/t/ /ī/ (tie)","/s/ /ī/ /t/ (sight)","/h/ /ī/ (high)","/r/ /ī/ /t/ (right)"], segment=["pie (/p/ /ī/)","night (/n/ /ī/ /t/)","bright (/b/ /r/ /ī/ /t/)","flight (/f/ /l/ /ī/ /t/)"]),
 bd=dict(chain="pie → tie → lie → die → high → sigh → sight → light → might → night → right → bright → fright → flight → tight", grid=g(["ie","igh","i","y"], ["t","",""], ["p","t","l","d","h","s","m","n","r","br","fr","fl","sl","bl","th","f"])),
 intro=["We know that /ī/ can be spelled i in an open syllable (tiger), i_e (kite) and y at the end of a word (fly). Today we will learn two vowel teams that spell /ī/.",
        "IE spells /ī/ at the end of a few short words: pie, tie, lie, die. IGH spells /ī/ in the middle or at the end of a word: light, night, high. In IGH the letters g and h are silent - the three letters spell one sound.",
        "IE can sometimes spell /ē/ in the middle of a word (field, chief). Be flexible: try /ī/ first, then /ē/."],
 gesture="Review the /ī/ gesture.", soundwall="Add 'ie' and 'igh' under /ī/ on the vowel valley.", formation=None,
 spell=dict(ido=["tie"], wedo=["pie","high","night","bright"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="pie → tie → lie → die → high → sigh → sight → light → might → night → right → bright → fright → flight → tight"),
 text_spell=["Do you always fight for the last slice of pie?","We are almost done fixing the bright lights.","She tried to help because it was the right thing to do."],
 chains=[["Onset-Rime Level: -ie","pie → tie → lie → die → tied → lied → dried → cried → fried"],["Onset-Rime Level: -ight","sight → light → might → night → right → bright → fright → flight → tight → slight"],["Phoneme Level: spellings of /ī/","my → mine → might → mite → tie → tight → time"]],
 hf=dict(dolch=["light","right","high","always","almost"], fry=["light","right","high"]), lists={"ie /ī/":["tie","lie","pie","die","tied","lied","dried","cried","fried","tried","spied","untie","magpie","necktie"],"igh /ī/":["sight","high","right","night","fight","bright","flight","sunlight","light","might","tight","sigh","thigh","slight","fright","knight*","highway","tonight","midnight","delight"]})
P["88"] = dict(tag="Vowel teams review 1: ai, ay, ee, ea, ey, oa, ow, oe, ie, igh",
 pa=dict(blend=["/s/ /t/ /r/ /ā/ (stray)","/f/ /l/ /ō/ /t/ (float)","/n/ /ī/ /t/ (night)","/g/ /r/ /ē/ /t/ (greet)"], segment=["scream (/s/ /k/ /r/ /ē/ /m/)","boast (/b/ /ō/ /s/ /t/)","fright (/f/ /r/ /ī/ /t/)","day-light (daylight)"]),
 bd=dict(chain="train → rain → ray → tray → tree → free → freed → feed → seed → sea → seat → sight → light → load → road → toad → tie", grid=g(["ai","ay","ee","ea","oa","ow","ie","igh"], ["n","d","t","l","m",""], ["tr","r","t","fr","f","s","l","b","g","m","st","sh","fl","gr","cr"])),
 intro=["We have learned vowel teams for /ā/ (ai, ay), /ē/ (ee, ea, ey), /ō/ (oa, ow, oe) and /ī/ (ie, igh). Today we review all of them and read longer words that use them: rain-coat, day-light, be-tween.",
        "Look for the vowel team in each syllable. Read each syllable, then blend."],
 gesture="Review /ā/, /ē/, /ō/, /ī/.", soundwall="No new grapheme.", formation=None,
 spell=dict(ido=["stray"], wedo=["greet","float","night","scream"]),
 ww=dict(type="Word Sort", text="Read and sort the words by vowel sound: /ā/, /ē/, /ō/, /ī/. Words: stray, oatmeal, way, day, gain, greet, scream, float, boast, show, night, fright, follow, untie, between, below, daylight, railroad, highway, jersey, raincoat.", chain="train → rain → ray → tray → tree → free → freed → feed → seed → sea → seat → sight → light → load → road → toad → tie"),
 text_spell=["It is very bright on the road today.","The team groaned as they almost scored.","I always use soap when I take a bath at night."],
 chains=[["Phoneme Level: Mixed vowel teams","train → rain → ray → tray → tree → free → freed → feed → seed → sea → seat → sight → light → load → road → toad → tie"],["Syllable Level: two-syllable words","rain-coat, rail-road, high-way, day-light, oat-meal, be-tween, be-low, fol-low, un-tie, jer-sey"]],
 hf=dict(dolch=["between","below","follow"], fry=["between","below"]), lists={"review":["stray","oatmeal","way","day","gain","greet","scream","float","boast","show","night","fright","follow","untie","between","below","daylight","railroad","highway","jersey","raincoat","seaweed","peanut","teapot","sailboat"]})
P["89"] = dict(tag="OO and U spell /oo/ (as in book, put)",
 notes=["OO spells the short /oo/ sound in book, look, good, foot. The letter U spells the same sound in a few common words: put, push, pull, full, bush, bull. OO also spells /ū/ (moon) - Lesson 90."],
 pa=dict(blend=["/b/ /oo/ /k/ (book)","/p/ /oo/ /t/ (put)","/g/ /oo/ /d/ (good)","/b/ /oo/ /sh/ (bush)"], segment=["look (/l/ /oo/ /k/)","wood (/w/ /oo/ /d/)","push (/p/ /oo/ /sh/)","shook (/sh/ /oo/ /k/)"]),
 bd=dict(chain="book → look → took → cook → hook → hood → good → wood → wool → foot → soot → put → push → bush → bull → full → pull", grid=g(["oo","u"], ["k","d","l","t","sh","ll"], ["b","l","t","c","h","g","w","f","s","p","sh","br","cr","st"])),
 intro=["Today we will learn a new vowel sound, /oo/, like in book and foot. It is a short, relaxed sound. The vowel team OO spells /oo/, like in look and good.",
        "The letter U can also spell /oo/ in a few common words: put, push, pull, full, bush. U usually spells /ŭ/ (cup), so try /ŭ/ first; if it is not a real word, try /oo/."],
 gesture="To make the /oo/ sound as in 'book', round your lips a little and keep your mouth relaxed... (model). Be sure your voice is on. It is a short sound - do not stretch it. Watch me /oo/. You try /oo/.",
 soundwall="Add 'oo' and 'u' under /oo/ on the vowel valley.", formation=None,
 spell=dict(ido=["book"], wedo=["look","good","put","push"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="book → look → took → cook → hook → hood → good → wood → wool → foot → soot → put → push → bush → bull → full → pull"),
 text_spell=["He put a hook on the door.","They stood on the clean floor.","Did you cook a full meal for these people?"],
 chains=[["Onset-Rime Level: -ook","book → look → took → cook → hook → shook → brook → crook"],["Onset-Rime Level: -ood / -oot","good → hood → wood → stood; foot → soot"],["Phoneme Level: u /oo/","put → push → bush → bull → full → pull → pulled → bullet"]],
 hf=dict(dolch=["look","book","good","put","took","floor","door","poor"], fry=["look","good","put","took"]), lists={"oo /oo/":["book","cooking","took","wood","look","good","shook","textbook","football","hook","cook","foot","stood","brook","wool","hood","soot","crook","cookie","goodbye"],"u /oo/":["bush","pull","put","push","full","bull","bullet","pudding","butcher","cushion","sugar*"]})
P["90"] = dict(tag="OO spells /ū/ (as in moon)",
 notes=["OO spells two sounds: short /oo/ (book) and long /ū/ (moon, food). Try /ū/ first, then /oo/. The long /ū/ is also spelled u_e (rule), u (flu)."],
 pa=dict(blend=["/r/ /ū/ /m/ (room)","/s/ /ū/ /n/ (soon)","/f/ /ū/ /d/ (food)","/t/ /ū/ /th/ (tooth)"], segment=["cool (/k/ /ū/ /l/)","bloom (/b/ /l/ /ū/ /m/)","scoop (/s/ /k/ /ū/ /p/)","boot (/b/ /ū/ /t/)"]),
 bd=dict(chain="moon → soon → spoon → spool → pool → cool → tool → too → zoo → zoom → boom → boot → root → roof → room → broom → bloom", grid=g(["oo","u_e","oo"], ["n","l","m","t","f","p","d","th",""], ["m","s","sp","p","c","t","z","b","r","br","bl","f","sh","sm","st","sc","dr","g","n","h"])),
 intro=["Yesterday we learned that OO spells /oo/ as in book. Today we will learn that OO can also spell /ū/, like in moon and food. This is the same sound as u_e in rule and flute.",
        "OO /ū/ can come in the middle of a word (soon, food) or at the end (too, zoo). When you read a word with OO, try /ū/ first; if it does not make a real word, try /oo/."],
 gesture="Review the /ū/ gesture (lips tightly rounded, voice on, long).", soundwall="Add 'oo' under /ū/ on the vowel valley.", formation=None,
 spell=dict(ido=["moon"], wedo=["soon","food","cool","tooth"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="moon → soon → spoon → spool → pool → cool → tool → too → zoo → zoom → boom → boot → root → roof → room → broom → bloom"),
 text_spell=["Their son will scoop the food for the dog.","Did your son have a smooth bus ride to the zoo?","They won the game when he shot the ball in the hoop."],
 chains=[["Onset-Rime Level: -oon / -oom","moon → soon → noon → spoon → balloon; room → boom → zoom → broom → bloom → gloom"],["Onset-Rime Level: -oot / -ool","boot → root → hoot → shoot → scoot; pool → cool → tool → fool → spool → stool → school"],["Phoneme Level: /oo/ or /ū/?","book → boot → boom → look → loop → loom → food → foot → good → goose"]],
 hf=dict(dolch=["soon","too","won","son"], fry=["soon","too"]), lists={"oo /ū/":["room","bedroom","soon","food","roof","cool","tooth","bloom","too","scoop","boot","bathroom","moon","spoon","pool","tool","zoo","zoom","broom","smooth","balloon","noon","stool","goose","loose","shoot","school*"]})
P["91"] = dict(tag="The vowel teams EW, UI and UE spell /ū/",
 notes=["EW spells /ū/ at the end of a word (new, blew, flew). UI spells /ū/ in the middle of a word (fruit, suit, juice). UE spells /ū/ at the end of a word (blue, glue, true). EW and UE also spell /yū/ (few, cue) - Lesson 115."],
 pa=dict(blend=["/b/ /l/ /ū/ (blew)","/f/ /r/ /ū/ /t/ (fruit)","/b/ /l/ /ū/ (blue)","/ch/ /ū/ (chew)"], segment=["drew (/d/ /r/ /ū/)","juice (/j/ /ū/ /s/)","glue (/g/ /l/ /ū/)","cruise (/k/ /r/ /ū/ /z/)"]),
 bd=dict(chain="new → dew → drew → grew → blew → flew → chew → stew → threw → true → blue → glue → clue → cruise → bruise → fruit → suit", grid=g(["ew","ue","ui","oo"], ["","t","ce","se"], ["n","d","dr","gr","bl","fl","ch","st","thr","tr","gl","cl","cr","br","fr","s","j"])),
 intro=["We know that /ū/ can be spelled u_e (rule), u (flu) and oo (moon). Today we will learn three more vowel teams that spell /ū/.",
        "EW spells /ū/ at the end of a word: new, flew, grew. UI spells /ū/ in the middle of a word: fruit, suit, juice. UE spells /ū/ at the end of a word: blue, glue, true.",
        "That is many spellings for one sound! When spelling, think about where the sound is: at the end of the word use ew or ue; in the middle use oo, ui or u_e."],
 gesture="Review the /ū/ gesture.", soundwall="Add 'ew', 'ui' and 'ue' under /ū/ on the vowel valley.", formation=None,
 spell=dict(ido=["blew"], wedo=["fruit","blue","chew","juice"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="new → dew → drew → grew → blew → flew → chew → stew → threw → true → blue → glue → clue → cruise → bruise → fruit → suit"),
 text_spell=["Sue cut fruit for the crew.","What month will we go on the cruise?","Sue threw on her new suit to go to the pool."],
 chains=[["Onset-Rime Level: -ew","new → dew → drew → grew → blew → flew → chew → stew → threw → crew → screw"],["Onset-Rime Level: -ue","true → blue → glue → clue → due → sue"],["Phoneme Level: spellings of /ū/","blue → blew → boo → boot → suit → soot* → root → rude → rule"]],
 hf=dict(dolch=["new","blue","true","month"], fry=["new","blue"]), lists={"ew /ū/":["blew","brew","drew","chew","grew","flew","new","dew","stew","threw","crew","screw","jewel","chewing"],"ui /ū/":["cruise","fruit","juice","suitcase","suit","bruise","fruity","juicy"],"ue /ū/":["blue","blueprint","glue","true","clue","due","Sue","clueless","glued"]})
P["92"] = dict(tag="Vowel teams review 2 (including two-syllable and compound words)",
 pa=dict(blend=["sun-light (sunlight)","grape-fruit (grapefruit)","re-play (replay)","tooth-brush (toothbrush)"], segment=["maintain (main-tain)","oatmeal (oat-meal)","teaspoon (tea-spoon)","unhook (un-hook)"]),
 bd=dict(chain="play → replay → repay → repaid → paid → laid → load → reload → loaf → leaf → lean → clean → unclean → seen → unseen", grid=g(["ai","ay","ee","ea","oa","oo","ew","ue","ui"], ["","d","f","n","k","t","l"], ["pl","re","un","p","l","cl","s","m","sp","gr","fr","t","b","d","f","g","sh","th"])),
 intro=["We have learned many vowel teams. Today we will read longer words that use them: compound words (sun-light, tooth-brush) and words with prefixes or endings (re-play, un-hook, chew-y).",
        "Find the vowel team in each part. Read each part, then blend the parts together."],
 gesture="Review the long vowel gestures.", soundwall="No new grapheme.", formation=None,
 spell=dict(ido=["sunlight"], wedo=["replay","oatmeal","teaspoon","toothbrush"]),
 ww=dict(type="Syllable Decoding and Blending", text="Read each part, then blend: sun/light, grape/fruit, main/tain, re/play, oat/meal, un/hook, tea/spoon, snow/suit, tooth/brush, clue/less, chew/y, moon/light, rain/coat.", chain="play → replay → repay → repaid → paid → laid → load → reload → loaf → leaf → lean → clean → unclean → seen → unseen"),
 text_spell=["Please clean the stain on the floor.","Their son got a scoop of ice cream as a sweet treat.","Put a teaspoon of toothpaste on your new toothbrush."],
 chains=[["Syllable Level: compound words with vowel teams","sunlight, moonlight, daylight, rainbow, seaweed, teaspoon, toothbrush, snowsuit, grapefruit, railroad"]],
 hf=dict(dolch=[], fry=[]), lists={"review":["sunlight","grapefruit","maintain","replay","oatmeal","unhook","teaspoon","snowsuit","toothbrush","clueless","chewy","lunchroom","between","Sunday","rainbow","seaweed","peanut","teapot","sailboat","moonlight","football","weekend","freeway","payday"]})
P["93"] = dict(tag="The vowel teams AU, AW and AUGH spell /or/ (/aw/)",
 notes=["In Australian/NZ English, the sound in saw, haul and caught is the same as the /or/ in fork and more. The UFLI US edition calls it /aw/. AU comes in the middle of a word (haul, sauce); AW at the end of a word or before n/l (saw, lawn, crawl); AUGH before t (caught, taught)."],
 pa=dict(blend=["/d/ /r/ /or/ (draw)","/h/ /or/ /l/ (haul)","/t/ /or/ /t/ (taught)","/s/ /or/ (saw)"], segment=["law (/l/ /or/)","crawl (/k/ /r/ /or/ /l/)","launch (/l/ /or/ /n/ /ch/)","cause (/k/ /or/ /z/)"]),
 bd=dict(chain="saw → paw → jaw → law → lawn → dawn → drawn → draw → straw → claw → crawl → haul → maul → Paul → cause → pause → caught → taught", grid=g(["aw","au","augh","or","ore"], ["","n","l","se","t","ch","k"], ["s","p","j","l","d","dr","str","cl","cr","h","m","P","c","t","f","sh","y","thr"])),
 intro=["We know that OR and ORE spell /or/ (fork, more). Today we will learn three vowel teams that spell the same sound in our accent: /or/ (in American books it is written /aw/).",
        "AW spells /or/ at the end of a word (saw, draw, law) and before n or l (lawn, crawl). AU spells /or/ in the middle of a word (haul, sauce, August). AUGH spells /or/ before t (caught, taught, daughter) - the gh is silent.",
        "Listen: saw, for, haul, more - the vowel sound is the same. When spelling, think about where the sound is in the word."],
 gesture="Review the /or/ gesture (lips rounded, mouth open a little, voice on).", soundwall="Add 'au', 'aw' and 'augh' under /or/ (/aw/) on the vowel valley.", formation=None,
 spell=dict(ido=["saw"], wedo=["draw","haul","cause","taught"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="saw → paw → jaw → law → lawn → dawn → drawn → draw → straw → claw → crawl → haul → maul → Paul → cause → pause"),
 text_spell=["I always yawn at this late hour.","She taught me to draw what I saw.","I picked up more sauce at the last minute."],
 chains=[["Onset-Rime Level: -aw","saw → paw → jaw → law → raw → draw → straw → claw → thaw"],["Onset-Rime Level: -awn / -awl","lawn → dawn → yawn → drawn → prawn; crawl → shawl → sprawl"],["Onset-Rime Level: -aught / -ause","caught → taught → daughter; cause → pause → clause"]],
 hf=dict(dolch=["saw","draw","because","hour","minute"], fry=["saw","draw"]), lists={"aw /or/":["draw","seesaw","law","saw","straw","crawl","withdraw","paw","jaw","raw","claw","thaw","lawn","dawn","yawn","drawn","prawn","shawl","awful","hawk"],"au /or/":["haul","launch","cause","sauce","pause","August","autumn","fault","vault","author","laundry","applause","sausage","haunted"],"augh /or/":["taught","caught","daughter","naughty","slaughter"]})
P["94"] = dict(tag="EA spells /ĕ/ and A spells /ŏ/ (after w)",
 notes=["EA usually spells /ē/ (team) but in some common words it spells /ĕ/ (head, bread, ready). Try /ē/ first, then /ĕ/. After W (and QU), A often spells /ŏ/: wash, watch, swan, want."],
 pa=dict(blend=["/h/ /ĕ/ /d/ (head)","/w/ /ŏ/ /sh/ (wash)","/b/ /r/ /ĕ/ /d/ (bread)","/w/ /ŏ/ /ch/ (watch)"], segment=["meant (/m/ /ĕ/ /n/ /t/)","spread (/s/ /p/ /r/ /ĕ/ /d/)","swan (/s/ /w/ /ŏ/ /n/)","heavy (heav-y)"]),
 bd=dict(chain="head → read → bread → dread → thread → spread → sweat → sweater → wash → wasp → was → swat → swap → swan → swamp → watch", grid=g(["ea","a","e"], ["d","t","th","sh","sp","n","p","mp","tch"], ["h","r","br","dr","thr","spr","sw","w","d","l","m","f","st","wh"])),
 intro=["We know that EA spells /ē/ as in eat and team. Today we will learn that in some words EA spells /ĕ/, like in head and bread. When you read a word with EA, try /ē/ first. If it is not a real word, try /ĕ/.",
        "We also know that A spells /ă/ as in cat. After the letter W, A often spells /ŏ/: wash, watch, swan, swamp. Listen: w-a-sh, wash. The W changes the vowel sound."],
 gesture="Review /ĕ/ and /ŏ/.", soundwall="Add 'ea' under /ĕ/ and 'a' (after w) under /ŏ/.", formation=None,
 spell=dict(ido=["head"], wedo=["bread","wash","watch","read"]),
 ww=dict(type="Word Sort", text="Read and sort the words by vowel sound: ea /ē/ (mean, team), ea /ĕ/ (head, bread), a /ŏ/ (wash, swan). Words: head, wash, read, bread, meant, spread, heavy, feather, want, watch, mean, team, dead, thread, swan, swamp.", chain="head → read → bread → dread → thread → spread → sweat → wash → wasp → was → swat → swap → swan → swamp → watch"),
 text_spell=["Watch out for sharks in the water.","On Monday we will sweat a lot.","We will wash the car on Wednesday."],
 chains=[["Onset-Rime Level: -ead","head → read → bread → dead → dread → thread → spread → instead"],["Phoneme Level: a after w","wash → wasp → was → swat → swap → swan → swamp → watch → wand → wander"]],
 hf=dict(dolch=["read","head","want","wash","Monday","Wednesday"], fry=["read","head","want"]), lists={"ea /ĕ/":["head","read","bread","meant","spread","heavy","feather","dead","dread","thread","instead","ready","weather","breakfast","sweat","sweater","leather","health","wealth","breath"],"a /ŏ/":["wash","want","watch","swan","swamp","wasp","was","swap","swat","wand","wander","squash","quad","wallet","waffle"]})
P["95"] = dict(tag="The diphthongs OI and OY spell /oi/",
 notes=["A diphthong is a vowel sound that glides from one sound to another (/oi/ = /o/ gliding to /i/). OI spells /oi/ in the middle of a word (coin, point). OY spells /oi/ at the end of a word or syllable (toy, enjoy, royal)."],
 pa=dict(blend=["/v/ /oi/ /s/ (voice)","/t/ /oi/ (toy)","/p/ /oi/ /n/ /t/ (point)","/s/ /oi/ /l/ (soil)"], segment=["noise (/n/ /oi/ /z/)","join (/j/ /oi/ /n/)","boy (/b/ /oi/)","spoil (/s/ /p/ /oi/ /l/)"]),
 bd=dict(chain="oil → boil → coil → coin → join → joint → point → moist → hoist → foil → soil → spoil → boy → toy → joy → enjoy → ploy", grid=g(["oi","oy"], ["l","n","nt","st","ce","se",""], ["b","c","j","p","m","h","f","s","sp","t","ann","enj","r","br","destr"])),
 intro=["Today we will learn a new vowel sound, /oi/, like in oil and boy. It is a diphthong: two vowel sounds that glide together so fast we say them as one - /o/ /i/, /oi/.",
        "OI spells /oi/ in the middle of a word: coin, point, oil. OY spells /oi/ at the end of a word or syllable: boy, toy, enjoy, royal. When you hear /oi/ at the end of a word, use OY."],
 gesture="To make the /oi/ sound as in 'oil', start with your lips round for /o/ and glide to a smile for /i/... (model). Be sure your voice is on. Feel your mouth move. Watch me /oi/. You try /oi/.",
 soundwall="Add 'oi' and 'oy' under /oi/ (diphthongs).", formation=None,
 spell=dict(ido=["coin"], wedo=["boy","point","toy","soil"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="oil → boil → coil → coin → join → joint → point → moist → hoist → foil → soil → spoil → boy → toy → joy → enjoy"),
 text_spell=["I hope the fruit does not spoil.","I will join the hockey team in February.","Does Joy's plant need moist soil to live?"],
 chains=[["Onset-Rime Level: -oil / -oin","oil → boil → coil → foil → soil → spoil → toil; coin → join → loin → groin"],["Onset-Rime Level: -oy","boy → toy → joy → coy → soy → Roy → enjoy → annoy → destroy"]],
 hf=dict(dolch=["boy","toy","enjoy","February"], fry=["boy","enjoy"]), lists={"oi /oi/":["voice","point","soil","noise","join","spoil","choice","coin","oil","boil","foil","moist","joint","hoist","poison","toilet","avoid","rejoice"],"oy /oi/":["toy","boyhood","boy","toys","enjoy","joy","annoy","destroy","royal","loyal","oyster","employ","cowboy","soybean"]})
P["96"] = dict(tag="The diphthongs OU and OW spell /ow/",
 notes=["OU spells /ow/ at the beginning or middle of a word (out, loud, house). OW spells /ow/ at the end of a word (how, cow), before n, l (down, owl, town) and in a few others (crowd). OW also spells /ō/ (snow) - be flexible."],
 pa=dict(blend=["/s/ /ow/ /n/ /d/ (sound)","/h/ /ow/ (how)","/ow/ /t/ (out)","/b/ /r/ /ow/ /n/ (brown)"], segment=["house (/h/ /ow/ /s/)","round (/r/ /ow/ /n/ /d/)","now (/n/ /ow/)","crowd (/k/ /r/ /ow/ /d/)"]),
 bd=dict(chain="out → shout → scout → spout → pout → loud → cloud → count → mount → mouth → south → sound → round → ground → found → how → now → cow → down → town → brown → crown → clown → owl → growl", grid=g(["ou","ow"], ["t","d","nd","nt","th","se","","n","l"], ["sh","sc","sp","p","l","cl","c","m","s","r","gr","f","h","n","d","t","br","cr","g","fl","pl","dr"])),
 intro=["Today we will learn another diphthong, /ow/, like in owl and cow. Your mouth starts open and glides to round: /a/ /oo/, /ow/.",
        "OU spells /ow/ at the beginning or middle of a word: out, loud, house, round. OW spells /ow/ at the end of a word (how, cow, now) and before n or l (down, town, owl, growl).",
        "Remember OW can also spell /ō/ (snow, grow). Try /ō/ and /ow/ to see which makes a real word."],
 gesture="To make the /ow/ sound as in 'owl', open your mouth wide and glide to round lips... (model). Be sure your voice is on. Feel your lips move. Watch me /ow/. You try /ow/.",
 soundwall="Add 'ou' and 'ow' under /ow/ (diphthongs).", formation=None,
 spell=dict(ido=["out"], wedo=["loud","how","down","found"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="out → shout → scout → spout → pout → loud → cloud → count → mount → mouth → south → sound → round → ground → found → how → now → cow → down → town → brown → crown → clown"),
 text_spell=["He found our brown bag on the ground.","How do you draw the shape of a heart?","How many days are in the month of February?"],
 chains=[["Onset-Rime Level: -out / -ound","out → shout → scout → spout → pout → sprout; sound → round → ground → found → hound → pound"],["Onset-Rime Level: -own / -ow","down → town → brown → crown → clown → frown → gown; how → now → cow → bow → wow → vow → plow"],["Phoneme Level: ow /ō/ or /ow/?","snow → now → cow → crow → crowd → grow → growl → owl → bowl"]],
 hf=dict(dolch=["out","how","now","down","around","our","eye","heart"], fry=["out","how","now","down","around","our"]), lists={"ou /ow/":["sound","around","outside","house","round","out","without","loud","cloud","count","mouth","south","ground","found","shout","scout","proud","about","couch","pound"],"ow /ow/":["how","now","brown","crowd","downhill","down","town","cow","owl","growl","crown","clown","frown","gown","towel","flower","power","shower","tower","vowel"]})
P["97"] = dict(tag="Vowel teams and diphthongs review (two-syllable words)",
 pa=dict(blend=["toi-let (toilet)","Au-gust (August)","out-side (outside)","break-fast (breakfast)"], segment=["noisy (nois-y)","daughter (daugh-ter)","weather (weath-er)","enjoyed (en-joyed)"]),
 bd=dict(chain="coin → join → joint → point → pound → round → sound → south → mouth → moth* → mouse → house → howl → owl → oil → boil → boy", grid=g(["oi","oy","ou","ow","au","aw","ea","oo"], ["n","nt","nd","th","se","l","",""], ["c","j","p","r","s","m","h","b","fl","gr","sh","cl","t","d"])),
 intro=["We have learned the diphthongs oi, oy, ou, ow and the vowel teams au, aw, augh, ea /ĕ/ and a /ŏ/. Today we review them in one- and two-syllable words: toi-let, Au-gust, out-side, break-fast.",
        "Find the vowel team in each syllable. Read each syllable, then blend."],
 gesture="Review /oi/, /ow/, /or/.", soundwall="No new grapheme.", formation=None,
 spell=dict(ido=["toilet"], wedo=["August","outside","breakfast","noisy"]),
 ww=dict(type="Syllable Decoding and Blending", text="Read each syllable, then blend: toi/let, Au/gust, house/hold, down/hill, nois/y, daugh/ter, break/fast, read/y, weath/er, point/ed, a/round, en/joyed, out/side, pow/er, flow/er.", chain="coin → join → joint → point → pound → round → sound → south → mouth → mouse → house → howl → owl → oil → boil → boy"),
 text_spell=["I keep my bedroom nice and clean.","My drawing of the heart is almost ready!","Roy will raid the fridge for something good to eat."],
 chains=[["Phoneme Level: Mixed diphthongs","coin → join → joint → point → pound → round → sound → south → mouth → mouse → house → howl → owl → oil → boil → boy"]],
 hf=dict(dolch=[], fry=[]), lists={"review":["toilet","August","household","downhill","noisy","daughter","breakfast","ready","weather","pointed","around","enjoyed","outside","bedroom","drawing","cowboy","flower","powder","awful","autumn","poison","royal","couch","proud"]})
P["98"] = dict(tag="Silent letters: KN /n/, WR /r/, MB /m/",
 notes=["KN spells /n/ at the beginning of a word (knot, knee). WR spells /r/ at the beginning of a word (wrap, write). MB spells /m/ at the end of a word (lamb, comb, thumb). The silent letters were pronounced long ago."],
 pa=dict(blend=["/n/ /ŏ/ /t/ (knot)","/r/ /ă/ /p/ (wrap)","/th/ /ŭ/ /m/ (thumb)","/n/ /ō/ (know)"], segment=["write (/r/ /ī/ /t/)","wrench (/r/ /ĕ/ /n/ /ch/)","limb (/l/ /ĭ/ /m/)","crumb (/k/ /r/ /ŭ/ /m/)"]),
 bd=dict(chain="knot → knit → knob → knock → know → knee → kneel → knelt → wrap → wrist → write → wreck → wren → lamb → limb → numb → thumb → crumb → comb → climb", grid=g(["o","i","ee","a","e","u","ō"], ["t","b","ck","","l","st","te","ch","mb"], ["kn","wr","l","n","th","cr","c","cl","d","t","b"])),
 intro=["Today we will learn three spellings with silent letters. Long ago, people said both letters; now one letter is silent.",
        "KN spells /n/ at the beginning of a word: knot, knee, know. The K is silent. WR spells /r/ at the beginning of a word: wrap, write, wrist. The W is silent. MB spells /m/ at the end of a word: lamb, comb, thumb. The B is silent.",
        "When you read, do not say the silent letter. When you spell, remember to write it!"],
 gesture="Review /n/, /r/, /m/.", soundwall="Add 'kn' under /n/, 'wr' under /r/ and 'mb' under /m/.", formation=None,
 spell=dict(ido=["knot"], wedo=["wrap","thumb","know","write"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="knot → knit → knob → knock → know → knee → kneel → knelt → wrap → wrist → write → wreck → wren → lamb → limb → numb → thumb → crumb → comb → climb"),
 text_spell=["Grandma knits for about twenty minutes each night.","Please clean up your crumbs after you eat.","I know how to wrap gifts very well."],
 chains=[["Phoneme Level: kn-","knot → knit → knob → knock → know → knee → kneel → knelt → knife → knight"],["Phoneme Level: wr-","wrap → wrist → write → wreck → wren → wrench → wreath → wrong → wrote"],["Phoneme Level: -mb","lamb → limb → numb → thumb → crumb → comb → climb → bomb → tomb"]],
 hf=dict(dolch=["know","write","about"], fry=["know","write","about"]), lists={"kn /n/":["knot","know","knife","knock","knelt","knit","knee","kneel","knob","knight","knuckle","known"],"wr /r/":["wrap","write","wrench","wreath","wreck","wrist","wren","wrong","wrote","written","wrinkle","wrapper"],"mb /m/":["thumb","limb","crumb","comb","lamb","climb","numb","bomb","tomb","dumb","plumber","crumble"]})
P["99"] = dict(tag="The suffixes -s and -es (morphemes)",
 notes=["This lesson revisits -s and -es as morphemes: word parts that change meaning. -s/-es make nouns plural (one dog, two dogs) and change verbs (I run, he runs). Use -es after s, x, z, sh, ch."],
 pa=dict(blend=["/k/ /l/ /ar/ /s/ /əz/ (classes)","/g/ /r/ /ō/ /z/ (grows)","/p/ /ar/ /t/ /s/ (parts)","/b/ /r/ /ŭ/ /sh/ /əz/ (brushes)"], segment=["dresses (dress-es)","spends (spend-s)","shows (show-s)","matches (match-es)"]),
 bd=dict(chain="class → classes → glasses → grasses → grass → gross → grows → glows → glow → blow → blows → brushes → brush → crush → crushes", grid=g(["a","o","ow","u"], ["ss","sses","s","ws","sh","shes","tch","tches"], ["cl","gl","gr","bl","br","cr","dr","fl","p","m","w"])),
 intro=["A morpheme is a word part that changes a word's meaning. A suffix is a morpheme added to the end of a word. We know the suffixes -s and -es.",
        "Nouns are people, animals, places and things: dog, shirt, box. Adding -s or -es makes a noun mean more than one: dogs, shirts, boxes. Verbs describe an action: run, brush. Adding -s or -es changes the verb: I run, she runs; I brush, he brushes.",
        "Add -es after s, x, z, sh and ch, because -es adds a syllable that we can hear: box-es, brush-es."],
 gesture="No new sound. Review that -s says /s/ after quiet sounds and /z/ after voiced sounds.", soundwall="Review the '-s' and '-es' suffix cards.", formation=None,
 spell=dict(ido=["classes"], wedo=["grows","parts","brushes","matches"]),
 ww=dict(type="Word Meaning Activity", text="Add -s or -es and say what the new word means: dress (dresses = more than one dress), spend (spends = he/she spends), show, match, pass, rush, girl, dog, wish, box.", chain="class → classes → glasses → grasses → grass → gross → grows → glows → glow → blow → blows → brushes → brush → crush → crushes"),
 text_spell=["The girls got new dresses to match their glasses.","Chase and Finn walk their dogs on leashes.","Jane always says hello when she answers the phone."],
 chains=[["Morpheme Level: -s / -es","class → classes, grow → grows, part → parts, dress → dresses, brush → brushes, spend → spends, show → shows, match → matches, pass → passes, rush → rushes"]],
 hf=dict(dolch=["answer"], fry=["answer"]), lists={"-s":["grows","parts","spends","shows","screams","girls","dogs","plays","reads","jumps","coins","trains"],"-es":["classes","dresses","brushes","matches","passes","rushes","pushes","boxes","wishes","dishes","benches","glasses","foxes","buzzes"]})
P["100"] = dict(tag="The suffixes -er and -est (comparing)",
 notes=["-er means 'more than' (taller); -est means 'the most' (tallest). They are added to adjectives (describing words). Today's base words do not change spelling; the doubling rule is Lesson 108 and the y-to-i rule is Lesson 110."],
 pa=dict(blend=["/h/ /ī/ /ə/ (higher)","/s/ /m/ /orl/ /ə/ /s/ /t/ (smallest)","/sh/ /ar/ /p/ /ə/ (sharper)","/l/ /ŏ/ /ŋ/ /g/ /ə/ /s/ /t/ (longest)"], segment=["softer (soft-er)","tallest (tall-est)","newer (new-er)","hardest (hard-est)"]),
 bd=dict(chain="tall → taller → tallest → smallest → smaller → small → sharp → sharper → sharpest → shortest → shorter → short → soft → softer → softest", grid=g(["a","ar","or","ew","igh","ee","o"], ["ll","ller","llest","rp","rper","rpest","rt","rter","rtest","ft","fter","ftest"], ["t","sm","sh","s","l","h","n","d","f","gr","sl","qu"])),
 intro=["Adjectives are words that describe people, places, animals and things: a red car, a tall boy. Today we will learn two suffixes we add to adjectives to compare things.",
        "-er means 'more than'. Martin is taller than Jay. -est means 'the most'. Ty is the fastest person on the team. Add -er to compare two things; add -est to compare three or more.",
        "The -er ending says /ə/ (like the end of letter). Read the base word first, then add the suffix: tall-er, taller."],
 gesture="No new sound.", soundwall="Add '-er' and '-est' suffix cards.", formation=None,
 spell=dict(ido=["taller"], wedo=["tallest","softer","longest","newer"]),
 ww=dict(type="Word Meaning Activity", text="Add -er and -est, then use the words to compare: tall (taller, tallest), small, sharp, soft, short, long, new, hard, fast, high, dark, cold.", chain="tall → taller → tallest → smallest → smaller → small → sharp → sharper → sharpest → shortest → shorter → short → soft → softer → softest"),
 text_spell=["My bunny has the softest fur!","At this rate, we could walk there faster!","Jayden is taller than Josh but Eve is the tallest."],
 chains=[["Morpheme Level: -er / -est","tall → taller → tallest, small → smaller → smallest, sharp → sharper → sharpest, soft → softer → softest, high → higher → highest, new → newer → newest"]],
 hf=dict(dolch=["faster","better*"], fry=[]), lists={"-er":["higher","sharper","softer","newer","shorter","taller","smaller","longer","harder","faster","darker","colder","older","cleaner","deeper","louder"],"-est":["highest","smallest","tallest","shortest","longest","hardest","newest","softest","fastest","darkest","coldest","oldest","cleanest","deepest","loudest","sweetest"]})
P["101"] = dict(tag="The suffix -ly",
 notes=["-ly means 'in a ___ way' or 'like'. It turns adjectives into adverbs that tell how something is done (slow → slowly). -ly says /lē/. Today's base words do not change spelling (happy → happily comes with the y-to-i rule)."],
 pa=dict(blend=["slow-ly (slowly)","sad-ly (sadly)","quick-ly (quickly)","loud-ly (loudly)"], segment=["deeply (deep-ly)","badly (bad-ly)","swiftly (swift-ly)","firmly (firm-ly)"]),
 bd=dict(chain="slow → slowly → lowly → low → loud → loudly → proudly → proud → sad → sadly → madly → mad → glad → gladly → badly → bad", grid=g(["ow","ou","a","ee","ir","ick"], ["","ly","d","dly","p","ply","m","mly"], ["sl","l","pr","s","m","gl","b","d","f","qu","sw","sh","k"])),
 intro=["A suffix is a morpheme added to the end of a word. We know -s, -es, -er and -est. Today we will learn the suffix -ly.",
        "-ly means 'in a certain way' or 'like'. Tom drives slowly - in a slow way. Shane screams loudly - in a loud way. Words with -ly tell us how something is done.",
        "-ly says /lē/, with the Y spelling /ē/ like at the end of happy. Read the base word, then add -ly: slow-ly, slowly."],
 gesture="No new sound.", soundwall="Add '-ly' suffix card.", formation=None,
 spell=dict(ido=["slowly"], wedo=["sadly","quickly","loudly","deeply"]),
 ww=dict(type="Word Meaning Activity", text="Add -ly and use the word in a sentence about how something is done: slow (slowly - He walks slowly.), sad, quick, loud, deep, bad, swift, firm, kind, soft, glad, brave.", chain="slow → slowly → lowly → low → loud → loudly → proudly → proud → sad → sadly → madly → mad → glad → gladly → badly → bad"),
 text_spell=["Sadly, it did not work out.","Can you repeat the answer slowly?","Being honest is highly important."],
 chains=[["Morpheme Level: add -ly","slow → slowly, sad → sadly, quick → quickly, loud → loudly, deep → deeply, bad → badly, swift → swiftly, firm → firmly, kind → kindly, brave → bravely"]],
 hf=dict(dolch=["honest","honour"], fry=[]), lists={"-ly":["deeply","slowly","badly","loudly","sadly","quickly","swiftly","firmly","wrongly","lightly","shortly","kindly","softly","gladly","bravely","sweetly","nearly","calmly","proudly","weekly","hourly","mostly","lastly","clearly"]})
P["102"] = dict(tag="The suffixes -less and -ful",
 notes=["-less means 'without' (sleepless = without sleep). -ful means 'full of' (helpful = full of help). Note that the suffix -ful is spelled with one L."],
 pa=dict(blend=["help-less (helpless)","help-ful (helpful)","hope-ful (hopeful)","end-less (endless)"], segment=["thankful (thank-ful)","useful (use-ful)","painful (pain-ful)","spotless (spot-less)"]),
 bd=dict(chain="help → helpful → helpless → hopeless → hopeful → useful → useless → careless → careful → thankful → painful → painless → spotless → endless", grid=g(["e","o_e","u_e","are","a","ai","o","en"], ["lp","lpful","lpless","peful","peless","seful","seless","reful","reless","nkful","nful","nless","tless","dless"], ["h","c","th","p","sp","f","gr","sk","cl","harm","rest","fear"])),
 intro=["We know several suffixes: -s, -es, -er, -est, -ly. Today we will learn two suffixes that change what a word means in a big way.",
        "-less means 'without'. Sleepless means without sleep. Careless means without care. -ful means 'full of'. Helpful means full of help. Hopeful means full of hope. Notice that the suffix -ful has only one L.",
        "Read the base word first, then the suffix, and think about the meaning: hope-less, hopeless - without hope."],
 gesture="No new sound.", soundwall="Add '-less' and '-ful' suffix cards.", formation=None,
 spell=dict(ido=["helpful"], wedo=["helpless","hopeful","useful","endless"]),
 ww=dict(type="Word Meaning Activity", text="Add -less or -ful (or both) and explain the meaning: help, hope, use, care, thank, pain, spot, end, fear, harm, rest, thought.", chain="help → helpful → helpless → hopeless → hopeful → useful → useless → careless → careful → thankful → painful → painless → spotless → endless"),
 text_spell=["The trophy was such an honour, I am speechless.","The floor is spotless after endless cleaning.","We are thankful for the useful gifts."],
 chains=[["Morpheme Level: -less / -ful","help → helpful → helpless, hope → hopeful → hopeless, use → useful → useless, care → careful → careless, thank → thankful, pain → painful → painless, spot → spotless, end → endless"]],
 hf=dict(dolch=[], fry=[]), lists={"-less":["helpless","countless","endless","clueless","spotless","flawless","harmless","careless","hopeless","useless","painless","fearless","restless","speechless","sleepless","homeless"],"-ful":["helpful","thankful","useful","painful","hopeful","skillful","graceful","careful","wishful","delightful","fearful","playful","cheerful","powerful","peaceful","joyful"]})
P["103"] = dict(tag="The prefix un-",
 notes=["A prefix is a morpheme added to the beginning of a word. un- means 'not' or 'the opposite of' (unhappy = not happy; unzip = the opposite of zip)."],
 pa=dict(blend=["un-wrap (unwrap)","un-safe (unsafe)","un-tie (untie)","un-kind (unkind)"], segment=["unhappy (un-hap-py)","undo (un-do)","unclean (un-clean)","uncover (un-cov-er)"]),
 bd=dict(chain="tie → untie → undo → unlock → lock → unpack → pack → unzip → zip → unclean → clean → unkind → kind → unsafe → safe", grid=g(["ie","o","o","a","i","ea","i","a_e"], ["","ck","p","n","nd","fe"], ["un","t","d","l","p","z","cl","k","s","unt","unl","unp","unz","uncl","unk","uns"])),
 intro=["A suffix is a morpheme added to the end of a word. A prefix is a morpheme added to the beginning of a word. Today we will learn the prefix un-.",
        "un- means 'not' or 'the opposite of'. Unhappy means not happy. Unkind means not kind. Unzip means the opposite of zip. Uncover means the opposite of cover.",
        "Read the prefix, then the base word, then think about the meaning: un-lock, unlock - the opposite of lock."],
 gesture="No new sound.", soundwall="Add 'un-' prefix card.", formation=None,
 spell=dict(ido=["unwrap"], wedo=["untie","unsafe","unkind","unhappy"]),
 ww=dict(type="Word Meaning Activity", text="Add un- and explain the meaning: wrap (unwrap = the opposite of wrap), tie, safe, kind, happy, do, clean, cover, lock, pack, fair, well.", chain="tie → untie → undo → unlock → lock → unpack → pack → unzip → zip → unclean → clean → unkind → kind → unsafe → safe"),
 text_spell=["The trip was truly unlike any other.","Please unlock the car so I can unload it.","Tell me the truth, why does he look so unhappy?"],
 chains=[["Morpheme Level: add un-","wrap → unwrap, tie → untie, safe → unsafe, do → undo, kind → unkind, clean → unclean, happy → unhappy, cover → uncover, lock → unlock, pack → unpack"]],
 hf=dict(dolch=["truth","truly"], fry=[]), lists={"un-":["unwrap","untamed","unsafe","undo","untie","unkind","unclean","unhappy","unfinished","uncover","unlock","unpack","unzip","unfair","unwell","unlucky","unload","unplug","unseen","unable","unlike","unfold"]})
P["104"] = dict(tag="The prefixes pre- and re-",
 notes=["pre- means 'before' (preview = watch before; preheat = heat before). re- means 'again' or 'back' (redo = do again; return = go back). Both prefixes have an open syllable with a long e: /prē/, /rē/."],
 pa=dict(blend=["pre-view (preview)","re-do (redo)","pre-heat (preheat)","re-play (replay)"], segment=["preset (pre-set)","revisit (re-vis-it)","preteen (pre-teen)","rewind (re-wind)"]),
 bd=dict(chain="play → replay → repay → pay → prepay → preset → reset → set → resend → send → rewind → wind → refill → fill → prefill", grid=g(["ay","e","i","ill","o"], ["","t","nd","ll"], ["pre","re","pl","p","s","w","f","d","t","m","pres","res","rep","prep","rew","ref"])),
 intro=["We learned the prefix un-. Today we will learn two more prefixes: pre- and re-.",
        "pre- means 'before'. Preview means to watch before. Preheat means to heat before. Preschool is school before big school.",
        "re- means 'again' or 'back'. Redo means to do again. Replay means to play again. Return means to give or go back. Both prefixes are open syllables, so the e says /ē/: pre-, re-."],
 gesture="No new sound.", soundwall="Add 'pre-' and 're-' prefix cards.", formation=None,
 spell=dict(ido=["preview"], wedo=["preheat","redo","replay","rewind"]),
 ww=dict(type="Word Meaning Activity", text="Add pre- or re- and explain the meaning: view (preview = watch before), heat, pay, set, do (redo = do again), play, wind, fill, visit, send, sell, cook.", chain="play → replay → repay → pay → prepay → preset → reset → set → resend → send → rewind → wind → refill → fill → prefill"),
 text_spell=["Will I need to prepay for the food?","Please untie the knot and redo the bow.","Replay the tape so we can review it."],
 chains=[["Morpheme Level: pre-","view → preview, heat → preheat, pay → prepay, set → preset, cook → precook, teen → preteen, school → preschool"],["Morpheme Level: re-","do → redo, play → replay, wind → rewind, fill → refill, visit → revisit, send → resend, sell → resell, turn → return, build → rebuild"]],
 hf=dict(dolch=[], fry=[]), lists={"pre-":["preset","precook","preteen","prepay","preview","preheat","preschool","prefix","pretest","precut","prepaid","pregame"],"re-":["revisit","resend","rewind","resell","replay","refill","redo","return","rebuild","reread","repaint","reheat","reload","retell","rethink","replant"]})
P["105"] = dict(tag="The prefix dis-",
 notes=["dis- means 'not' or 'the opposite of' (disagree = do not agree; disconnect = take apart). dis- is a closed syllable: /dĭs/."],
 pa=dict(blend=["dis-like (dislike)","dis-agree (disagree)","dis-order (disorder)","dis-count (discount)"], segment=["disrespect (dis-re-spect)","dislodge (dis-lodge)","disown (dis-own)","disconnect (dis-con-nect)"]),
 bd=dict(chain="like → dislike → disagree → agree → disarm → arm → disorder → order → discount → count → disconnect → connect → disobey → obey", grid=g(["i_e","ee","ar","or","ou","e"], ["","m","der","nt","ct"], ["dis","l","agr","disagr","ord","disord","c","disc","conn","disconn","ob","disob"])),
 intro=["We know the prefixes un-, pre- and re-. Today we will learn the prefix dis-.",
        "dis- means 'not' or 'the opposite of', just like un-. Disagree means to not agree. Dislike means to not like. Disconnect means to take apart - the opposite of connect. Disorder means not in order.",
        "dis- is a closed syllable: d-i-s, /dĭs/. Read the prefix, then the base word: dis-like, dislike."],
 gesture="No new sound.", soundwall="Add 'dis-' prefix card.", formation=None,
 spell=dict(ido=["dislike"], wedo=["disagree","disorder","discount","disconnect"]),
 ww=dict(type="Word Meaning Activity", text="Add dis- and explain the meaning: like (dislike = not like), agree, order, connect, own, count, respect, obey, trust, honest, appear, please.", chain="like → dislike → disagree → agree → disarm → arm → disorder → order → discount → count → disconnect → connect → disobey → obey"),
 text_spell=["Mum will disinfect the toys before the baby plays with them.","Jay and I disagree about what to eat for lunch.","The WiFi got disconnected so I could not play the video game."],
 chains=[["Morpheme Level: add dis-","like → dislike, agree → disagree, order → disorder, connect → disconnect, own → disown, count → discount, respect → disrespect, obey → disobey, trust → distrust, appear → disappear"]],
 hf=dict(dolch=[], fry=[]), lists={"dis-":["disrespect","dislodge","disorder","discount","disagree","disown","disinterested","dislike","disconnect","disobey","distrust","disappear","dishonest","displease","disarm","disinfect","disband","discard"]})
P["106"] = dict(tag="Affixes review 1: -s, -es, -ed, -ing, -er, -est, -ly, -less, -ful, un-, pre-, re-, dis-",
 notes=["Review of all affixes so far. Word work: break words into parts (prefix + base + suffix) and give a definition."],
 pa=dict(blend=["un-fin-ished (unfinished)","re-start (restart)","harm-ful (harmful)","loud-est (loudest)"], segment=["preset (pre-set)","spotless (spot-less)","smarter (smart-er)","dislike (dis-like)"]),
 bd=dict(chain="start → restart → restarted → started → starting → starter → smart → smarter → smartest → smartly → kind → unkind → kindly → kindness*", grid=g(["ar","i","e"], ["t","ted","ting","ter","test","tly","nd","ndly"], ["st","re","sm","k","un","rest","unk","pres","dis"])),
 intro=["Morphemes are word parts that change a word's meaning. Suffixes come at the end: -s and -es (more than one; he/she does), -ed (past), -ing (happening now), -er and -est (compare), -ly (how), -less (without), -ful (full of). Prefixes come at the beginning: un- and dis- (not / opposite), pre- (before), re- (again / back).",
        "To read a long word, find the prefix, the base word and the suffix. Read each part, then put them together and think about the meaning: un-finish-ed, unfinished - not finished."],
 gesture="No new sound.", soundwall="Review all affix cards.", formation=None,
 spell=dict(ido=["unfinished"], wedo=["restart","harmful","loudest","dislike"]),
 ww=dict(type="Word Meaning Activity (word parts)", text="Break each word into parts and give a definition: prepays (pre + pay + s), unfinished, restarting, harmless, replayed, disliked, kindly, hopeful, smartest, uncovered.", chain="start → restart → restarted → started → starting → starter → smart → smarter → smartest → smartly → kind → unkind → kindly"),
 text_spell=["Ride your bike slowly to prevent a crash.","He discovered a mistake and had to redo his work.","We are truly thankful for all the gifts."],
 chains=[["Morpheme Level: build words","start → restart → restarted → restarting; kind → unkind → kindly → unkindly; help → helpful → helpless → unhelpful; play → replay → replayed → player"]],
 hf=dict(dolch=[], fry=[]), lists={"review":["unfinished","going","jumped","mixes","smarter","loudest","slowly","harmful","spotless","preset","restart","unkind","dislike","smaller","harmless","replay","hopeful","prepays","uncovered","disliked","restarting","kindly","careless","useful"]})
