# Lesson plan data, lessons 21-41c
P = {}
P["21"] = dict(tag="The suffix -s spells /z/",
 notes=["After voiced sounds (like /g/, /n/, /d/, /b/ and vowels) the suffix -s says /z/: dogs, pens, fans. Students already know S spells /s/; today S also spells /z/ (is, as, has)."],
 pa=dict(blend=["/d/ /ŏ/ /g/ /z/ (dogs)","/f/ /ă/ /n/ /z/ (fans)","/p/ /ĕ/ /n/ /z/ (pens)","/b/ /ŭ/ /g/ /z/ (bugs)"], segment=["bags (/b/ /ă/ /g/ /z/)","fins (/f/ /ĭ/ /n/ /z/)","pods (/p/ /ŏ/ /d/ /z/)","suds (/s/ /ŭ/ /d/ /z/)"]),
 bd=dict(chain="dog → dogs → digs → pigs → pins → pans → fans → fins → bins → buns → bugs → bags", grid=dict(initial=["d","p","f","b","m","t","n","s","g"], medial=["a","e","i","o","u"], final=["g","n","d","b","gs","ns","ds","bs"])),
 intro=["We learned that the suffix -s says /s/ after quiet sounds like /t/ and /p/: cats, maps. Today we will learn that after noisy (voiced) sounds, the suffix -s says /z/: dogs, pens, bugs.",
        "Listen: /dŏg/ - /dŏgz/. The voice stays on, so the -s sounds like /z/. The letter S can spell /s/ and /z/. We also see S spelling /z/ in the words is, as and has."],
 gesture="Compare /s/ (voice off) and /z/ (voice on) with a hand on the throat. Both use teeth together with air pushed through.", soundwall="Add 's' and '-s' under /z/.", formation=None,
 spell=dict(ido=["dogs"], wedo=["pens","bugs","fans"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="dog → dogs → digs → pigs → pins → pans → fans → fins → bins → bugs → bags → tags"),
 text_spell=["The dogs dig in the mud.","Dad set ten pens on the bed.","Ben tugs on the bags."],
 chains=[["Morpheme Level: add -s","dog → dogs, pen → pens, bug → bugs, fan → fans"],["Phoneme Level: Intro Lesson","dog → dogs → digs → pigs → pins → pans → fans → fins → bins → bugs → bags → tags"]],
 hf=dict(dolch=["is","as","has"], fry=["is","as","has"]), lists={"-s /z/":["dogs","bugs","bags","pans","fins","pens","bins","tags","dads","fans","pigs","suds","pods","buds","digs","tugs"],"s /z/":["is","as"]})
P["22"] = dict(tag="The grapheme K spells /k/",
 notes=["K is used to spell /k/ before i and e (kid, kept). C is used before a, o and u. Both letters spell the same sound.",
        "ask and fast are heart words for now: in Australian/NZ English the A says /ar/ (introduced in Lesson 77 AUS)."],
 pa=dict(blend=["/k/ /ĭ/ /d/ (kid)","/k/ /ĭ/ /t/ (kit)","/s/ /k/ /ĭ/ /p/ (skip)","/d/ /ĕ/ /s/ /k/ (desk)"], segment=["kin (/k/ /ĭ/ /n/)","kids (/k/ /ĭ/ /d/ /z/)","skin (/s/ /k/ /ĭ/ /n/)","skit (/s/ /k/ /ĭ/ /t/)"]),
 bd=dict(chain="kit → kid → kin → pin → pit → sit → skit → skid → skin → skip → kip → kick*", grid=dict(initial=["k","p","s","sk","c","m","d","t","b"], medial=["a","e","i","o","u"], final=["t","d","n","p","g","m","s"]), note="*kick uses ck (Lesson 44) - skip if not yet taught; use skim instead."),
 intro=["Today we are learning about the letter K. K is a consonant. The letter K spells the /k/ sound like at the beginning of kite. We already know that C spells /k/ too.",
        "K comes at the beginning of a word before i and e, such as kid and kit. C comes before a, o and u, such as cat and cot. K can also come at the end of a word after another consonant, such as desk."],
 gesture="Review the /k/ gesture (tongue pulled back, voice off, quick stop sound).", soundwall="Add 'k' under /k/ next to 'c'.", formation="Practise letter formation for uppercase K and lowercase k.",
 spell=dict(ido=["kid"], wedo=["kit","desk","skip"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="kit → kid → kin → skin → skip → skim → skit → kit"),
 text_spell=["The kids skip.","Kim got a kit.","Ken sat at the desk."],
 chains=[["Onset-Rime Level: -id","kid → skid → did → bid"],["Onset-Rime Level: -in","kin → skin → pin → tin"],["Phoneme Level: Intro Lesson","kit → kid → kin → skin → skip → skim → skit → kit"]],
 hf=dict(dolch=["ask"], fry=["ask"]), lists={"k /k/":["kit","kid","kin","kids","skip","skin","skit","skim","skid","desk","task","Kim","Ken","kept"]})
P["23"] = dict(tag="The grapheme H spells /h/",
 pa=dict(blend=["/h/ /ă/ /t/ (hat)","/h/ /ĭ/ /m/ (him)","/h/ /ŭ/ /g/ (hug)","/h/ /ĕ/ /n/ (hen)"], segment=["had (/h/ /ă/ /d/)","has (/h/ /ă/ /z/)","hum (/h/ /ŭ/ /m/)","hunt (/h/ /ŭ/ /n/ /t/)"]),
 bd=dict(chain="hat → hit → hip → hop → hog → hug → hum → him → hid → had → hand → hint", grid=dict(initial=["h","p","s","m","b","k","d","t","g"], medial=["a","e","i","o","u"], final=["t","p","g","m","d","nd","nt","n"])),
 intro=["Today we are learning about the letter H. H is a consonant. The letter H spells the /h/ sound like at the beginning of hat.",
        "H comes at the beginning of a word, such as had and has. H does not spell /h/ at the end of a word."],
 gesture="To make the /h/ sound as in 'hat', open your mouth and push a puff of air from the back of your throat... (model). Your voice is off. Watch me /h/. You try /h/.",
 soundwall="Add 'h' under /h/ (back of throat).", formation="Practise letter formation for uppercase H and lowercase h.",
 spell=dict(ido=["hat"], wedo=["him","hug","hand"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="hat → hit → hip → hop → hog → hug → hum → hem → hen → hint → hunt"),
 text_spell=["He has a big hat.","Did he hug me?","The hen hid in the hut."],
 chains=[["Onset-Rime Level: -ug","hug → bug → mug → dug"],["Onset-Rime Level: -im","him → dim → Tim → Kim"],["Phoneme Level: Intro Lesson","hat → hit → hip → hop → hog → hug → hum → hem → hen → hint → hunt"]],
 hf=dict(dolch=["had","has","him","he","be","me"], fry=["had","has","him","he","be","me"]), lists={"h /h/":["hat","had","has","him","his","hug","hen","hum","hunt","hint","hand","hip","hop","hot","hid","hut","hem"]})
P["24"] = dict(tag="The grapheme R spells /r/",
 pa=dict(blend=["/r/ /ă/ /t/ (rat)","/r/ /ŭ/ /n/ (run)","/r/ /ĕ/ /d/ (red)","/r/ /ĭ/ /p/ (rip)"], segment=["rug (/r/ /ŭ/ /g/)","rim (/r/ /ĭ/ /m/)","rent (/r/ /ĕ/ /n/ /t/)","rust (/r/ /ŭ/ /s/ /t/)"]),
 bd=dict(chain="rat → ran → run → rug → rig → rip → rap → ramp → rump → rust → rest → rent", grid=dict(initial=["r","h","k","s","m","b","d","t","p"], medial=["a","e","i","o","u"], final=["t","n","g","p","mp","st","nt","d"])),
 intro=["Today we are learning about the letter R. R is a consonant. The letter R spells the /r/ sound like at the beginning of red.",
        "R comes at the beginning of a word, such as rat and run. In this lesson R is only at the beginning; next lesson we will read R after another consonant (crab, frog)."],
 gesture="To make the /r/ sound as in 'red', pull your tongue up and back a little without touching the roof of your mouth, and round your lips slightly... (model). Be sure your voice is on. /r/ can be stretched a little. Watch me /rrr/. You try /rrr/. Do not say /ruh/.",
 soundwall="Add 'r' under /r/ (tongue lifted).", formation="Practise letter formation for uppercase R and lowercase r.",
 spell=dict(ido=["rat"], wedo=["run","red","rust"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="rat → ran → run → rug → rag → rap → rip → rim → ram → ramp"),
 text_spell=["The rat ran to the rug.","Rob has a red hat.","Did Ron rest on the raft?"],
 chains=[["Onset-Rime Level: -un","run → sun → fun → bun"],["Onset-Rime Level: -ust","rust → must → dust → gust"],["Phoneme Level: Intro Lesson","rat → ran → run → rug → rag → rap → rip → rim → ram → ramp"]],
 hf=dict(dolch=["ran","run","red"], fry=["run"]), lists={"r /r/":["rat","ran","run","rug","rag","rap","rip","rim","red","rod","rob","rub","rug","ramp","rest","rent","rust","raft","Ron","Rob"]})
P["25"] = dict(tag="R in consonant clusters at the beginning of words (br, cr, dr, fr, gr, pr, tr)",
 notes=["A consonant cluster (often called a 'blend') is two consonants together that keep their own sounds: /k/ /r/ in crab. Do not teach clusters as a single sound - segment each sound.",
        "The /t/ before /r/ often sounds like /ch/ (trip) and /d/ before /r/ like /j/ (drum). This is normal; students still spell them with t and d."],
 pa=dict(blend=["/g/ /r/ /ă/ /b/ (grab)","/f/ /r/ /ŏ/ /g/ (frog)","/d/ /r/ /ŭ/ /m/ (drum)","/t/ /r/ /ĭ/ /p/ (trip)"], segment=["crab (/k/ /r/ /ă/ /b/)","drip (/d/ /r/ /ĭ/ /p/)","brag (/b/ /r/ /ă/ /g/)","grin (/g/ /r/ /ĭ/ /n/)"]),
 bd=dict(chain="rip → trip → drip → drop → crop → crab → grab → grub → drum → drug → drag → brag", grid=dict(initial=["r","tr","dr","cr","gr","br","fr","pr"], medial=["a","e","i","o","u"], final=["p","b","g","m","n","t","d"])),
 intro=["We know that R spells /r/ at the beginning of a word. R can also come right after another consonant at the beginning of a word: c-r-a-b, crab. Each consonant keeps its own sound, so we say every sound: /k/ /r/ /ă/ /b/.",
        "Today we will read and spell words that begin with two consonants, such as grab, frog, crop and trip. Listen carefully for both sounds at the start."],
 gesture="Review /r/. Practise saying two consonant sounds quickly one after the other: /k/ /r/, /g/ /r/, /t/ /r/.", soundwall="No new grapheme. Review 'r' under /r/.", formation=None,
 spell=dict(ido=["frog"], wedo=["grab","trip","drum"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="rip → trip → trap → tramp → ramp → cramp → crab → grab → grub → drum"),
 text_spell=["The frog can grab the bug.","Greg hit the drum.","Did Brad trip on the crab?"],
 chains=[["Onset-Rime Level: -ip","rip → trip → drip → grip"],["Onset-Rime Level: -ab","crab → grab → drab"],["Phoneme Level: Intro Lesson","rip → trip → trap → tramp → ramp → cramp → crab → grab → grub → drum"]],
 hf=dict(dolch=["from"], fry=["from"]), lists={"r clusters":["brag","crab","trim","drop","crib","drip","grab","prop","grub","grin","frog","trip","drum","crop","trap","grid","brim","press","from","trot"]})
P["26"] = dict(tag="The grapheme L spells /l/",
 notes=["L at the end of a one-syllable word after a short vowel is usually doubled (bell, hill) - that comes in Lesson 42. Today L is at the beginning or after another sound (help, milk)."],
 pa=dict(blend=["/l/ /ă/ /p/ (lap)","/l/ /ĕ/ /t/ (let)","/l/ /ĭ/ /d/ (lid)","/l/ /ŏ/ /s/ /t/ (lost)"], segment=["lip (/l/ /ĭ/ /p/)","lump (/l/ /ŭ/ /m/ /p/)","left (/l/ /ĕ/ /f/ /t/)","list (/l/ /ĭ/ /s/ /t/)"]),
 bd=dict(chain="lap → lip → lid → let → lest → list → lost → last → lamp → limp → lump → land", grid=dict(initial=["l","r","h","k","b","m","s","t","d"], medial=["a","e","i","o","u"], final=["p","d","t","st","mp","nd","ft"])),
 intro=["Today we are learning about the letter L. L is a consonant. The letter L spells the /l/ sound like at the beginning of leaf.",
        "L can come at the beginning of a word, such as lap and let. L can also come in the middle or at the end of a word, such as help and milk."],
 gesture="To make the /l/ sound as in 'leaf', put the tip of your tongue behind your top teeth and let your voice flow around the sides of your tongue... (model). Be sure your voice is on. /l/ is a continuous sound. Watch me /lll/. You try /lll/.",
 soundwall="Add 'l' under /l/ (tongue behind top teeth).", formation="Practise letter formation for uppercase L and lowercase l.",
 spell=dict(ido=["lap"], wedo=["let","lid","lost"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="lap → lip → lid → lad → lag → leg → let → lot → lost → list → lift → left"),
 text_spell=["Lin lost the lid.","Let me help him.","Bill left the lamp on."],
 chains=[["Onset-Rime Level: -ip","lip → hip → tip → dip"],["Onset-Rime Level: -ost","lost → cost"],["Phoneme Level: Intro Lesson","lap → lip → lid → lad → lag → leg → let → lot → lost → list → lift → left"]],
 hf=dict(dolch=["let","look","book"], fry=["let","look"]), lists={"l /l/":["lap","lip","lid","let","lot","log","leg","lad","lag","lost","last","list","left","lift","lump","land","lamp","help","milk","melt","held","Lin","Len"]})
P["27"] = dict(tag="L in consonant clusters at the beginning of words (bl, cl, fl, gl, pl, sl)",
 notes=["As with R clusters, treat each consonant as its own sound: /f/ /l/ /ă/ /g/, flag."],
 pa=dict(blend=["/f/ /l/ /ĭ/ /p/ (flip)","/g/ /l/ /ă/ /d/ (glad)","/p/ /l/ /ă/ /n/ (plan)","/s/ /l/ /ŭ/ /g/ (slug)"], segment=["clap (/k/ /l/ /ă/ /p/)","slam (/s/ /l/ /ă/ /m/)","plant (/p/ /l/ /ă/ /n/ /t/)","blend (/b/ /l/ /ĕ/ /n/ /d/)"]),
 bd=dict(chain="lap → clap → slap → slip → flip → flap → flag → flat → slat → slot → plot → plod → plan → plant", grid=dict(initial=["l","cl","sl","fl","pl","bl","gl","r","h"], medial=["a","e","i","o","u"], final=["p","g","t","d","n","nt","m","b"])),
 intro=["We know that L spells /l/ at the beginning of a word. L can also come right after another consonant at the beginning of a word: f-l-a-g, flag. Say every sound: /f/ /l/ /ă/ /g/.",
        "Today we will read and spell words that begin with two consonants ending in L, such as slip, glad, clap and plan."],
 gesture="Review /l/. Practise pairs of consonant sounds: /f/ /l/, /s/ /l/, /k/ /l/, /p/ /l/, /b/ /l/, /g/ /l/.", soundwall="No new grapheme. Review 'l' under /l/.", formation=None,
 spell=dict(ido=["flag"], wedo=["slip","glad","plan","clap"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="lap → clap → slap → slip → slim → slid → slug → plug → plum → plan → plant"),
 text_spell=["The slug is on the plant.","Glen is glad to help.","Did the flag flap in the gust?"],
 chains=[["Onset-Rime Level: -ap","clap → slap → flap"],["Onset-Rime Level: -ug","slug → plug → glug"],["Phoneme Level: Intro Lesson","lap → clap → slap → slip → slim → slid → slug → plug → plum → plan → plant"]],
 hf=dict(dolch=["are"], fry=["are"]), lists={"l clusters":["flip","slug","flag","glad","plan","clap","slam","plant","plot","plum","plug","slip","slid","slim","club","blot","bled","glum","clam","clip","flat","fled"]})
P["28"] = dict(tag="The grapheme W spells /w/",
 notes=["W is only used at the beginning of a word or syllable. At the end of words /w/ is not spelled with w alone."],
 pa=dict(blend=["/w/ /ĭ/ /n/ (win)","/w/ /ă/ /g/ (wag)","/w/ /ĕ/ /t/ (wet)","/s/ /w/ /ĭ/ /m/ (swim)"], segment=["web (/w/ /ĕ/ /b/)","went (/w/ /ĕ/ /n/ /t/)","twig (/t/ /w/ /ĭ/ /g/)","swam (/s/ /w/ /ă/ /m/)"]),
 bd=dict(chain="win → wig → wag → wed → web → wet → went → west → wept → swept → swim → twin → twig", grid=dict(initial=["w","sw","tw","l","r","h","d","b"], medial=["a","e","i","o","u"], final=["n","g","b","t","nt","st","pt","m"]), note=None),
 intro=["Today we are learning about the letter W. W is a consonant. The letter W spells the /w/ sound like at the beginning of watermelon.",
        "W comes at the beginning of a word, such as win and wag. W can also come after another consonant at the beginning, such as swim and twin."],
 gesture="To make the /w/ sound as in 'watermelon', round your lips like you are going to whistle, then open them as your voice comes out... (model). Be sure your voice is on. Watch me /w/. You try /w/.",
 soundwall="Add 'w' under /w/ (lips rounded).", formation="Practise letter formation for uppercase W and lowercase w.",
 spell=dict(ido=["win"], wedo=["wet","went","swim"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="win → wig → wag → wet → web → wed → went → west → wept → swept"),
 text_spell=["The twins went to swim.","Wes got wet in the wind.","Did Will win?"],
 chains=[["Onset-Rime Level: -et","wet → let → get → met"],["Onset-Rime Level: -in","win → twin → tin → pin"],["Phoneme Level: Intro Lesson","win → wig → wag → wet → web → wed → went → west → wept → swept"]],
 hf=dict(dolch=["went","will","was"], fry=["went","will"]), lists={"w /w/":["web","west","wag","win","wig","wet","went","wept","wed","wind","swam","swim","twin","twig","swept","Wes","Will","Wend"]})
P["29"] = dict(tag="The grapheme J spells /j/",
 notes=["J is only used at the beginning of words and syllables. /j/ at the end of a word is spelled -ge or -dge (Lessons 61 and 70)."],
 pa=dict(blend=["/j/ /ă/ /m/ (jam)","/j/ /ĕ/ /t/ (jet)","/j/ /ŏ/ /g/ (jog)","/j/ /ŭ/ /m/ /p/ (jump)"], segment=["jab (/j/ /ă/ /b/)","jig (/j/ /ĭ/ /g/)","just (/j/ /ŭ/ /s/ /t/)","jest (/j/ /ĕ/ /s/ /t/)"]),
 bd=dict(chain="jam → jab → jog → jig → jug → jut → just → jest → jet → jets → jots → jobs", grid=dict(initial=["j","w","l","r","h","b","d","g"], medial=["a","e","i","o","u"], final=["m","b","g","t","st","ts","bs","mp"])),
 intro=["Today we are learning about the letter J. J is a consonant. The letter J spells the /j/ sound like at the beginning of jar.",
        "J comes at the beginning of a word, such as job and jet. J is not used at the end of a word."],
 gesture="To make the /j/ sound as in 'jar', put your teeth together and round your lips, then push the air out with your voice on... (model). It is like /ch/ with the voice on. /j/ is a quick sound. Watch me /j/. You try /j/.",
 soundwall="Add 'j' under /j/ (tongue lifted).", formation="Practise letter formation for uppercase J and lowercase j.",
 spell=dict(ido=["jam"], wedo=["jet","jog","jump"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="jam → jab → jog → jig → jug → jut → just → jest → jet"),
 text_spell=["Jen and Jim jog.","Jeb has a job on a jet.","I just got a jug of jam."],
 chains=[["Onset-Rime Level: -et","jet → wet → get → let"],["Onset-Rime Level: -ust","just → must → rust → dust"],["Phoneme Level: Intro Lesson","jam → jab → jog → jig → jug → jut → just → jest → jet"]],
 hf=dict(dolch=["jump","just","was"], fry=["just","was"]), lists={"j /j/":["jam","jab","jog","jig","jug","jut","jet","jot","job","jobs","just","jest","jump","Jen","Jim","Jeb","Jill"]})
P["30"] = dict(tag="The grapheme Y spells /y/",
 notes=["Y is a consonant at the beginning of a word (yes). At the end of words Y is a vowel (my, happy) - Lessons 73 and 74."],
 pa=dict(blend=["/y/ /ĕ/ /s/ (yes)","/y/ /ă/ /m/ (yam)","/y/ /ĕ/ /t/ (yet)","/y/ /ĕ/ /l/ /p/ (yelp)"], segment=["yak (/y/ /ă/ /k/)","yum (/y/ /ŭ/ /m/)","yap (/y/ /ă/ /p/)","yip (/y/ /ĭ/ /p/)"]),
 bd=dict(chain="yes → yet → yam → yap → yip → yum → yuk → yelp → help → held → yell*", grid=dict(initial=["y","j","w","l","r","h","m","b"], medial=["a","e","i","o","u"], final=["s","t","m","p","k","lp","ld"]), note="*yell uses ll (Lesson 42) - stop at held."),
 intro=["Today we are learning about the letter Y. Y is a consonant at the beginning of a word. The letter Y spells the /y/ sound like at the beginning of yellow.",
        "Y comes at the beginning of a word, such as yes and yam."],
 gesture="To make the /y/ sound as in 'yellow', lift the middle of your tongue toward the roof of your mouth and glide your voice out... (model). Be sure your voice is on. Watch me /y/. You try /y/.",
 soundwall="Add 'y' under /y/ (tongue lifted).", formation="Practise letter formation for uppercase Y and lowercase y.",
 spell=dict(ido=["yes"], wedo=["yet","yam","yelp"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="yes → yet → yam → yap → yip → yum → yuk → yelp"),
 text_spell=["Yes, I can yelp.","The yak got a yam.","Did Yin yell yet?"],
 chains=[["Onset-Rime Level: -et","yet → jet → wet → get"],["Onset-Rime Level: -um","yum → hum → gum → sum"],["Phoneme Level: Intro Lesson","yes → yet → yam → yap → yip → yum → yuk → yelp"]],
 hf=dict(dolch=["yes","yet"], fry=["yes"]), lists={"y /y/":["yes","yet","yam","yap","yip","yum","yak","yelp","yuk","Yin"]})
P["31"] = dict(tag="The grapheme X spells /ks/",
 notes=["X spells two sounds, /k/ + /s/. It usually comes at the end of a word (box, six). Count /ks/ as two sounds when segmenting."],
 pa=dict(blend=["/b/ /ŏ/ /k/ /s/ (box)","/s/ /ĭ/ /k/ /s/ (six)","/f/ /ŏ/ /k/ /s/ (fox)","/w/ /ă/ /k/ /s/ (wax)"], segment=["mix (/m/ /ĭ/ /k/ /s/)","tux (/t/ /ŭ/ /k/ /s/)","next (/n/ /ĕ/ /k/ /s/ /t/)","flex (/f/ /l/ /ĕ/ /k/ /s/)"]),
 bd=dict(chain="box → fox → fix → six → mix → max → wax → tax → tux → flex → next → text", grid=dict(initial=["b","f","s","m","w","t","fl","n"], medial=["a","e","i","o","u"], final=["x","xt","t","p","g"])),
 intro=["Today we are learning about the letter X. The letter X spells two sounds together, /k/ and /s/, like at the end of box.",
        "X comes at the end of a word, such as box and wax. It can also come before t, such as next and text."],
 gesture="Say /k/ then /s/ quickly: /ks/. Feel the back of the tongue pop for /k/ then the air hiss for /s/. Watch me /ks/. You try /ks/.",
 soundwall="Add 'x' under /k/ and /s/ with a note that it spells both sounds.", formation="Practise letter formation for uppercase X and lowercase x.",
 spell=dict(ido=["box"], wedo=["six","fox","next"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="box → fox → fix → six → mix → max → wax → tax → tux → flex → next"),
 text_spell=["Max has six pets.","The fox is in the box.","Can you fix it next?"],
 chains=[["Onset-Rime Level: -ox","box → fox → pox"],["Onset-Rime Level: -ix","six → fix → mix"],["Phoneme Level: Intro Lesson","box → fox → fix → six → mix → max → wax → tax → tux → flex → next"]],
 hf=dict(dolch=["six","you"], fry=["you"]), lists={"x /ks/":["box","fox","fix","six","mix","max","wax","tax","tux","flex","next","text","ox","ax","Max","Rex","Lex"]})
P["32"] = dict(tag="The grapheme QU spells /kw/",
 notes=["Q is always followed by U. Together they spell two sounds, /k/ + /w/. Count /kw/ as two sounds when segmenting."],
 pa=dict(blend=["/k/ /w/ /ĭ/ /t/ (quit)","/k/ /w/ /ĭ/ /z/ (quiz)","/k/ /w/ /ĭ/ /l/ /t/ (quilt)","/k/ /w/ /ĕ/ /s/ /t/ (quest)"], segment=["quip (/k/ /w/ /ĭ/ /p/)","quid (/k/ /w/ /ĭ/ /d/)","squid (/s/ /k/ /w/ /ĭ/ /d/)","quits (/k/ /w/ /ĭ/ /t/ /s/)"]),
 bd=dict(chain="quit → quip → quid → squid → quilt → quest → quests → quits", grid=dict(initial=["qu","squ","j","w","y","fl","b"], medial=["a","e","i","o","u"], final=["t","p","d","z","lt","st","ts"])),
 intro=["Today we are learning about the letters QU. The letter Q is always followed by the letter U. Together QU spells the sounds /k/ /w/, like at the beginning of quilt.",
        "QU comes at the beginning of a word, such as quiz and quilt. It can also come after S, such as squid."],
 gesture="Say /k/ then /w/ quickly: /kw/. Pop the back of your tongue for /k/, then round your lips for /w/. Watch me /kw/. You try /kw/.",
 soundwall="Add 'qu' under /k/ and /w/ with a note that it spells both sounds.", formation="Practise letter formation for uppercase Q and lowercase q.",
 spell=dict(ido=["quit"], wedo=["quest","quilt","squid"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="quit → quip → quid → squid → quilt → quit"),
 text_spell=["Do not quit the quest.","The squid is on the quilt.","Quin went on a quest."],
 chains=[["Onset-Rime Level: -it","quit → hit → sit → fit"],["Phoneme Level: Intro Lesson","quit → quip → quid → squid → quilt → quit"]],
 hf=dict(dolch=[], fry=[]), lists={"qu /kw/":["quit","quilt","quest","quip","quid","squid","quits","quest","Quin","quilts"]})
P["33"] = dict(tag="The grapheme V spells /v/",
 notes=["English words do not end in v on its own - a silent e is added (give, have). That is why have is a heart word for now."],
 pa=dict(blend=["/v/ /ă/ /n/ (van)","/v/ /ĕ/ /t/ (vet)","/v/ /ĕ/ /s/ /t/ (vest)","/v/ /ĕ/ /n/ /t/ (vent)"], segment=["vat (/v/ /ă/ /t/)","vend (/v/ /ĕ/ /n/ /d/)","vim (/v/ /ĭ/ /m/)","Val (/v/ /ă/ /l/)"]),
 bd=dict(chain="van → vat → vet → vest → vent → vend → bend → bent → best → vest", grid=dict(initial=["v","qu","x","w","j","b","n"], medial=["a","e","i","o","u"], final=["n","t","st","nt","nd","m"])),
 intro=["Today we are learning about the letter V. V is a consonant. The letter V spells the /v/ sound like at the beginning of volcano.",
        "V comes at the beginning of a word, such as van and vet. V does not come at the very end of a word - English words add an e after v (have, give)."],
 gesture="To make the /v/ sound as in 'volcano', put your top teeth on your bottom lip and let the air out with your voice on... (model). It is like /f/ with the voice on. /v/ is a continuous sound. Watch me /vvv/. You try /vvv/.",
 soundwall="Add 'v' under /v/ (teeth on lip).", formation="Practise letter formation for uppercase V and lowercase v.",
 spell=dict(ido=["van"], wedo=["vet","vest","vent"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="van → vat → vet → vest → vent → vend"),
 text_spell=["The vet has a van.","Val got a red vest.","What did the vet do?"],
 chains=[["Onset-Rime Level: -et","vet → jet → wet → yet"],["Onset-Rime Level: -est","vest → best → rest → west"],["Phoneme Level: Intro Lesson","van → vat → vet → vest → vent → vend"]],
 hf=dict(dolch=["have","what"], fry=["have","what"]), lists={"v /v/":["van","vat","vet","vest","vent","vend","vim","Val","Vic","Vin"]})
P["34"] = dict(tag="The grapheme Z spells /z/",
 notes=["If a word has a short vowel followed by /z/, the /z/ is usually spelled zz (buzz). This is introduced in Lesson 42 (FLSZ rule)."],
 pa=dict(blend=["/z/ /ĭ/ /p/ (zip)","/z/ /ă/ /p/ (zap)","/z/ /ĕ/ /s/ /t/ (zest)","/k/ /w/ /ĭ/ /z/ (quiz)"], segment=["zit (/z/ /ĭ/ /t/)","zen (/z/ /ĕ/ /n/)","zig (/z/ /ĭ/ /g/)","zag (/z/ /ă/ /g/)"]),
 bd=dict(chain="zip → zap → zag → zig → zit → zest → best → vest → quest → quiz", grid=dict(initial=["z","v","qu","j","w","b","y"], medial=["a","e","i","o","u"], final=["p","g","t","st","n","z"])),
 intro=["Today we are learning about the letter Z. Z is a consonant. The letter Z spells the /z/ sound like at the beginning of zip. We already know that S can spell /z/ too (is, dogs).",
        "Z comes at the beginning of a word, such as zip and zap. Z also comes at the end of a few words, such as quiz."],
 gesture="To make the /z/ sound as in 'zip', put your teeth together, keep your lips open and buzz with your voice on... (model). It is like /s/ with the voice on. /z/ is a continuous sound. Watch me /zzz/. You try /zzz/.",
 soundwall="Add 'z' under /z/ next to 's'.", formation="Practise letter formation for uppercase Z and lowercase z.",
 spell=dict(ido=["zip"], wedo=["zap","zest","quiz"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="zip → zap → zag → zig → zit → zest"),
 text_spell=["Zed can zip the bag.","Zap the bug!","Did you do the quiz yet?"],
 chains=[["Onset-Rime Level: -ip","zip → hip → lip → tip"],["Phoneme Level: Intro Lesson","zip → zap → zag → zig → zit → zest"]],
 hf=dict(dolch=[], fry=[]), lists={"z /z/":["zip","zap","zag","zig","zit","zen","zest","quiz","Zed","Zag","Zig"]})
# ---- review lessons 35a-41c ----
def _rev(tag, notes, blend, seg, chain, grid, intro, spell, ww, sents, chains, lists, hf=None):
    return dict(tag=tag, notes=notes, pa=dict(blend=blend, segment=seg), bd=dict(chain=chain, grid=grid), intro=intro,
                gesture="Review the articulatory gestures for the short vowel(s) in this lesson using the vowel valley.", soundwall="No new grapheme.", formation=None,
                spell=spell, ww=ww, text_spell=sents, chains=chains, hf=hf or dict(dolch=[], fry=[]), lists=lists)
G5 = dict(initial=["m","s","t","p","f","n","d","c","g","b","k","h","r","l","w","j","v","z"], medial=["a","e","i","o","u"], final=["t","p","m","n","d","g","b","s","x"])
P["35a"] = _rev("Short A review: VC and CVC words", ["Review lesson. Choose 35a, 35b, 35c or all three depending on the student's needs."],
 ["/s/ /ă/ /t/ (sat)","/h/ /ă/ /d/ (had)","/k/ /ă/ /t/ (cat)","/b/ /ă/ /g/ (bag)"], ["map (/m/ /ă/ /p/)","sad (/s/ /ă/ /d/)","has (/h/ /ă/ /z/)","tag (/t/ /ă/ /g/)"],
 "sat → mat → hat → had → bad → bag → tag → tap → map → cap → cat", dict(initial=["s","m","h","b","t","c","d","g","p","f","n"], medial=["a"], final=["t","d","g","p","s","m","n"]),
 ["We are reviewing the short vowel A. A spells /ă/ as in apple. Say each sound, then blend: /s/ /ă/ /t/, sat."], dict(ido=["had"], wedo=["cat","bag","map"]),
 dict(type="Word Work with Manipulative Letters", chain="sat → mat → hat → had → bad → bag → tag → tap → map → cap → cat"),
 ["The cat has a hat.","Dad had a big bag.","Sam sat on the mat."], [["Onset-Rime Level: -at","cat → hat → mat → sat → bat"],["Onset-Rime Level: -ag","bag → tag → rag → wag"]],
 {"a /ă/":["sat","at","as","mat","sad","map","had","has","cat","bad","bag","tag","hat","dad","gas","tap","cap","jam","van","wag"]})
P["35b"] = _rev("Nasalized A review: -am and -an", ["Review of Lesson 11. When /ă/ comes before /m/ or /n/ it sounds nasal (am, an)."],
 ["/j/ /ă/ /m/ (jam)","/k/ /ă/ /n/ (can)","/h/ /ă/ /m/ (ham)","/r/ /ă/ /n/ (ran)"], ["Sam (/s/ /ă/ /m/)","fan (/f/ /ă/ /n/)","dam (/d/ /ă/ /m/)","man (/m/ /ă/ /n/)"],
 "am → ham → jam → ram → ran → man → pan → can → fan → van → Dan → dam", dict(initial=["h","j","r","m","p","c","f","v","d","s","t"], medial=["a"], final=["m","n","d","t","p"]),
 ["We are reviewing nasalized A. When A is followed by M or N, the vowel sounds a little different: am, an. Read the -am and -an chunks quickly."], dict(ido=["jam"], wedo=["can","man","fan"]),
 dict(type="Word Work with Manipulative Letters", chain="am → ham → jam → ram → ran → man → pan → can → fan → van → Dan"),
 ["I am Dan.","The man has a fan.","Sam and Pam ran to the van."], [["Onset-Rime Level: -am","am → ham → jam → ram → Sam"],["Onset-Rime Level: -an","an → can → fan → man → pan → ran → van"]],
 {"-am":["am","ham","jam","ram","Sam","Pam","dam","yam","clam","slam","swam"],"-an":["an","can","fan","man","pan","ran","van","tan","Dan","plan","clan"]})
P["35c"] = _rev("Short A advanced: words with consonant clusters", ["Review of short A in longer words (CCVC, CVCC, CCVCC). Segment every consonant in a cluster."],
 ["/f/ /l/ /ă/ /t/ (flat)","/p/ /l/ /ă/ /n/ /t/ (plant)","/d/ /r/ /ă/ /g/ (drag)","/h/ /ă/ /n/ /d/ (hand)"], ["lamp (/l/ /ă/ /m/ /p/)","snap (/s/ /n/ /ă/ /p/)","fact (/f/ /ă/ /k/ /t/)","camp (/k/ /ă/ /m/ /p/)"],
 "at → hat → had → hand → band → land → lamp → camp → clamp → clap → flap → flat → flag → drag", dict(initial=["h","b","l","c","cl","fl","dr","sn","pl","tr","st"], medial=["a"], final=["t","d","nd","mp","p","g","ct","st"]),
 ["We are reviewing short A in longer words. Some words have two consonants together at the start or the end: f-l-a-t, l-a-m-p. Say every sound, then blend."], dict(ido=["flat"], wedo=["plant","hand","drag","lamp"]),
 dict(type="Word Work with Manipulative Letters", chain="at → hat → had → hand → band → land → lamp → camp → clamp → clap → flap → flat → flag"),
 ["Stan had a flat hat.","The plant is in the sand.","Brad can clap and stamp."], [["Onset-Rime Level: -amp","camp → lamp → damp → stamp → clamp"],["Onset-Rime Level: -and","hand → band → land → sand → stand"]],
 {"a /ă/ clusters":["flat","plant","hand","lamp","drag","fact","snap","camp","clap","stamp","stand","grand","brand","blast","glad","flag","trap","crab","past","last"]})
P["36a"] = _rev("Short I review: VC and CVC words", ["Review lesson for short I."],
 ["/s/ /ĭ/ /t/ (sit)","/h/ /ĭ/ /m/ (him)","/b/ /ĭ/ /g/ (big)","/d/ /ĭ/ /d/ (did)"], ["in (/ĭ/ /n/)","six (/s/ /ĭ/ /k/ /s/)","win (/w/ /ĭ/ /n/)","pig (/p/ /ĭ/ /g/)"],
 "it → sit → hit → him → dim → did → dig → big → bin → win → wig → pig → pin", dict(initial=["s","h","d","b","w","p","f","t","l","r","k"], medial=["i"], final=["t","m","d","g","n","x","p"]),
 ["We are reviewing the short vowel I. I spells /ĭ/ as in itch. Keep your mouth in a small smile for /ĭ/."], dict(ido=["big"], wedo=["six","him","did"]),
 dict(type="Word Work with Manipulative Letters", chain="it → sit → hit → him → dim → did → dig → big → bin → win → wig → pig"),
 ["The pig is big.","Did Sid win?","I see six kids."], [["Onset-Rime Level: -it","it → sit → hit → fit → bit"],["Onset-Rime Level: -ig","big → dig → pig → wig → fig"]],
 {"i /ĭ/":["in","six","it","if","sit","win","him","big","did","hit","pig","dig","fig","lid","bin","fin","kid","lip","rip","zip"]})
P["36b"] = _rev("Short I advanced: words with consonant clusters", ["Review of short I in longer words (CCVC, CVCC)."],
 ["/f/ /l/ /ĭ/ /p/ (flip)","/t/ /w/ /ĭ/ /n/ (twin)","/l/ /ĭ/ /s/ /t/ (list)","/s/ /k/ /ĭ/ /n/ (skin)"], ["trip (/t/ /r/ /ĭ/ /p/)","wind (/w/ /ĭ/ /n/ /d/)","gift (/g/ /ĭ/ /f/ /t/)","slid (/s/ /l/ /ĭ/ /d/)"],
 "sip → slip → slid → slit → split → spit → spin → skin → skip → skid → slid → slim → swim", dict(initial=["s","sl","sp","sk","sw","tr","fl","dr","gr","tw"], medial=["i"], final=["p","d","t","n","m","st","ft","nd"]),
 ["We are reviewing short I in longer words with consonant clusters: s-l-i-p, l-i-s-t. Say every sound, then blend."], dict(ido=["flip"], wedo=["list","skin","twin","gift"]),
 dict(type="Word Work with Manipulative Letters", chain="sip → slip → slid → slit → split → spit → spin → skin → skip → skid"),
 ["Lin can do a flip.","The gift is a list of trips.","Did the twins skip and spin?"], [["Onset-Rime Level: -ip","slip → skip → trip → flip → drip"],["Onset-Rime Level: -ist","list → fist → mist → twist"]],
 {"i /ĭ/ clusters":["flip","twin","list","skin","trip","wind","gift","slid","spin","skip","split","fist","mist","lift","milk","drift","grin","print","crisp","swift"]})
P["37a"] = _rev("Short O review: VC and CVC words", ["Review lesson for short O."],
 ["/h/ /ŏ/ /t/ (hot)","/m/ /ŏ/ /p/ (mop)","/j/ /ŏ/ /b/ (job)","/f/ /ŏ/ /k/ /s/ (fox)"], ["on (/ŏ/ /n/)","lot (/l/ /ŏ/ /t/)","got (/g/ /ŏ/ /t/)","dog (/d/ /ŏ/ /g/)"],
 "on → hot → hop → mop → top → pop → pot → dot → dog → log → lot → not → nod → rod", dict(initial=["h","m","t","p","d","l","n","r","j","f","c"], medial=["o"], final=["n","t","p","g","d","b","x"]),
 ["We are reviewing the short vowel O. O spells /ŏ/ as in octopus. Open your mouth round and wide for /ŏ/."], dict(ido=["hot"], wedo=["job","mop","fox"]),
 dict(type="Word Work with Manipulative Letters", chain="on → hot → hop → mop → top → pop → pot → dot → dog → log → lot → not"),
 ["The fox is on the log.","Tom got a hot pot.","Can the dog hop on top?"], [["Onset-Rime Level: -op","hop → mop → top → pop → cop"],["Onset-Rime Level: -ot","hot → pot → dot → lot → not → got"]],
 {"o /ŏ/":["not","on","mob","lot","fox","hot","job","got","top","dog","hop","mop","pot","dot","log","rod","cod","box","fog","jog"]})
P["37b"] = _rev("Short O advanced: words with consonant clusters", ["Review of short O in longer words."],
 ["/s/ /t/ /ŏ/ /p/ (stop)","/f/ /r/ /ŏ/ /g/ (frog)","/l/ /ŏ/ /s/ /t/ (lost)","/p/ /ŏ/ /n/ /d/ (pond)"], ["spot (/s/ /p/ /ŏ/ /t/)","soft (/s/ /ŏ/ /f/ /t/)","drop (/d/ /r/ /ŏ/ /p/)","plot (/p/ /l/ /ŏ/ /t/)"],
 "hop → shop* → stop → spot → slot → plot → plod → prod → prom → from → frog → fog → fond → pond → bond", dict(initial=["st","sp","sl","pl","pr","fr","dr","cr","tr","bl"], medial=["o"], final=["p","t","d","m","g","nd","st","ft"]),
 ["We are reviewing short O in longer words with consonant clusters: s-t-o-p, l-o-s-t. Say every sound, then blend."], dict(ido=["stop"], wedo=["frog","lost","pond","spot"]),
 dict(type="Word Work with Manipulative Letters", chain="hop → stop → spot → slot → plot → plod → prod → prom → from → frog → fog → fond → pond"),
 ["The frog lost the spot.","Stop at the pond.","Did Dom drop the soft blob?"], [["Onset-Rime Level: -op","stop → drop → crop → plop → prop"],["Onset-Rime Level: -ond","pond → bond → fond → blond"]],
 {"o /ŏ/ clusters":["stop","frog","lost","pond","spot","soft","drop","plot","cost","blob","clog","trot","prom","from","fond","blond","crop","slot","stomp","frost"]})
P["38a"] = _rev("Short A, I, O review", ["Review of three short vowels. Contrast the mouth positions: /ă/ wide, /ĭ/ small smile, /ŏ/ round."],
 ["/m/ /ă/ /p/ (map)","/h/ /ĭ/ /m/ (him)","/j/ /ŏ/ /b/ (job)","/s/ /ă/ /t/ (sat)"], ["had (/h/ /ă/ /d/)","sit (/s/ /ĭ/ /t/)","not (/n/ /ŏ/ /t/)","six (/s/ /ĭ/ /k/ /s/)"],
 "sat → sit → sip → sop → top → tip → tap → map → mop → hop → hip → hat → hot", dict(initial=["s","t","m","h","p","d","b","l","r","n","f"], medial=["a","i","o"], final=["t","p","d","g","n","m","b","x"]),
 ["We are reviewing the short vowels A, I and O. Look at the vowel first, think of its sound, then say each sound and blend."], dict(ido=["map"], wedo=["him","job","sat","not"]),
 dict(type="Word Work with Manipulative Letters", chain="sat → sit → sip → sop → top → tip → tap → map → mop → hop → hip → hat → hot"),
 ["The man sat on a big log.","I got a hat and a pin.","Did the dog sit on the mat?"], [["Phoneme Level: Vowel Changes","hat → hit → hot, pat → pit → pot, bag → big → bog"]],
 {"a, i, o":["at","map","is","him","on","job","sat","had","and","man","if","sit","his","six","not","got","lot","top","pin","fog"]})
P["38b"] = _rev("Short A, I, O advanced: consonant clusters", ["Review of a, i, o in longer words."],
 ["/f/ /l/ /ă/ /p/ (flap)","/s/ /p/ /ŏ/ /t/ (spot)","/w/ /ĭ/ /n/ /d/ (wind)","/t/ /r/ /ă/ /p/ (trap)"], ["land (/l/ /ă/ /n/ /d/)","kids (/k/ /ĭ/ /d/ /z/)","stop (/s/ /t/ /ŏ/ /p/)","lamp (/l/ /ă/ /m/ /p/)"],
 "trap → trip → drip → drop → crop → clop → clip → clap → flap → flip → flop → plop → plod → plan", dict(initial=["tr","dr","cr","cl","fl","pl","sp","st","sl","gr"], medial=["a","i","o"], final=["p","d","n","t","nd","mp","st","ft"]),
 ["We are reviewing a, i and o in longer words with consonant clusters. Say every sound, then blend: f-l-a-p, flap."], dict(ido=["trap"], wedo=["spot","wind","lamp","skip"]),
 dict(type="Word Work with Manipulative Letters", chain="trap → trip → drip → drop → crop → clop → clip → clap → flap → flip → flop → plop"),
 ["The kids skip to the pond.","Stan can not stop the drip.","Brad got a lamp and a clock*."], [["Phoneme Level: Vowel Changes","flap → flip → flop, clap → clip → clop, stamp → stump"]],
 {"a, i, o clusters":["flap","land","wind","spot","trap","lamp","hand","kids","skip","stop","clip","crisp","drop","frost","grand","plant","print","split","stamp","twist"]})
P["39a"] = _rev("Short U review: VC and CVC words", ["Review lesson for short U."],
 ["/k/ /ŭ/ /p/ (cup)","/f/ /ŭ/ /n/ (fun)","/m/ /ŭ/ /d/ (mud)","/b/ /ŭ/ /s/ (bus)"], ["up (/ŭ/ /p/)","run (/r/ /ŭ/ /n/)","cut (/k/ /ŭ/ /t/)","sun (/s/ /ŭ/ /n/)"],
 "up → cup → cut → nut → hut → hug → bug → bun → sun → fun → fin* → run → rug → mug → mud", dict(initial=["c","n","h","b","s","f","r","m","p","t","g"], medial=["u"], final=["p","t","g","n","d","s","m","b"]),
 ["We are reviewing the short vowel U. U spells /ŭ/ as in up. Keep your mouth relaxed and open a little for /ŭ/."], dict(ido=["cup"], wedo=["fun","mud","bus"]),
 dict(type="Word Work with Manipulative Letters", chain="up → cup → cut → nut → hut → hug → bug → bun → sun → fun → run → rug → mug → mud"),
 ["The pup dug in the mud.","Gus is on the bus.","Mum cut up the bun."], [["Onset-Rime Level: -ug","bug → hug → mug → rug → tug → dug"],["Onset-Rime Level: -un","bun → fun → run → sun → gun"]],
 {"u /ŭ/":["cup","mum","up","us","fun","mud","run","but","sun","cut","bus","bug","hug","hut","nut","rug","tug","dug","gum","bud"]})
P["39b"] = _rev("Short U advanced: consonant clusters", ["Review of short U in longer words."],
 ["/s/ /l/ /ŭ/ /g/ (slug)","/j/ /ŭ/ /m/ /p/ (jump)","/p/ /l/ /ŭ/ /g/ (plug)","/d/ /ŭ/ /s/ /k/ (dusk)"], ["must (/m/ /ŭ/ /s/ /t/)","hunt (/h/ /ŭ/ /n/ /t/)","drum (/d/ /r/ /ŭ/ /m/)","stump (/s/ /t/ /ŭ/ /m/ /p/)"],
 "bug → slug → plug → plum → drum → dump → jump → bump → bum* → hum → hunt → hut → shut*", dict(initial=["sl","pl","dr","j","b","h","st","cr","tr","gr"], medial=["u"], final=["g","m","mp","nt","t","st","sk","nd"]),
 ["We are reviewing short U in longer words with consonant clusters: s-l-u-g, j-u-m-p. Say every sound, then blend."], dict(ido=["slug"], wedo=["jump","must","plug","hunt"]),
 dict(type="Word Work with Manipulative Letters", chain="bug → slug → plug → plum → drum → dump → jump → bump → hump → hunt"),
 ["The slug is on the stump.","Gus must jump on the trunk.","Just dust the drum."], [["Onset-Rime Level: -ump","jump → bump → dump → lump → stump"],["Onset-Rime Level: -ust","must → just → dust → rust → trust"]],
 {"u /ŭ/ clusters":["slug","dusk","plug","must","jump","just","hunt","drum","dump","bump","lump","stump","trust","crust","grunt","blunt","plus","club","stun","trunk*"]})
P["40a"] = _rev("Short E review: VC and CVC words", ["Review lesson for short E. Contrast /ĕ/ and /ĭ/ carefully."],
 ["/h/ /ĕ/ /n/ (hen)","/l/ /ĕ/ /t/ (let)","/r/ /ĕ/ /d/ (red)","/b/ /ĕ/ /d/ (bed)"], ["yes (/y/ /ĕ/ /s/)","set (/s/ /ĕ/ /t/)","get (/g/ /ĕ/ /t/)","ten (/t/ /ĕ/ /n/)"],
 "bed → red → fed → led → let → get → jet → wet → pet → pen → ten → hen → men → met", dict(initial=["b","r","f","l","g","j","w","p","t","h","m","n","s"], medial=["e"], final=["d","t","n","g","s","b"]),
 ["We are reviewing the short vowel E. E spells /ĕ/ as in edge. Open your mouth a little wider than for /ĭ/."], dict(ido=["hen"], wedo=["let","red","bed"]),
 dict(type="Word Work with Manipulative Letters", chain="bed → red → fed → led → let → get → jet → wet → pet → pen → ten → hen → men"),
 ["The hen sat on the bed.","Let Ben get the pet.","I fed ten red hens."], [["Onset-Rime Level: -et","get → let → met → net → pet → set → wet → jet"],["Onset-Rime Level: -en","hen → men → pen → ten → den"]],
 {"e /ĕ/":["hen","let","yes","set","get","ten","pet","red","bed","men","fed","led","jet","wet","net","pen","den","leg","peg","web"]})
P["40b"] = _rev("Short E advanced: consonant clusters", ["Review of short E in longer words."],
 ["/w/ /ĕ/ /s/ /t/ (west)","/h/ /ĕ/ /l/ /p/ (help)","/s/ /l/ /ĕ/ /d/ (sled)","/n/ /ĕ/ /k/ /s/ /t/ (next)"], ["rest (/r/ /ĕ/ /s/ /t/)","step (/s/ /t/ /ĕ/ /p/)","send (/s/ /ĕ/ /n/ /d/)","left (/l/ /ĕ/ /f/ /t/)"],
 "bed → bled → sled → slept → step → stem → stems → tens → tent → dent → dents → rest → best → nest → next", dict(initial=["bl","sl","st","fl","dr","tr","sp","gr","cr","sw"], medial=["e"], final=["d","pt","p","m","nt","st","ft","nd","xt"]),
 ["We are reviewing short E in longer words with consonant clusters: w-e-s-t, h-e-l-p. Say every sound, then blend."], dict(ido=["west"], wedo=["help","sled","next","step"]),
 dict(type="Word Work with Manipulative Letters", chain="bed → bled → sled → slept → step → stem → stems → tens → tent → dent → rest → best → nest → next"),
 ["Fred slept in the tent.","Send help to the west.","Did Jen step on the sled?"], [["Onset-Rime Level: -est","best → nest → rest → test → west → vest"],["Onset-Rime Level: -end","send → bend → lend → mend → tend"]],
 {"e /ĕ/ clusters":["west","help","sled","next","rest","step","send","left","tent","best","nest","bend","mend","dress*","fled","slept","spend","trend","crept","stem"]})
P["41a"] = _rev("Short vowels review (all five)", ["Review of all five short vowels in VC and CVC words."],
 ["/m/ /ă/ /t/ (mat)","/s/ /ĭ/ /t/ (sit)","/n/ /ŏ/ /t/ (not)","/m/ /ŭ/ /d/ (mud)"], ["let (/l/ /ĕ/ /t/)","six (/s/ /ĭ/ /k/ /s/)","job (/j/ /ŏ/ /b/)","run (/r/ /ŭ/ /n/)"],
 "hat → hit → hot → hut → hug → hog → hag → bag → beg → big → bog → bug → bud → bed → bad", dict(initial=["h","b","m","s","t","p","d","l","r","n","g"], medial=["a","e","i","o","u"], final=["t","g","d","p","n","m","b","s"]),
 ["We are reviewing all five short vowels. Every word has a vowel. Look at the vowel, think of its sound, then say each sound and blend."], dict(ido=["mat"], wedo=["sit","not","mud","let"]),
 dict(type="Word Work with Manipulative Letters", chain="hat → hit → hot → hut → hug → hog → hag → bag → beg → big → bog → bug → bud → bed → bad"),
 ["I have a red hen and a pig.","He was not on the bus.","Can you see the big dog?"], [["Phoneme Level: Vowel Changes","bat → bet → bit → bot → but, pan → pen → pin → pun"]],
 {"short vowels":["mat","sit","not","mud","let","sat","had","can","six","fit","on","got","job","us","run","red","ten","bug","hen","lip"]})
P["41b"] = _rev("Short vowels advanced 1: consonant clusters", ["Review of all short vowels in CCVC and CVCC words."],
 ["/m/ /ŭ/ /s/ /t/ (must)","/b/ /ĕ/ /n/ /d/ (bend)","/s/ /p/ /ŏ/ /t/ (spot)","/l/ /ĭ/ /f/ /t/ (lift)"], ["hand (/h/ /ă/ /n/ /d/)","slip (/s/ /l/ /ĭ/ /p/)","drop (/d/ /r/ /ŏ/ /p/)","step (/s/ /t/ /ĕ/ /p/)"],
 "slip → slap → slam → slim → slid → slug → snug → snag → snap → snip → spin → spun → spot → spit", dict(initial=["sl","sn","sp","st","dr","tr","fl","cl","gr","br"], medial=["a","e","i","o","u"], final=["p","m","d","g","n","t","st","nd","mp","ft"]),
 ["We are reviewing all short vowels in longer words with consonant clusters. Say every sound, then blend: s-l-i-p, slip; m-u-s-t, must."], dict(ido=["must"], wedo=["bend","spot","lift","hand"]),
 dict(type="Word Work with Manipulative Letters", chain="slip → slap → slam → slim → slid → slug → snug → snag → snap → snip → spin → spun → spot"),
 ["Tom can do a flip and a spin.","You have the best spot to rest.","What did Mum and Dad send?"], [["Phoneme Level: Vowel Changes","slip → slap → slop, spin → span → spun, drip → drop"]],
 {"clusters":["must","bend","cats","lost","hand","fits","lift","slip","lots","spot","drop","runs","jump","dust","end","best","step","plan","trust","stamp"]})
P["41c"] = _rev("Short vowels advanced 2: CCCVC, CCVCC and CCCVCC words", ["Review of all short vowels in the longest one-syllable words (split, sprint, strand)."],
 ["/t/ /r/ /ŭ/ /s/ /t/ (trust)","/s/ /p/ /ĕ/ /n/ /t/ (spent)","/s/ /p/ /l/ /ĭ/ /t/ (split)","/f/ /r/ /ŏ/ /s/ /t/ (frost)"], ["stand (/s/ /t/ /ă/ /n/ /d/)","sprint (/s/ /p/ /r/ /ĭ/ /n/ /t/)","blend (/b/ /l/ /ĕ/ /n/ /d/)","scrub (/s/ /k/ /r/ /ŭ/ /b/)"],
 "spit → split → splint → sprint → print → prints → punts → stunts → stunt → stint → stilt → still* → spilt → split", dict(initial=["spl","spr","str","scr","st","sp","pr","bl","tr","gr"], medial=["a","e","i","o","u"], final=["t","nt","nts","lt","nd","st","mp","sk"]),
 ["We are reviewing the longest short-vowel words: some start with three consonants (s-p-l-i-t) and some end with two (s-t-a-n-d). Say every sound - do not skip any."], dict(ido=["trust"], wedo=["spent","split","frost","stand"]),
 dict(type="Word Work with Manipulative Letters", chain="spit → split → splint → sprint → print → prints → punts → stunts → stunt → stint → stilt → spilt"),
 ["Can you get the crust?","Stand next to the plants.","Stan and Ben are the best at sprints."], [["Phoneme Level: Add a sound","pit → spit → split → splint, and → sand → stand → strand"]],
 {"CCCVC / CCVCC":["bland","scrub","grand","stand","swift","twist","frost","stunt","crust","spend","blend","scrap","strip","sprint","strand","split","splint","struck*","script","strict"]})
