# Lesson plan data, lessons 63-83 (incl. 67a, 67b, 77AUS, 80AUS)
P = {}
INIT = ["b","c","d","f","g","h","j","k","l","m","n","p","r","s","t","v","w","y","z","bl","cl","fl","sl","br","cr","dr","fr","gr","tr","sk","sn","sp","st","sw","sh","ch","th","wh"]
def g(final, medial=None, init=None):
    return dict(initial=init or INIT, medial=medial or ["a","e","i","o","u"], final=final)
P["63"] = dict(tag="The suffix -es",
 notes=["Add -es (not -s) after words ending in s, x, z, sh, ch, ss: box → boxes, dish → dishes. The suffix -es adds a syllable: /ĕz/ or /əz/.",
        "-es also changes verbs: he fixes, she wishes."],
 pa=dict(blend=["/b/ /ŏ/ /k/ /s/ /ĕz/ (boxes)","/d/ /ĭ/ /sh/ /ĕz/ (dishes)","/b/ /ŭ/ /s/ /ĕz/ (buses)","/l/ /ŭ/ /n/ /ch/ /ĕz/ (lunches)"], segment=["foxes (fox-es)","wishes (wish-es)","ashes (ash-es)","inches (inch-es)"]),
 bd=dict(chain="box → boxes → foxes → fixes → mixes → misses → kisses → hisses → wishes → dishes → fishes → fetches* → catches*", grid=g(["es","xes","shes","ches","sses","s"])),
 intro=["We learned that the suffix -s makes nouns plural (more than one) and changes verbs (he runs). Today we learn the suffix -es. When a word ends in s, x, z, sh or ch, we add -es instead of -s: one box, two boxes; one dish, two dishes.",
        "-es adds a new syllable to the word: box-es, dish-es. Listen: /bŏks/ /ĕz/. We also add -es to verbs: I wish, she wishes; I fix, he fixes."],
 gesture="No new sound. Notice that -es is a whole syllable: /ĕz/.", soundwall="Add '-es' as a suffix card.", formation=None,
 spell=dict(ido=["boxes"], wedo=["dishes","buses","lunches","wishes"]),
 ww=dict(type="Word Work with Writing (add -s or -es)", chain="box → boxes, dish → dishes, cat → cats, bus → buses, lunch → lunches, fix → fixes, dog → dogs, wish → wishes, dress → dresses"),
 text_spell=["He has to scrub the two dishes.","Which one of the buses is mine?","Does Phil have the boxes?"],
 chains=[["Morpheme Level: add -es","box → boxes, fox → foxes, dish → dishes, wish → wishes, bench → benches, dress → dresses, buzz → buzzes"],["Morpheme Level: -s or -es?","cats, boxes, dogs, dishes, hats, lunches, bugs, kisses"]],
 hf=dict(dolch=["two","does"], fry=["two","does"]), lists={"-es":["boxes","dresses","foxes","ashes","inches","buses","gases","lunches","lashes","dishes","kisses","wishes","fixes","mixes","benches","brushes","classes","glasses","matches*","patches*"]})
P["64"] = dict(tag="The suffix -ed",
 notes=["-ed makes a verb past tense. It spells three sounds: /t/ after quiet sounds (jumped), /d/ after voiced sounds (called), /əd/ after t or d (rested, landed). Students spell -ed for all three.",
        "Today's words are base words that do not change spelling. The doubling rule (stop → stopped) and drop-e rule come in Lessons 107 and 109."],
 pa=dict(blend=["/y/ /ĕ/ /l/ /d/ (yelled)","/j/ /ŭ/ /m/ /p/ /t/ (jumped)","/r/ /ĕ/ /s/ /t/ /əd/ (rested)","/f/ /ĭ/ /l/ /d/ (filled)"], segment=["asked (/ar/ /s/ /k/ /t/)","called (/k/ /orl/ /d/)","ended (end-ed)","handed (hand-ed)"]),
 bd=dict(chain="jump → jumped → bumped → dumped → dusted → rusted → rested → tested → nested → melted → yelled → filled → called", grid=g(["ed","ped","ted","led","ded","sted","mped"])),
 intro=["Today we will learn the suffix -ed. When we add -ed to an action word (a verb), it means the action already happened - in the past. Today I jump. Yesterday I jumped.",
        "-ed can sound three ways. After quiet sounds it says /t/: jumped, asked. After noisy sounds it says /d/: yelled, called. After /t/ or /d/ it says /əd/ and adds a syllable: rested, handed.",
        "No matter how it sounds, we spell it e-d. When you read a word that ends in -ed, cover the -ed, read the base word, then add the ending."],
 gesture="Compare /t/ (voice off) and /d/ (voice on) with a hand on the throat.", soundwall="Add '-ed' under /t/, /d/ and /əd/.", formation=None,
 spell=dict(ido=["jumped"], wedo=["yelled","rested","filled","asked"]),
 ww=dict(type="Word Work with Writing (add -ed)", chain="jump → jumped, yell → yelled, rest → rested, fill → filled, ask → asked, land → landed, call → called, wish → wished, hand → handed"),
 text_spell=["They planted kale and then rested.","He splashed but did not get wet.","Many kids yelled and jumped."],
 chains=[["Morpheme Level: -ed /t/","jumped, asked, wished, kicked, camped, fished, helped, packed"],["Morpheme Level: -ed /d/","yelled, filled, called, smelled, spilled, buzzed, hugged*"],["Morpheme Level: -ed /əd/","rested, ended, handed, landed, tested, melted, dusted, lifted"]],
 hf=dict(dolch=["many","any"], fry=["many","any"]), lists={"-ed /t/":["smashed","asked","crashed","rocked","jumped","kicked","fished","wished","helped","packed","camped"],"-ed /d/":["yelled","filled","called","smelled","spilled","thanked*","buzzed","filmed"],"-ed /əd/":["rested","ended","handed","landed","wanted","tested","melted","lifted","dusted"]})
P["65"] = dict(tag="The suffix -ing",
 notes=["-ing means the action is happening now, often with a helping verb (I am going, he is going, they were going). Today's base words do not change spelling. Doubling rule is Lesson 107; drop-e rule is Lesson 109."],
 pa=dict(blend=["/r/ /ĕ/ /s/ /t/ /ĭ/ /ŋ/ (resting)","/f/ /ĭ/ /sh/ /ĭ/ /ŋ/ (fishing)","/ar/ /s/ /k/ /ĭ/ /ŋ/ (asking)","/th/ /ĭ/ /ŋ/ /k/ /ĭ/ /ŋ/ (thinking)"], segment=["going (go-ing)","pulling (pull-ing)","bending (bend-ing)","planting (plant-ing)"]),
 bd=dict(chain="jump → jumping → bumping → dumping → dusting → resting → testing → nesting → melting → yelling → filling → calling → falling", grid=g(["ing","ping","ting","ling","ding","sting"])),
 intro=["Today we will learn the suffix -ing. When we add -ing to a verb, it tells us the action is happening now, or is going on: I am jumping. She is reading.",
        "We often use a helping verb with -ing: am, is, are, was, were. I am going. He is going. We are going. She was going. They were going.",
        "-ing is one syllable: /ĭng/. When you read a word that ends in -ing, cover the -ing, read the base word, then add the ending: jump-ing, jumping."],
 gesture="Review /ŋ/ (tongue back, voice through the nose).", soundwall="Add '-ing' as a suffix card.", formation=None,
 spell=dict(ido=["resting"], wedo=["fishing","asking","calling","thinking"]),
 ww=dict(type="Word Work with Writing (add -ing)", chain="rest → resting, fish → fishing, ask → asking, call → calling, think → thinking, plant → planting, jump → jumping, sing → singing, help → helping"),
 text_spell=["Steve has been singing and planting.","Is Liz being kind to you?","Many kids like fishing at the pond."],
 chains=[["Morpheme Level: add -ing","rest → resting, fish → fishing, ask → asking, bend → bending, call → calling, think → thinking, go → going, be → being"],["Morpheme Level: -ed and -ing","jumped → jumping, rested → resting, called → calling, wished → wishing"]],
 hf=dict(dolch=["been","into"], fry=["been","into"]), lists={"-ing":["resting","doing","pulling","asking","bending","calling","being","fishing","planting","sticking","thinking","flashing","going","falling","helping","jumping","singing","reading*","camping","melting"]})
P["66"] = dict(tag="Closed and open syllables",
 notes=["A syllable is a word or word part with one vowel sound. A closed syllable ends in a consonant and the vowel is short (hop, kick). An open syllable ends in a vowel and the vowel is long - it says its name (go, hi, me, we, she).",
        "This lesson makes he, be, me, we, she, go, no, so decodable."],
 pa=dict(blend=["/g/ /ō/ (go)","/m/ /ē/ (me)","/h/ /ī/ (hi)","/sh/ /ē/ (she)"], segment=["we (/w/ /ē/)","no (/n/ /ō/)","met (/m/ /ĕ/ /t/)","nap (/n/ /ă/ /p/)"]),
 bd=dict(chain="be → bet → met → me → we → wet → set → so → no → not → hot → ho* → go → got", grid=g(["t","p","n","d","g","sh",""], ["a","e","i","o","u"], ["b","m","w","s","n","h","g","sh","fl","st"])),
 intro=["A syllable is a word or part of a word with one vowel sound. Clap the syllables: cat (1), rabbit (2), banana (3).",
        "A closed syllable has a vowel followed by at least one consonant. The consonant 'closes in' the vowel, and the vowel is short: hop, kick, just. All the CVC words we know are closed syllables.",
        "An open syllable ends with the vowel. Nothing closes it in, so the vowel is long - it says its name: go, hi, me, we, she, so, no. Say the sounds: /g/ /ō/, go.",
        "Knowing whether a syllable is open or closed helps us read the vowel."],
 gesture="Review the long vowel sounds /ā/ /ē/ /ī/ /ō/ /ū/ (the letter names).", soundwall="Add cards for open-syllable vowels: a /ā/, e /ē/, i /ī/, o /ō/, u /ū/ /yū/ on the vowel valley.", formation=None,
 spell=dict(ido=["go"], wedo=["me","we","no","hi"]),
 ww=dict(type="Word Sort (open / closed)", text="Read and sort the words by syllable type: open (long vowel) or closed (short vowel). Words: be, met, nap, men, go, set, hi, mash, we, dip, split, no, she, so, got, we.", chain="be → bet → met → me → we → wet → set → so → no → not → hot → go → got"),
 text_spell=["My friend and I want to go camping in June.","Have you been sticking the stamps here?","We can see the two big pigs."],
 chains=[["Phoneme Level: open/closed","be → bet, me → met, we → wet, no → not, go → got, so → sob, hi → hid"]],
 hf=dict(dolch=["he","be","me","we","she","go","no","so","friend"], fry=["he","be","me","we","she","go","no","so"]), lists={"open syllables":["be","go","hi","we","he","me","she","no","so","I","a","flu","fly*"],"closed syllables":["met","nap","men","set","mash","dip","split","got","hot","not","shut","bench"]})
P["67a"] = dict(tag="Compound words",
 notes=["A compound word is two smaller words joined to make a new word (sun + set = sunset). Reading longer words: find the two small words, read each, then put them together."],
 pa=dict(blend=["sun-set (sunset)","hot-dog (hotdog)","back-pack (backpack)","up-hill (uphill)"], segment=["sandpit (sand-pit)","bulldog (bull-dog)","cannot (can-not)","suntan (sun-tan)"]),
 bd=dict(chain="sun → sunset → sunspot → sunlit → sunhat → hat → hotdog → dog → bulldog → bullpen → pen → pigpen", grid=g(["t","g","n","p","ck","ll","sh","ch"], None, ["sun","hot","back","up","bull","pig","sand","step","hand"])),
 intro=["Today we will learn about compound words. A compound word is made of two smaller words put together: sun + set = sunset. Both small words keep their spelling and their meaning.",
        "To read a long word, look for two small words you know. Read the first word, read the second word, then blend them: back-pack, backpack. Compound words have two syllables (or more), one for each small word."],
 gesture="No new sound.", soundwall="No new grapheme.", formation=None,
 spell=dict(ido=["sunset"], wedo=["backpack","hotdog","uphill","sandpit"]),
 ww=dict(type="Word Work with Writing (build compound words)", chain="step + mum = stepmum, pin + ball = pinball, kick + off = kickoff, pick + up = pickup, sun + tan = suntan, back + pack = backpack, up + hill = uphill, sand + pit = sandpit"),
 text_spell=["He went on a long hike by himself.","My friend likes softball and kickball.","Pete got something from the sandpit."],
 chains=[["Morpheme Level: compound words","sunset, sunhat, sunlit, sunspot, suntan; backpack, backstop, backbone; hotdog, hotpot, hotshot"]],
 hf=dict(dolch=["because","into"], fry=["because"]), lists={"compound words":["hotdog","handstand","itself","cannot","uphill","backpack","bulldog","suntan","sandpit","sometimes","something","himself","stepmum","pinball","kickoff","pickup","catfish","bathtub","laptop","desktop","sunset","pigpen"]})
P["67b"] = dict(tag="Two-syllable words: closed/closed",
 notes=["Divide two-syllable words between the two consonants (VC/CV): rab-bit, den-tist. Both syllables are closed, so both vowels are short. Read each syllable, then blend them.",
        "The vowel in an unstressed syllable may sound like schwa /ə/ (second, absent). Accept the relaxed pronunciation."],
 pa=dict(blend=["den-tist (dentist)","pic-nic (picnic)","rock-et (rocket)","nap-kin (napkin)"], segment=["until (un-til)","contest (con-test)","chicken (chick-en)","subject (sub-ject)"]),
 bd=dict(chain="rabbit → rabbits → habit → cabin → cabins → napkin → napkins → catnip → picnic → dentist → contest", grid=g(["t","n","d","st","ck","ch"], None, ["rab","hab","cab","nap","cat","pic","den","con","sub","chick","tim","sev"])),
 intro=["We have been reading one-syllable words and compound words. Today we will read other two-syllable words. Look at this word: rabbit. It has two vowels with two consonants between them: r-a-b-b-i-t.",
        "We divide the word between the two consonants: rab / bit. Each part is a closed syllable, so each vowel is short. Read the first syllable: rab. Read the second syllable: bit. Blend them: rabbit.",
        "When you see a long word, find the vowels, divide between the consonants, read each syllable, then put them together."],
 gesture="No new sound.", soundwall="No new grapheme.", formation=None,
 spell=dict(ido=["dentist"], wedo=["picnic","napkin","rabbit","until"]),
 ww=dict(type="Syllable Decoding and Blending", text="Read each syllable, then blend: tim/id, rock/et, sev/en, den/tist, pic/nic, nap/kin, con/test, sub/ject, chick/en, ab/sent.", chain="rabbit → habit → cabin → napkin → catnip → picnic → dentist → contest"),
 text_spell=["You are my friend because you are kind.","We bring the lunches in a plastic bag.","Can you go into the bag and get me a napkin?"],
 chains=[["Syllable Level: closed/closed","rab-bit, hab-it, cab-in, nap-kin, cat-nip, pic-nic, den-tist, con-test, sub-ject, in-sect, bas-ket, mag-net"]],
 hf=dict(dolch=[], fry=[]), lists={"closed/closed":["until","second","absent","picnic","denim","contest","chicken","subject","children","sentence","rabbit","napkin","basket","magnet","insect","muffin","puppet","sudden","kitten","dentist","catnip","cactus","helmet","pumpkin"]})
P["68"] = dict(tag="Two-syllable words: open/closed",
 notes=["When one consonant sits between two vowels (V/CV), divide before the consonant: ro-bot, o-pen. The first syllable is open, so its vowel is long. If that does not make a real word, try dividing after the consonant (closed, short vowel): rob-in, cab-in. This flexibility is called 'set for variability'."],
 pa=dict(blend=["ro-bot (robot)","o-pen (open)","mu-sic (music)","se-cret (secret)"], segment=["basic (ba-sic)","frozen (fro-zen)","unit (u-nit)","begin (be-gin)"]),
 bd=dict(chain="robot → robin → rob → ro → rodent → basin → basic → bacon → begin → began → be → being → unit → unite", grid=g(["t","n","c","d","s","sh","ck"], None, ["ro","ba","be","u","mu","si","va","o","e","hu","se","fro"])),
 intro=["Yesterday we divided words between two consonants (rab/bit). Today we will look at words with only one consonant between the vowels, like robot: r-o-b-o-t.",
        "When there is one consonant in the middle, we usually divide before the consonant: ro / bot. The first syllable is open, so the vowel says its name: /rō/. Then read the second syllable: /bŏt/. Blend: robot.",
        "Sometimes dividing before the consonant does not make a real word. Then be flexible: try dividing after the consonant and make the vowel short: rob / in, robin. Try the long sound first, then the short sound."],
 gesture="Review long vowel sounds for open syllables.", soundwall="No new grapheme.", formation=None,
 spell=dict(ido=["robot"], wedo=["open","music","begin","basic"]),
 ww=dict(type="Syllable Decoding and Blending", text="Read each syllable, then blend: ra/ven, si/lent, va/cant, mu/sic, ro/bot, o/pen, be/gin, se/cret, hu/mid, fro/zen, ti/ger, ba/con.", chain="robot → robin → rodent → basin → basic → bacon → begin → began → being → unit → unite"),
 text_spell=["My phone has been on silent.","Did your friend begin the race?","I love music because we get to sing."],
 chains=[["Syllable Level: open/closed","ro-bot, o-pen, mu-sic, ba-sic, be-gin, se-cret, hu-mid, fro-zen, e-ven, ti-ger, si-lent, pi-lot"],["Syllable Level: flexible (long or short?)","robot / robin, cabin, lemon, seven, planet, tulip, spider*"]],
 hf=dict(dolch=["open","begin"], fry=["open","begin"]), lists={"open/closed":["basic","frozen","open","even","unit","virus","robot","begin","secret","humid","moment","music","silent","vacant","raven","tiger","pilot","bacon","spoken","tulip","student","total","hotel","potent"]})
P["69"] = dict(tag="The grapheme TCH spells /ch/",
 notes=["Use TCH right after a short vowel at the end of a word (catch, itch). Use CH after a consonant or a long vowel (bench, much, coach). Exceptions: much, such, rich, which, sandwich."],
 pa=dict(blend=["/m/ /ă/ /ch/ (match)","/ĭ/ /ch/ (itch)","/f/ /ĕ/ /ch/ (fetch)","/w/ /ĭ/ /ch/ (witch)"], segment=["latch (/l/ /ă/ /ch/)","patch (/p/ /ă/ /ch/)","ditch (/d/ /ĭ/ /ch/)","switch (/s/ /w/ /ĭ/ /ch/)"]),
 bd=dict(chain="match → batch → patch → latch → hatch → hutch → Dutch → ditch → pitch → witch → switch → stitch → stretch → fetch → sketch", grid=g(["tch","ch","nch","ck","sh","th"], None, ["m","b","p","l","h","d","w","sw","st","str","f","sk","n","cl","scr"])),
 intro=["We know that CH spells /ch/ as in chip and much. Today we will learn another way to spell /ch/: TCH. T-C-H spells one sound, /ch/, like at the end of catch.",
        "TCH comes at the end of a word right after a short vowel: match, fetch, itch, witch. After a consonant we use CH: bench, lunch. This is like CK: right after a short vowel we use ck (back), and after a consonant we use k (milk).",
        "A few words are exceptions and use CH after a short vowel: much, such, rich, which."],
 gesture="Review the /ch/ gesture.", soundwall="Add 'tch' under /ch/ next to 'ch'.", formation=None,
 spell=dict(ido=["match"], wedo=["fetch","itch","witch","switch"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="match → batch → patch → latch → hatch → hutch → ditch → pitch → witch → switch → stitch → stretch → fetch → sketch"),
 text_spell=["Spot will fetch the long stick.","The woman will patch the dress with lace.","Close the latch on the fence."],
 chains=[["Onset-Rime Level: -atch","match → batch → patch → latch → hatch → catch → snatch → scratch"],["Onset-Rime Level: -itch","itch → ditch → pitch → witch → switch → stitch → twitch"],["Onset-Rime Level: -etch","fetch → sketch → stretch → wretch"],["Phoneme Level: ch or tch?","much → mutch* → match → march* → bench → bunch → butch"]],
 hf=dict(dolch=["woman","women"], fry=[]), lists={"tch /ch/":["match","itch","fetch","witch","latch","patch","ditch","hatch","stitch","switch","catch","pitch","crutch","sketch","stretch","batch","hutch","notch","clutch","scratch","kitchen","watch*"]})
P["70"] = dict(tag="The grapheme DGE spells /j/",
 notes=["Use DGE right after a short vowel at the end of a word (badge, bridge, fudge). Use -GE after a consonant or long vowel (cage, hinge, large). Like ck and tch, dge follows a short vowel."],
 pa=dict(blend=["/b/ /ă/ /j/ (badge)","/f/ /r/ /ĭ/ /j/ (fridge)","/j/ /ŭ/ /j/ (judge)","/ĕ/ /j/ (edge)"], segment=["ledge (/l/ /ĕ/ /j/)","wedge (/w/ /ĕ/ /j/)","smudge (/s/ /m/ /ŭ/ /j/)","bridge (/b/ /r/ /ĭ/ /j/)"]),
 bd=dict(chain="badge → bridge → ridge → ledge → edge → wedge → hedge → fudge → judge → nudge → budge → smudge → grudge → lodge → dodge", grid=g(["dge","ge","tch","ck","nge"], None, ["b","br","r","l","w","h","f","j","n","sm","gr","d","tr","pl","sl"])),
 intro=["We know that -ge spells /j/ at the end of a word after a long vowel: cage, huge. Today we will learn DGE. D-G-E spells one sound, /j/, like at the end of badge.",
        "DGE comes at the end of a word right after a short vowel: badge, edge, bridge, fudge. This is like ck and tch: right after a short vowel we use the longer spelling. After a consonant or a long vowel we use -ge: hinge, cage.",
        "Remember: J is never written at the end of a word. We use -ge or -dge."],
 gesture="Review the /j/ gesture.", soundwall="Add 'dge' under /j/ next to 'j' and '_ge'.", formation=None,
 spell=dict(ido=["badge"], wedo=["fridge","judge","edge","fudge"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="badge → bridge → ridge → ledge → edge → wedge → hedge → fudge → judge → nudge → budge → smudge → grudge → lodge → dodge"),
 text_spell=["Has Midge been your friend for a long time?","I moved the batch of fudge into the fridge.","The woman trims the hedge next to the fence."],
 chains=[["Onset-Rime Level: -edge","edge → ledge → wedge → hedge → pledge → sledge"],["Onset-Rime Level: -udge","fudge → judge → nudge → budge → smudge → grudge → trudge"],["Onset-Rime Level: -idge","ridge → bridge → fridge → midge"],["Phoneme Level: ge or dge?","cage → badge, huge → fudge, page → pledge, stage → smudge"]],
 hf=dict(dolch=["move"], fry=["move"]), lists={"dge /j/":["badge","fridge","ridge","ledge","judge","wedge","fudge","nudge","bridge","smudge","grudge","edge","hedge","pledge","dodge","lodge","budge","trudge","sledge","midge"]})
P["71"] = dict(tag="tch /ch/ and dge /j/ review",
 pa=dict(blend=["/h/ /ă/ /ch/ (hatch)","/b/ /ă/ /j/ (badge)","/s/ /t/ /r/ /ĕ/ /ch/ (stretch)","/t/ /r/ /ŭ/ /j/ (trudge)"], segment=["patch (/p/ /ă/ /ch/)","ledge (/l/ /ĕ/ /j/)","fridge (/f/ /r/ /ĭ/ /j/)","switch (/s/ /w/ /ĭ/ /ch/)"]),
 bd=dict(chain="match → patch → batch → badge → bridge → ridge → ditch → pitch → witch → wedge → hedge → edge → etch → fetch → fudge → judge", grid=g(["tch","dge","ch","ge","ck"], None, ["m","p","b","br","r","d","w","h","f","j","st","sw","sm","tr"])),
 intro=["We have learned that after a short vowel at the end of a word, /ch/ is spelled tch (catch) and /j/ is spelled dge (badge). After a consonant or a long vowel we use ch and ge (bench, cage). Today we review both.",
        "When you spell a word ending in /ch/ or /j/, ask: is the vowel short and right before the sound? If yes, use tch or dge."],
 gesture="Review /ch/ and /j/ (same mouth position; /ch/ quiet, /j/ voice on).", soundwall="Review tch and dge cards.", formation=None,
 spell=dict(ido=["hatch"], wedo=["badge","match","ridge","stretch"]),
 ww=dict(type="Word Sort", text="Read and sort the words by their ending: tch, ch, dge, ge. Words: hatch, badge, match, ditch, patch, stretch, ridge, ledge, bridge, trudge, fridge, bench, cage, lunch, page, much.", chain="match → patch → batch → badge → bridge → ridge → ditch → pitch → witch → wedge → hedge → edge → etch → fetch → fudge → judge"),
 text_spell=["I see a smudge on my chin.","They have a patch that will match.","Mitch moved back home because he missed his friends."],
 chains=[["Phoneme Level: tch/dge","match → batch → badge → bridge → ridge → ditch → pitch → witch → wedge → hedge → edge → etch → fetch → fudge → judge"]],
 hf=dict(dolch=[], fry=[]), lists={"tch":["hatch","match","ditch","patch","stretch","switch","fetch","kitchen","scratch","snatch"],"dge":["badge","ridge","ledge","bridge","trudge","fridge","fudge","pledge","judge","smudge"]})
P["72"] = dict(tag="Long VCC patterns: -ild, -old, -ind, -olt, -ost",
 notes=["In a few endings the vowel is long even though the syllable is closed: wild, child, mild; old, cold, told; find, kind, mind; bolt, colt; most, post, host. Exceptions: wind (air), cost, lost, frost, gold vs. golf."],
 pa=dict(blend=["/w/ /ī/ /l/ /d/ (wild)","/k/ /ō/ /l/ /d/ (cold)","/f/ /ī/ /n/ /d/ (find)","/m/ /ō/ /s/ /t/ (most)"], segment=["child (/ch/ /ī/ /l/ /d/)","hold (/h/ /ō/ /l/ /d/)","kind (/k/ /ī/ /n/ /d/)","bolt (/b/ /ō/ /l/ /t/)"]),
 bd=dict(chain="old → cold → fold → gold → hold → bold → bolt → colt → jolt → most → post → host → hind → find → kind → mind → mild → wild → child", grid=dict(initial=["c","f","g","h","b","j","m","p","k","w","ch","s","t","bl","gr"], medial=["o","i"], final=["ld","lt","st","nd"])),
 intro=["We know that in a closed syllable the vowel is usually short: hot, hop. Today we will learn some special endings where the vowel is long even though the syllable is closed.",
        "-ild says /īld/: wild, child, mild. -ind says /īnd/: find, kind, mind. -old says /ōld/: old, cold, told. -olt says /ōlt/: bolt, colt. -ost says /ōst/: most, post, host.",
        "Learn these endings as chunks. Be careful: some words with these letters keep the short vowel - cost, lost, frost, wind (the blowing kind). Be flexible: try the long sound first, then the short sound."],
 gesture="Review /ī/ and /ō/.", soundwall="Add chunk cards -ild, -ind under /ī/ and -old, -olt, -ost under /ō/.", formation=None,
 spell=dict(ido=["cold"], wedo=["child","find","most","bolt"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="old → cold → fold → gold → hold → bold → bolt → colt → jolt → most → post → host → hind → find → kind → mind → mild → wild → child"),
 text_spell=["It is cold in the old home.","The child wanted to hold the sketch.","What kind of cake do you like the most?"],
 chains=[["Onset-Rime Level: -old","old → cold → fold → gold → hold → bold → sold → told → scold"],["Onset-Rime Level: -ind","find → kind → mind → bind → hind → blind → grind"],["Onset-Rime Level: -ild / -olt / -ost","wild → mild → child; bolt → colt → jolt; most → post → host"]],
 hf=dict(dolch=["old","cold","kind","find","hold","both"], fry=["old","find","kind","hold"]), lists={"-ild / -ind":["mild","child","wild","find","kind","mind","bind","hind","blind","grind","behind","rewind"],"-old / -olt / -ost":["old","cold","hold","bold","fold","gold","sold","told","scold","bolt","colt","jolt","most","post","host","ghost*"]})
P["73"] = dict(tag="The grapheme Y spells /ī/ at the end of a word",
 notes=["Y is a vowel at the end of a word. In one-syllable words (and stressed endings) it says /ī/: my, fly, sky. This makes by and my decodable."],
 pa=dict(blend=["/m/ /ī/ (my)","/f/ /l/ /ī/ (fly)","/s/ /k/ /ī/ (sky)","/k/ /r/ /ī/ (cry)"], segment=["by (/b/ /ī/)","try (/t/ /r/ /ī/)","spy (/s/ /p/ /ī/)","why (/w/ /ī/)"]),
 bd=dict(chain="my → by → fly → fry → cry → dry → try → sly → sky → spy → shy → why", grid=dict(initial=["m","b","fl","fr","cr","dr","tr","sl","sk","sp","sh","wh","pr","st"], medial=["y"], final=[])),
 intro=["We know that Y is a consonant at the beginning of a word, as in yes and yellow. Today we will learn that Y is a vowel at the end of a word. At the end of a short word, Y spells /ī/, like in my and fly.",
        "Y /ī/ comes at the end of one-syllable words: by, my, sky, try, why. English words do not usually end with the letter I, so Y does the job: fl-y, fly."],
 gesture="Review the /ī/ gesture.", soundwall="Add 'y' under /ī/ on the vowel valley.", formation=None,
 spell=dict(ido=["my"], wedo=["fly","sky","try","why"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="my → by → fly → fry → cry → dry → try → sly → sky → spy → shy → why"),
 text_spell=["The fly landed by the plate.","I was trying to dry myself in the sun.","Sky was in fourth place by the end of the race."],
 chains=[["Phoneme Level: Targeted (-y /ī/)","my → by → fly → fry → cry → dry → try → sly → sky → spy → shy → why"]],
 hf=dict(dolch=["my","by","fly","try","why","four"], fry=["my","by","try","why"]), lists={"y /ī/":["my","fry","by","fly","sky","cry","pry","sty","sly","spy","try","why","dry","shy","reply*","July","myself","supply*"]})
P["74"] = dict(tag="The grapheme Y spells /ē/ at the end of a word",
 notes=["At the end of a two-syllable word, Y spells /ē/: happy, funny, baby. Divide the syllables, then read: hap-py, ba-by."],
 pa=dict(blend=["hap-py (happy)","fun-ny (funny)","ba-by (baby)","sun-ny (sunny)"], segment=["lucky (luck-y)","candy (cand-y)","only (on-ly)","tiny (ti-ny)"]),
 bd=dict(chain="funny → sunny → bunny → puppy → happy → sappy → sandy → candy → handy → windy → mummy → tummy → yummy", grid=dict(initial=["fun","sun","bun","pup","hap","sap","sand","cand","hand","wind","mum","tum","yum","luck","stud","ba","ti"], medial=[], final=["ny","py","dy","my","ky","ly","by"])),
 intro=["Yesterday we learned that Y spells /ī/ at the end of a short word: my, fly. Today we will learn that at the end of a longer word, Y spells /ē/, like at the end of happy and baby.",
        "Y /ē/ comes at the end of two-syllable words: hap-py, fun-ny, ba-by. To read these words, divide the syllables, read each part, then blend: fun / ny, funny."],
 gesture="Review the /ē/ gesture.", soundwall="Add 'y' under /ē/ on the vowel valley.", formation=None,
 spell=dict(ido=["happy"], wedo=["funny","baby","sunny","candy"]),
 ww=dict(type="Word Work with Writing", chain="funny → sunny → bunny → puppy → happy → sappy → sandy → candy → handy → windy → mummy → tummy → yummy"),
 text_spell=["Did your buddy bring you candy?","I will bring a funny gift for Tommy.","It was both foggy and windy by the lake."],
 chains=[["Syllable Level: Targeted (-y /ē/)","funny → sunny → bunny → puppy → happy → sappy → sandy → candy → handy → windy"]],
 hf=dict(dolch=["funny","only","happy"], fry=["only"]), lists={"y /ē/":["happy","lady","funny","lucky","candy","mummy","sunny","study","only","baby","tiny","puppy","bunny","windy","handy","sandy","silly","jelly","penny","muddy","foggy","pony","body"]})
P["75"] = dict(tag="The final stable syllable -le",
 notes=["-le is a final stable syllable: consonant + le at the end of a word (ap-ple, puz-zle). Divide before the consonant that comes before -le. If the first syllable is closed, the vowel is short (lit-tle); if open, it is long (ta-ble)."],
 pa=dict(blend=["ap-ple (apple)","puz-zle (puzzle)","lit-tle (little)","ta-ble (table)"], segment=["middle (mid-dle)","handle (han-dle)","simple (sim-ple)","noble (no-ble)"]),
 bd=dict(chain="puddle → paddle → saddle → riddle → middle → little → battle → rattle → cattle → settle → kettle → nettle", grid=dict(initial=["pud","pad","sad","rid","mid","lit","bat","rat","cat","set","ket","net","han","jin","sim"], medial=[], final=["dle","tle","ple","gle","ble","kle","zle"])),
 intro=["A syllable is a word or word part with one vowel sound. We know closed syllables (short vowel) and open syllables (long vowel). Today we will learn a final stable syllable: -le.",
        "Final means it comes last. Stable means it always looks and sounds the same. -le comes at the end of a word with a consonant in front of it: ap-ple, puz-zle. The -le syllable says /əl/ - the e is silent and the L makes the sound.",
        "To read a word ending in -le, divide before the consonant that comes before -le: lit / tle, ta / ble. Read the first syllable, then add the -le syllable."],
 gesture="Say the /əl/ syllable: a quick relaxed /ə/ then /l/.", soundwall="Add '-le' as a final stable syllable card.", formation=None,
 spell=dict(ido=["little"], wedo=["puddle","table","handle","simple"]),
 ww=dict(type="Word Work with Writing", chain="puddle → paddle → saddle → riddle → middle → little → battle → rattle → cattle → settle → kettle"),
 text_spell=["My uncle is so kind and funny!","Many people see the bubbles go by.","There are forty people on the shuttle."],
 chains=[["Syllable Level: Targeted (-le)","puddle → paddle → saddle → riddle → middle → little → battle → rattle → cattle → settle → kettle"],["Syllable Level: closed + -le / open + -le","little, puzzle, middle, bubble; table, noble, bugle, title"]],
 hf=dict(dolch=["little","people"], fry=["little","people"]), lists={"-le":["little","puddle","jingle","middle","battle","handle","simple","trample","table","noble","apple","puzzle","bubble","candle","uncle","bottle","cattle","giggle","wiggle","sample","title","bugle","able","able"]})
P["76"] = dict(tag="Ending patterns review: -ild -old -ind -olt -ost, y /ī/ /ē/, -le",
 pa=dict(blend=["/r/ /ī/ /n/ /d/ (rind)","/s/ /l/ /ī/ (sly)","la-dy (lady)","no-ble (noble)"], segment=["hold (/h/ /ō/ /l/ /d/)","try (/t/ /r/ /ī/)","study (stud-y)","little (lit-tle)"]),
 bd=dict(chain="mild → wild → wind → mind → kind → find → fold → hold → cold → colt → bolt → jolt → most → post", grid=dict(initial=["m","w","k","f","h","c","b","j","p","ch","bl","gr","sc","t"], medial=["i","o"], final=["ld","nd","lt","st"])),
 intro=["We have learned several ending patterns: -ild, -old, -ind, -olt, -ost with long vowels; Y at the end of a word spelling /ī/ (my) or /ē/ (happy); and the final stable syllable -le (little). Today we review all of them.",
        "Look at the end of the word first. Is there a Y? One syllable: /ī/; two syllables: /ē/. Is there -le? Divide before the consonant. Is there -old, -ind...? Try the long vowel."],
 gesture="Review /ī/, /ō/, /ē/.", soundwall="No new grapheme.", formation=None,
 spell=dict(ido=["wild"], wedo=["hold","sky","lady","table"]),
 ww=dict(type="Word Sort", text="Read and sort the words by ending pattern: long VCC (-ild, -old, -ind, -olt, -ost), y /ī/, y /ē/, -le. Words: rind, sly, lady, noble, wild, hold, mind, my, sky, by, puppy, baby, lumpy, dazzle, table, middle.", chain="mild → wild → mind → kind → find → fold → hold → cold → colt → bolt → jolt → most → post"),
 text_spell=["Many people like candy apples.","Does the little pony have a bridle?","The lady holds the baby while walking."],
 chains=[["Phoneme Level: Mixed Review","mild → wild → mind → kind → find → fold → hold → cold → colt → bolt → jolt → most → post"]],
 hf=dict(dolch=[], fry=[]), lists={"review":["rind","sly","lady","noble","wild","hold","mind","my","sky","by","puppy","baby","lumpy","dazzle","table","middle","try","study","little","gold","child","fly","happy","bubble"]})
P["77"] = dict(tag="The grapheme AR spells /ar/",
 notes=["AR is an r-controlled vowel: the R changes the vowel sound so A no longer says /ă/. In Australian/NZ English /ar/ is a long open vowel with no /r/ sound at the end (car, park)."],
 pa=dict(blend=["/p/ /ar/ /t/ (part)","/f/ /ar/ (far)","/k/ /ar/ (car)","/d/ /ar/ /k/ (dark)"], segment=["hard (/h/ /ar/ /d/)","star (/s/ /t/ /ar/)","park (/p/ /ar/ /k/)","art (/ar/ /t/)"]),
 bd=dict(chain="car → card → hard → harm → farm → far → jar → bar → bark → dark → park → part → art → arm → charm", grid=dict(initial=["c","h","f","j","b","d","p","st","sh","ch","sm","sp","m","y"], medial=["ar"], final=["d","m","k","t","n","p","ch","sh",""])),
 intro=["Today we are learning about the letters AR. We know A spells /ă/. When A is followed by R, the R changes the vowel sound. AR spells /ar/, like in the words bark, far and arm. We call this an r-controlled vowel: the R is the boss of the vowel.",
        "AR can come at the beginning of a word, such as art and arm. AR can come in the middle, such as bark and part, or at the end, such as far and star."],
 gesture="To make the /ar/ sound as in 'arm', open your mouth wide and relaxed, and drop your chin a little... (model). Be sure your voice is on. /ar/ is a continuous sound that can be stretched out. Watch me /ar/. You try /ar/.",
 soundwall="Add 'ar' under /ar/ (r-controlled vowels).", formation=None,
 spell=dict(ido=["car"], wedo=["park","hard","star","farm"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="car → card → hard → harm → farm → far → jar → bar → bark → dark → park → part → art → arm → charm"),
 text_spell=["Bart makes a pretty card in art.","My dog loves car rides to the park.","The cat played with yarn in the backyard."],
 chains=[["Onset-Rime Level: -ark","bark → dark → park → mark → shark → spark"],["Onset-Rime Level: -art","art → cart → part → dart → start → chart → smart"],["Onset-Rime Level: -arm","arm → farm → harm → charm"],["Phoneme Level: Intro Lesson","car → card → hard → harm → farm → far → jar → bar → bark → dark → park → part → art → arm → charm"]],
 hf=dict(dolch=["far","start","pretty"], fry=["far","start"]), lists={"ar /ar/":["part","start","far","car","hard","star","dark","park","large","marble","target","art","arm","farm","harm","bark","shark","smart","chart","yard","card","jar","barn","garden","carpet"]})
P["77AUS"] = dict(tag="The grapheme A spells /ar/ (Australian/NZ pronunciation)",
 notes=["This lesson has been added into the Australian scope and sequence because in Australian/NZ English the letter A commonly represents /ar/ before s, th, f and n clusters: bath, last, ask, after, dance.",
        "This makes ask and fast (heart words since Lesson 22) fully decodable."],
 pa=dict(blend=["/ar/ /s/ /k/ (ask)","/l/ /ar/ /s/ /t/ (last)","/b/ /l/ /ar/ /s/ /t/ (blast)","/g/ /r/ /ar/ /s/ /p/ (grasp)"], segment=["fast (/f/ /ar/ /s/ /t/)","mask (/m/ /ar/ /s/ /k/)","grass (/g/ /r/ /ar/ /s/)","paths (/p/ /ar/ /th/ /s/)"]),
 bd=dict(chain="host → hold → holt → hot → dot → dart → cart → part → park → dark → bark → barge → large → charge", grid=dict(initial=["b","c","d","g","k","t","h","l","p","ch"], medial=["o","e","ar"], final=["lt","st","ld","t","k","rge","ch"])),
 intro=["We have learned about the /ar/ sound. We learned AR can spell /ar/ like in the words bark, far, and arm.",
        "The letter A can also represent the /ar/ sound. A spells /ar/ in the middle of a word, such as the words bath and last. A can spell /ar/ at the beginning of a word, such as the words ask and after."],
 gesture="To make the /ar/ sound as in 'arm', start with an open relaxed mouth and as you say the sound, drop your chin a little like this (model). Be sure your voice is on. Like all vowels, /ar/ is a continuous sound that can be stretched out (use continuous hand motion). Watch me /ar/. You try /ar/.",
 soundwall="Add 'a' under /ar/.", formation="Practise letter formation, as needed.",
 read=dict(ido=["ask","class","mast"], wedo=["asked","gasp","fast","mask","past","last","grasp","grass","flask"]), spell=dict(ido=["past","craft"], wedo=["last","fast","ask","grass","class","blast"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="ask → task → mask → mast → cast → past → fast → last → blast"),
 text_spell=["I can't have a bath.","The path led to the tall grass.","She asked for two large glasses."],
 chains=[["Onset-Rime Level: -ast","blast → last → fast → past → cast"],["Onset-Rime Level: -ask","mask → task → nask → ask → bask"],["Phoneme Level: -ing","blasting → lasting → fasting → asting → asking → masking → tasking"],["Phoneme Level: Mixed Review","baths → paths → path → pat → past → mast → mask → ask → bask → fask → fast → last → blast → blass → brass → grass → grasp → gasp"],["Phoneme Level: Intro Lesson","ask → task → mask → mast → cast → past → fast → last → blast"]],
 hf=dict(dolch=["ask","fast","half"], fry=["ask"]), lists={"a /ar/":["ask","bath","blast","brass","cast","class","craft","draft","fast","flask","gasp","glass","grasp","grass","last","mask","mast","pass","past","path","raft","staff","task"],"2 syllables":["basket","drama","data","lava","nasty"]})
P["78"] = dict(tag="The graphemes OR and ORE spell /or/",
 notes=["OR spells /or/ at the beginning, middle or end of a word (orb, fork, for). ORE spells /or/ at the end of a word (more, store). In Australian/NZ English /or/ is a long vowel with no /r/ sound."],
 pa=dict(blend=["/f/ /or/ /k/ (fork)","/k/ /or/ /n/ (corn)","/m/ /or/ (more)","/s/ /t/ /or/ (store)"], segment=["sport (/s/ /p/ /or/ /t/)","north (/n/ /or/ /th/)","form (/f/ /or/ /m/)","shore (/sh/ /or/)"]),
 bd=dict(chain="for → fork → cork → corn → born → torn → worn* → horn → thorn → short → sort → sport → port → fort → form → storm → store → more", grid=dict(initial=["f","c","b","t","h","th","sh","s","sp","p","st","m","sc","sn"], medial=["or","ar"], final=["k","n","t","m","ch","d","e",""])),
 intro=["Today we are learning another r-controlled vowel. When O is followed by R, the R changes the vowel sound. OR spells /or/, like in fork and corn.",
        "OR can come at the beginning of a word (orb), in the middle (fork, corn) or at the end (for). At the end of a word, /or/ is often spelled ORE, with a silent e: more, store, shore."],
 gesture="To make the /or/ sound as in 'orange', round your lips and open your mouth a little... (model). Be sure your voice is on. /or/ is a continuous sound. Watch me /or/. You try /or/.",
 soundwall="Add 'or' and 'ore' under /or/.", formation=None,
 spell=dict(ido=["fork"], wedo=["corn","more","short","store"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="for → fork → cork → corn → born → torn → horn → thorn → short → sort → sport → port → fort → form → storm → store → more"),
 text_spell=["The bad storm tore up the shore.","I love to sit and do nothing on my porch.","We ate pork and corn for lunch."],
 chains=[["Onset-Rime Level: -orn","corn → born → torn → horn → thorn → worn"],["Onset-Rime Level: -ort","sort → short → sport → port → fort → snort"],["Onset-Rime Level: -ore","more → store → shore → sore → tore → score → snore → before"],["Phoneme Level: Intro Lesson","for → fork → cork → corn → born → torn → horn → thorn → short → sort → sport → port → fort → form → storm → store → more"]],
 hf=dict(dolch=["for","or","more","before","nothing"], fry=["for","or","more","before"]), lists={"or /or/":["sport","important","for","form","corn","north","fork","short","storm","horn","born","torn","sort","port","fort","morning","story","forty","order","corner"],"ore /or/":["more","store","shore","score","before","sore","tore","wore","snore","chore","bore","core","adore","ignore","explore"]})
P["79"] = dict(tag="ar /ar/ and or, ore /or/ review",
 pa=dict(blend=["/s/ /t/ /ar/ /t/ (start)","/f/ /or/ /m/ (form)","/l/ /ar/ /j/ (large)","/m/ /or/ (more)"], segment=["hard (/h/ /ar/ /d/)","short (/sh/ /or/ /t/)","march (/m/ /ar/ /ch/)","store (/s/ /t/ /or/)"]),
 bd=dict(chain="car → cart → chart → charm → harm → farm → form → storm → store → shore → short → sort → sport → spar → star → start", grid=dict(initial=["c","ch","h","f","st","sh","sp","m","b","d","p","t"], medial=["ar","or"], final=["t","m","d","k","ch","e","n",""])),
 intro=["We have learned two r-controlled vowels: AR spells /ar/ (car, park) and OR/ORE spell /or/ (fork, more). Today we review both.",
        "When you see a vowel followed by R, read them together as one sound. Do not say the short vowel."],
 gesture="Review /ar/ and /or/.", soundwall="No new grapheme.", formation=None,
 spell=dict(ido=["start"], wedo=["form","large","more","short"]),
 ww=dict(type="Word Sort", text="Read and sort the words by vowel sound: /ar/ (ar) or /or/ (or, ore). Words: start, important, hard, part, large, march, form, more, story, before, market, morning, shark, corner, score, garden.", chain="car → cart → chart → charm → harm → farm → form → storm → store → shore → short → sort → sport → spar → star → start"),
 text_spell=["There was nothing left in the cart.","The pretty stars twinkle in the dark sky.","The people wore shorts to the party."],
 chains=[["Phoneme Level: ar/or","car → cart → chart → charm → harm → farm → form → storm → store → shore → short → sort → sport → spar → star → start"]],
 hf=dict(dolch=[], fry=[]), lists={"ar":["start","hard","part","large","march","market","garden","shark","smart","farmer","party","carpet"],"or / ore":["important","form","more","story","before","morning","corner","score","short","storm","forty","order"]})
P["80"] = dict(tag="The grapheme ER spells /er/",
 notes=["ER spells /er/ in the middle of a word (fern, verb) and at the end (her). Lesson 80 AUS covers ER as the unstressed schwa /ə/ at the end of two-syllable words (letter, sister)."],
 pa=dict(blend=["/h/ /er/ (her)","/f/ /er/ /n/ (fern)","/v/ /er/ /b/ (verb)","/t/ /er/ /m/ (term)"], segment=["herd (/h/ /er/ /d/)","perch (/p/ /er/ /ch/)","serve (/s/ /er/ /v/)","nerve (/n/ /er/ /v/)"]),
 bd=dict(chain="her → herd → herb → verb → very* → fern → term → germ → perm → perch → per → percent", grid=dict(initial=["h","v","f","t","g","p","s","n","st","cl","j","m"], medial=["er","ar","or"], final=["d","b","n","m","ch","ve","k","t",""])),
 intro=["Today we are learning another r-controlled vowel. When E is followed by R, the R changes the vowel sound. ER spells /er/, like in her and fern.",
        "ER can come in the middle of a word, such as verb and fern. ER can also come at the end of a word, such as her and per."],
 gesture="To make the /er/ sound as in 'earth', open your mouth a little and pull your tongue back and up slightly... (model). Be sure your voice is on. /er/ is a continuous sound. Watch me /er/. You try /er/.",
 soundwall="Add 'er' under /er/.", formation=None,
 spell=dict(ido=["her"], wedo=["fern","verb","term","herd"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="her → herd → herb → verb → fern → term → germ → perm → perch → per"),
 text_spell=["That pretty fern will perk her up!","What other dishes do they serve?","I planted another fern on my verge."],
 chains=[["Onset-Rime Level: -erm / -ern","term → germ → perm → fern → stern"],["Phoneme Level: Intro Lesson","her → herd → herb → verb → fern → term → germ → perm → perch → per"]],
 hf=dict(dolch=["her","other","another"], fry=["her","other","another"]), lists={"er /er/":["her","term","fern","verb","adverb","herd","perch","serve","nerve","germ","stern","perk","jerk","clerk","expert","person","perfect","concert","verse","merge"]})
P["80AUS"] = dict(tag="The grapheme ER spells /ə/ (schwa) at the end of two-syllable words",
 notes=["This lesson has been added into the Australian scope and sequence because ER commonly represents the sound /ə/ at the end of many two-syllable words (letter, number, sister).",
        "Word work today uses writing because of the double letters."],
 pa=dict(blend=["/ō/ (o) /v/ /ə/ (ver) o-ver (over)","/w/ /ĭ/ /n/ (win) /t/ /ə/ (ter) win-ter (winter)","sis-ter (sister)","af-ter (after)"], segment=["after (af-ter): af (/ar/ /f/) ter (/t/ /ə/)","sister (sis-ter): sis (/s/ /ĭ/ /s/) ter (/t/ /ə/)","never (nev-er)","river (riv-er)"]),
 bd=dict(chain="bath → baths → paths → path → pat → past → mast → fast → cast → last → blast → blass → brass → grass → glass → class", grid=dict(initial=["b","c","f","l","m","p","br","gr","bl","cl","gl"], medial=["a"], final=["t","ss","st","s","th"])),
 intro=["We have been learning that the /er/ sound is an r-controlled vowel sound. ER can come in the middle of a word, such as the words verb and fern. ER can also come at the end of a word, such as the word her.",
        "However, when we see ER at the end of a two-syllable word, it is usually pronounced using the schwa sound, /ə/, such as the words letter and number."],
 gesture="To make the schwa /ə/ sound, open your mouth just a little bit, like this... (model). Be sure your voice is on. Unlike all the other vowel sounds, we don't really stretch out the schwa. We say it more quickly. Watch me /ə/. You try /ə/. Sometimes, a schwa can sound a little like a short u /ŭ/ or a short i /ĭ/, but it's actually more relaxed than either of those. Watch me again /ə/. You try again /ə/.",
 soundwall="Add 'er' under /ə/.", formation="Practise letter formation, as needed.",
 read=dict(ido=["ever","after","sister"], wedo=["over","under","never","winter","better","river"]), spell=dict(ido=["after"], wedo=["under","river"]),
 ww=dict(type="Word Work with Writing", chain="letter → litter → bitter → better → butter → batter"),
 text_spell=["My sister never litters.","You can go over or under the bridge.","Can my friend have another ride after me?"],
 chains=[["Phoneme Level: Intro Lesson","letter → litter → bitter → better → butter → batter"]],
 hf=dict(dolch=["after","over","under","never","water"], fry=["after","over","under","never","water"]), lists={"er /ə/":["after","batter","better","bitter","butter","ever","farmer","father","letter","lever","litter","mister","never","over","river","sister","super","under","winter"]})
P["81"] = dict(tag="The graphemes IR and UR spell /er/",
 notes=["IR and UR spell the same sound as ER: /er/. IR is usually in the middle of a word (bird, girl, first). UR can be in the middle (turn, hurt) or at the end (fur, blur). Spelling /er/ requires remembering the word - see Lesson 82."],
 pa=dict(blend=["/g/ /er/ /l/ (girl)","/b/ /er/ /d/ (bird)","/t/ /er/ /n/ (turn)","/h/ /er/ /t/ (hurt)"], segment=["third (/th/ /er/ /d/)","burn (/b/ /er/ /n/)","nurse (/n/ /er/ /s/)","churn (/ch/ /er/ /n/)"]),
 bd=dict(chain="bird → third → thirst → first → fir → fur → furl → curl → hurl → hurt → turn → burn → churn → church", grid=dict(initial=["b","th","f","c","h","t","ch","g","st","sh","d","bl","sp"], medial=["ir","ur","er"], final=["d","st","l","t","n","ch","se","ge","k",""])),
 intro=["We learned that ER spells /er/, as in her and fern. Today we will learn two more spellings for the same sound. IR spells /er/, like in bird and girl. UR spells /er/, like in turn and hurt.",
        "IR usually comes in the middle of a word: girl, bird, sir, stir. UR comes in the middle (turn, hurt, urge) or at the end of a word (fur, blur). When you hear /er/, it could be spelled er, ir or ur - you have to remember which one."],
 gesture="Review the /er/ gesture.", soundwall="Add 'ir' and 'ur' under /er/.", formation=None,
 spell=dict(ido=["bird"], wedo=["girl","turn","hurt","first"]),
 ww=dict(type="Word Work with Manipulative Letters", chain="bird → third → thirst → first → fir → fur → furl → curl → hurl → hurt → turn → burn → churn → church"),
 text_spell=["There is some dirt on her shirt.","Her brother is done with first grade!","My mother has a black skirt and a pink purse."],
 chains=[["Onset-Rime Level: -irt / -ird","dirt → shirt → skirt → flirt; bird → third → gird"],["Onset-Rime Level: -urn / -urt","turn → burn → churn; hurt → curt → blurt"],["Phoneme Level: Intro Lesson","bird → third → thirst → first → fir → fur → furl → curl → hurl → hurt → turn → burn → churn → church"]],
 hf=dict(dolch=["first","mother","brother"], fry=["first","mother","brother"]), lists={"ir /er/":["dirty","girl","bird","third","thirty","first","stir","sir","shirt","skirt","birth","firm","thirst","circle","chirp"],"ur /er/":["turn","hurt","burn","nurse","churn","turtle","fur","blur","curl","hurl","purse","surf","burst","church","urge","Thursday","purple","further"]})
P["82"] = dict(tag="Spelling /er/: er, ir, ur, w + or",
 notes=["/er/ has several spellings: er, ir, ur, and or after w (work, word, world). When spelling, use these hints: er is the most common and is used at the end of two-syllable words; ur/ir are common in one-syllable words; after w, /er/ is often spelled or."],
 pa=dict(blend=["/w/ /er/ /k/ (work)","/w/ /er/ /d/ (word)","/w/ /er/ /l/ /d/ (world)","/w/ /er/ /m/ (worm)"], segment=["her (/h/ /er/)","third (/th/ /er/ /d/)","hurt (/h/ /er/ /t/)","worth (/w/ /er/ /th/)"]),
 bd=dict(chain="work → worm → word → world → worst → worth → wort → worse → nurse → purse → curse → curl → girl → fern → term", grid=dict(initial=["w","n","p","c","g","f","t","h","b","st","th","ch"], medial=["or","ur","ir","er"], final=["k","m","d","ld","st","th","se","l","n",""])),
 intro=["We know that /er/ can be spelled er, ir and ur. Today we will learn one more spelling. After the letter W, the sound /er/ is usually spelled OR: work, word, world, worm. The W makes OR say /er/ instead of /or/.",
        "When you spell a word with /er/, think about which spelling it uses: her (er), bird (ir), turn (ur), work (w + or). We will sort words by their spelling today."],
 gesture="Review /er/.", soundwall="Add 'wor' under /er/.", formation=None,
 spell=dict(ido=["work"], wedo=["word","her","third","hurt"]),
 ww=dict(type="Word Sort", text="Read and sort the words by the spelling of /er/: er, ir, ur, or (after w). Words: her, third, hurt, work, girl, first, perch, serve, turn, blur, word, world, term, observe, bird, burn, worm, verb.", chain="work → worm → word → world → worst → worth → worse → nurse → purse → curse → curl → girl → fern → term"),
 text_spell=["These worms live in the dirt.","Her baby brother just said his first words!","Bert and Kirk work well together because they are friends."],
 chains=[["Phoneme Level: w + or","work → worm → word → world → worst → worth → worse"],["Phoneme Level: Mixed /er/","nurse → purse → curse → curl → girl → fern → term → perm → firm → form → worm"]],
 hf=dict(dolch=["work","word","world"], fry=["work","word","world"]), lists={"er":["her","perch","serve","term","observe","verb","fern","clerk"],"ir":["third","girl","first","bird","dirt","shirt","thirst"],"ur":["hurt","turn","blur","burn","nurse","curl","purse"],"w + or":["work","word","world","worm","worst","worth","worse","worship"]})
P["83"] = dict(tag="R-controlled vowels review: ar, or, ore, er, ir, ur, w+or, a /ar/",
 pa=dict(blend=["/s/ /t/ /ar/ /t/ (start)","/sh/ /ar/ /p/ (sharp)","/f/ /er/ /s/ /t/ (first)","/sh/ /or/ /t/ (short)"], segment=["merge (/m/ /er/ /j/)","large (/l/ /ar/ /j/)","world (/w/ /er/ /l/ /d/)","dirty (dirt-y)"]),
 bd=dict(chain="start → star → stir → stern → fern → firm → form → fork → cork → cord → card → cart → chart → short → shirt → shark", grid=dict(initial=["st","sh","f","c","ch","p","th","w","b","h","m","sp"], medial=["ar","or","er","ir","ur"], final=["t","n","m","k","d","ch","p","st","e",""])),
 intro=["We have learned all the r-controlled vowels: ar /ar/ (park), or and ore /or/ (fork, more), er, ir, ur and w+or /er/ (fern, bird, turn, work), and in our accent, a /ar/ (bath). Today we review them all.",
        "When a vowel is followed by R, read the two letters together. Look carefully at which vowel it is."],
 gesture="Review /ar/, /or/, /er/.", soundwall="No new grapheme.", formation=None,
 spell=dict(ido=["start"], wedo=["fern","short","first","world"]),
 ww=dict(type="Word Sort", text="Read and sort the words by vowel sound: /ar/, /or/, /er/. Words: start, merge, sharp, part, first, large, fern, perk, short, fork, third, world, work, worthy, dirty, store, return, adverb, bird, her.", chain="start → star → stir → stern → fern → firm → form → fork → cork → cord → card → cart → chart → short → shirt → shark"),
 text_spell=["The shark started to swim to shore!","I got another star for doing my work.","My father was the first farmer in this part of the state."],
 chains=[["Phoneme Level: Mixed r-controlled","start → star → stir → stern → fern → firm → form → fork → cork → cord → card → cart → chart → short → shirt → shark"]],
 hf=dict(dolch=[], fry=[]), lists={"/ar/":["start","sharp","part","large","farm","garden","after","class"],"/or/":["short","fork","store","sport","form","before","corner","morning"],"/er/":["merge","first","fern","perk","third","world","work","worthy","dirty","return","adverb","bird","her","turtle"]})
