/* UFLI grapheme -> phoneme(s) + easy example words (used by deck popups and the teacher's guide).
   Sound notation follows the UFLI Foundations manual (Australian edition where it differs). */
window.GRAPHEMES = {
  // ---- single consonants ----
  "m":  {sounds:[{ph:"/m/",  ex:["mat","mop","map"]}], tip:"<b>m</b> can be at the beginning (mad) or end (gum) of a word. Lips together, voice on, a continuous sound."},
  "s":  {sounds:[{ph:"/s/",  ex:["sat","sip","sun"]},{ph:"/z/",  ex:["is","as","has"]}], tip:"<b>s</b> spells /s/ (sat) and also /z/ at the end of many words (is, has, dogs)."},
  "t":  {sounds:[{ph:"/t/",  ex:["tap","top","sat"]}], tip:"Quick, quiet stop sound. Tongue behind the top teeth."},
  "p":  {sounds:[{ph:"/p/",  ex:["pat","pig","map"]}], tip:"Lips together, then a quiet puff of air."},
  "f":  {sounds:[{ph:"/f/",  ex:["fan","fit","fun"]}], tip:"Teeth on lip, voice off, continuous sound."},
  "n":  {sounds:[{ph:"/n/",  ex:["nap","nut","pin"]}], tip:"Tongue behind top teeth, air through the nose."},
  "d":  {sounds:[{ph:"/d/",  ex:["dad","dip","mud"]}], tip:"Same mouth as /t/ but with the voice on."},
  "c":  {sounds:[{ph:"/k/",  ex:["cat","cup","can"]},{ph:"/s/",  ex:["cent","ice","city"]}], tip:"<b>c</b> spells /k/ before a, o, u. Before e, i, y it usually spells /s/ (signal vowels, Lesson 117)."},
  "g":  {sounds:[{ph:"/g/",  ex:["go","get","big"]},{ph:"/j/",  ex:["gem","page","age"]}], tip:"<b>g</b> spells /g/ (got); before e, i, y it often spells /j/ (gem, giant)."},
  "b":  {sounds:[{ph:"/b/",  ex:["bat","big","tub"]}], tip:"Lips together, voice on. Compare with quiet /p/."},
  "k":  {sounds:[{ph:"/k/",  ex:["kit","kid","desk"]}], tip:"Use <b>k</b> before i and e (kit, kept); use <b>c</b> before a, o, u."},
  "h":  {sounds:[{ph:"/h/",  ex:["hat","hop","hum"]}], tip:"A quiet puff of air from the back of the throat. Only at the beginning of a syllable."},
  "r":  {sounds:[{ph:"/r/",  ex:["rat","run","red"]}], tip:"Tongue lifted, voice on. Do not add /uh/ at the end."},
  "l":  {sounds:[{ph:"/l/",  ex:["lap","let","lid"]}], tip:"Tongue behind top teeth, voice on, continuous."},
  "w":  {sounds:[{ph:"/w/",  ex:["win","wag","wet"]}], tip:"Round the lips and glide. Only at the beginning of words or syllables."},
  "j":  {sounds:[{ph:"/j/",  ex:["jam","jet","job"]}], tip:"<b>j</b> is used at the beginning of words. At the end we use -ge or -dge."},
  "y":  {sounds:[{ph:"/y/",  ex:["yes","yam","yet"]},{ph:"/ī/",  ex:["my","fly","sky"]},{ph:"/ē/",  ex:["happy","funny","baby"]}], tip:"<b>y</b> is a consonant at the start of a word (yes). At the end it is a vowel: /ī/ in short words (my), /ē/ at the end of longer words (happy)."},
  "x":  {sounds:[{ph:"/ks/", ex:["box","six","fox"]}], tip:"<b>x</b> spells two sounds together, /k/ + /s/. Usually at the end of a word."},
  "qu": {sounds:[{ph:"/kw/", ex:["quiz","quit","quilt"]}], tip:"<b>q</b> is always followed by <b>u</b>. Together they spell /kw/."},
  "v":  {sounds:[{ph:"/v/",  ex:["van","vet","vest"]}], tip:"Teeth on lip with the voice on. English words do not end in v alone (give, have)."},
  "z":  {sounds:[{ph:"/z/",  ex:["zip","zap","quiz"]}], tip:"Same as /s/ but with the voice on."},
  // ---- short vowels ----
  "a":  {sounds:[{ph:"/ă/",  ex:["cat","map","at"]},{ph:"/ā/",  ex:["apron","baby","table"]},{ph:"/ar/", ex:["bath","last","ask"]},{ph:"/ŏ/", ex:["wash","swan","watch"]}], tip:"Short /ă/ (cat) is the first sound we learn. Open syllable: /ā/ (baby). Australian/NZ English: <b>a</b> often spells /ar/ (bath, fast). After w: /ŏ/ (wash)."},
  "i":  {sounds:[{ph:"/ĭ/",  ex:["sit","pig","in"]},{ph:"/ī/",  ex:["hi","tiger","find"]}], tip:"Short /ĭ/ in closed syllables (sit); long /ī/ in open syllables (hi, tiger) and before -nd, -ld (find, mild)."},
  "o":  {sounds:[{ph:"/ŏ/",  ex:["hot","mop","on"]},{ph:"/ō/",  ex:["no","go","cold"]}], tip:"Short /ŏ/ in closed syllables (hot); long /ō/ in open syllables (no) and before -ld, -st, -lt (cold, most)."},
  "u":  {sounds:[{ph:"/ŭ/",  ex:["cup","sun","up"]},{ph:"/ū/",  ex:["truth","flu","tuna"]},{ph:"/yū/", ex:["unit","music","menu"]},{ph:"/oo/", ex:["put","push","full"]}], tip:"Short /ŭ/ (cup). Open syllable: /ū/ or /yū/ (flu, music). Sometimes /oo/ as in put, push, bull."},
  "e":  {sounds:[{ph:"/ĕ/",  ex:["bed","pet","ten"]},{ph:"/ē/",  ex:["me","he","we"]}], tip:"Short /ĕ/ in closed syllables (bed); long /ē/ in open syllables (me, he, be)."},
  // ---- consonant digraphs & doubles ----
  "ck": {sounds:[{ph:"/k/",  ex:["sock","kick","duck"]}], tip:"Use <b>ck</b> right after a short vowel at the end of a word (back, neck, lick)."},
  "ff": {sounds:[{ph:"/f/",  ex:["off","puff","cliff"]}], tip:"FLSZ rule: double f, l, s, z after a short vowel at the end of a one-syllable word."},
  "ll": {sounds:[{ph:"/l/",  ex:["hill","bell","doll"]}], tip:"FLSZ rule: double l after a short vowel at the end of a word."},
  "ss": {sounds:[{ph:"/s/",  ex:["miss","kiss","dress"]}], tip:"FLSZ rule: double s after a short vowel at the end of a word."},
  "zz": {sounds:[{ph:"/z/",  ex:["buzz","fizz","jazz"]}], tip:"FLSZ rule: double z after a short vowel at the end of a word."},
  "sh": {sounds:[{ph:"/sh/", ex:["ship","shop","fish"]}], tip:"Two letters, one new sound. Beginning (ship) or end (fish) of a word."},
  "th": {sounds:[{ph:"/th/ (voiced)", ex:["this","that","them"]},{ph:"/th/ (unvoiced)", ex:["thin","bath","moth"]}], tip:"Tongue between the teeth. Voice on: this, that. Voice off: thin, bath."},
  "ch": {sounds:[{ph:"/ch/", ex:["chip","chin","chat"]},{ph:"/sh/", ex:["chef","chute","machine"]},{ph:"/k/",  ex:["school","echo","ache"]}], tip:"<b>ch</b> usually spells /ch/. In some words from French it spells /sh/ (chef); from Greek it spells /k/ (school)."},
  "wh": {sounds:[{ph:"/w/",  ex:["whip","when","which"]}], tip:"<b>wh</b> spells /w/ at the beginning of question words and others (what, whip). In who it spells /h/."},
  "ph": {sounds:[{ph:"/f/",  ex:["phone","graph","dolphin"]}], tip:"<b>ph</b> spells /f/ in words from Greek."},
  "ng": {sounds:[{ph:"/ŋ/",  ex:["ring","song","king"]}], tip:"One sound at the end of a word or syllable: sing, long, bang."},
  "nk": {sounds:[{ph:"/ŋk/", ex:["pink","bank","sink"]}], tip:"/ŋ/ + /k/ together at the end of a word: ink, thank, junk."},
  "tch":{sounds:[{ph:"/ch/", ex:["catch","match","witch"]}], tip:"Use <b>tch</b> right after a short vowel at the end of a word (catch). Otherwise use <b>ch</b> (much, bench)."},
  "dge":{sounds:[{ph:"/j/",  ex:["badge","edge","bridge"]}], tip:"Use <b>dge</b> right after a short vowel at the end of a word. Otherwise -ge (cage, hinge)."},
  "kn": {sounds:[{ph:"/n/",  ex:["knot","knee","knit"]}], tip:"Silent k. <b>kn</b> spells /n/ at the beginning of a word."},
  "wr": {sounds:[{ph:"/r/",  ex:["wrap","wrist","write"]}], tip:"Silent w. <b>wr</b> spells /r/ at the beginning of a word."},
  "mb": {sounds:[{ph:"/m/",  ex:["lamb","comb","thumb"]}], tip:"Silent b. <b>mb</b> spells /m/ at the end of a word."},
  "gn": {sounds:[{ph:"/n/",  ex:["gnat","gnome","sign"]}], tip:"Silent g. <b>gn</b> spells /n/ at the beginning (gnat) or end (sign) of a word."},
  "gh": {sounds:[{ph:"/g/",  ex:["ghost","ghoul","ghastly"]},{ph:"/f/", ex:["laugh","cough","rough"]}], tip:"<b>gh</b> spells /g/ at the beginning of a few words (ghost). At the end it can spell /f/ (laugh, tough) or be silent (high)."},
  // ---- VCe & related ----
  "a_e":{sounds:[{ph:"/ā/",  ex:["cake","made","game"]}], tip:"Silent e at the end makes the vowel say its name: cap → cape."},
  "i_e":{sounds:[{ph:"/ī/",  ex:["bike","time","kite"]}], tip:"Silent e: bit → bite, kit → kite."},
  "o_e":{sounds:[{ph:"/ō/",  ex:["home","nose","bone"]}], tip:"Silent e: hop → hope, not → note."},
  "e_e":{sounds:[{ph:"/ē/",  ex:["these","Pete","theme"]}], tip:"Silent e: not many words use e_e (these, eve, complete)."},
  "u_e":{sounds:[{ph:"/ū/",  ex:["rule","tune","flute"]},{ph:"/yū/", ex:["cute","mule","use"]}], tip:"Silent e: tub → tube. Sometimes /ū/ (rule), sometimes /yū/ (cute)."},
  "_ce":{sounds:[{ph:"/s/",  ex:["ice","rice","face"]}], tip:"<b>ce</b> at the end spells /s/ (the e signals the soft c)."},
  "_ge":{sounds:[{ph:"/j/",  ex:["cage","page","huge"]}], tip:"<b>ge</b> at the end spells /j/ (the e signals the soft g)."},
  "-ce":{sounds:[{ph:"/s/",  ex:["ice","rice","face"]}], tip:"<b>ce</b> at the end spells /s/."},
  "-ge":{sounds:[{ph:"/j/",  ex:["cage","page","huge"]}], tip:"<b>ge</b> at the end spells /j/."},
  // ---- endings / suffixes ----
  "-s": {sounds:[{ph:"/s/",  ex:["cats","hats","maps"]},{ph:"/z/",  ex:["dogs","bugs","pens"]}], tip:"Suffix -s makes plurals and verbs. It sounds /s/ after quiet sounds (cats) and /z/ after voiced sounds (dogs)."},
  "-es":{sounds:[{ph:"/ĕz/ /əz/", ex:["boxes","dishes","wishes"]}], tip:"Add -es after s, x, z, sh, ch, ss: box → boxes, wish → wishes."},
  "-ed":{sounds:[{ph:"/t/",  ex:["jumped","walked","kicked"]},{ph:"/d/",  ex:["played","called","hugged"]},{ph:"/əd/", ex:["wanted","needed","landed"]}], tip:"Suffix -ed means past tense. Three sounds: /t/ after quiet sounds, /d/ after voiced sounds, /əd/ after t or d."},
  "-ing":{sounds:[{ph:"/ĭng/", ex:["jumping","singing","fishing"]}], tip:"Suffix -ing: something is happening now (jump → jumping)."},
  "-le":{sounds:[{ph:"/əl/", ex:["apple","puzzle","little"]}], tip:"Final stable syllable: consonant + le. Divide before the consonant: ap-ple, puz-zle."},
  "-all":{sounds:[{ph:"/orl/ /awl/", ex:["ball","call","tall"]}], tip:"In -all the a does not say /ă/: ball, tall, small."},
  "-oll":{sounds:[{ph:"/ōl/", ex:["roll","toll","poll"]}], tip:"In -oll the o often says /ō/: roll, stroll."},
  "-ull":{sounds:[{ph:"/ool/", ex:["full","pull","bull"]}], tip:"In -ull the u says /oo/ as in put: full, pull."},
  "-er":{sounds:[{ph:"/er/ /ə/", ex:["bigger","faster","teacher"]}], tip:"Suffix -er means 'more' with adjectives (bigger) or 'one who' with verbs (teacher)."},
  "-est":{sounds:[{ph:"/əst/", ex:["biggest","fastest","tallest"]}], tip:"Suffix -est means 'the most'."},
  "-ly":{sounds:[{ph:"/lē/", ex:["slowly","sadly","quickly"]}], tip:"Suffix -ly tells how something is done (slow → slowly)."},
  "-less":{sounds:[{ph:"/ləs/", ex:["hopeless","careless","endless"]}], tip:"Suffix -less means 'without'."},
  "-ful":{sounds:[{ph:"/fəl/", ex:["helpful","hopeful","playful"]}], tip:"Suffix -ful means 'full of'. Spelled with one l."},
  "un-":{sounds:[{ph:"/ŭn/", ex:["unlock","unzip","unhappy"]}], tip:"Prefix un- means 'not' or 'the opposite of'."},
  "pre-":{sounds:[{ph:"/prē/", ex:["preheat","preview","preschool"]}], tip:"Prefix pre- means 'before'."},
  "re-":{sounds:[{ph:"/rē/", ex:["redo","replay","rewrite"]}], tip:"Prefix re- means 'again' or 'back'."},
  "dis-":{sounds:[{ph:"/dĭs/", ex:["dislike","disagree","disconnect"]}], tip:"Prefix dis- means 'not' or 'the opposite of'."},
  "-tion":{sounds:[{ph:"/shən/", ex:["action","nation","station"]}], tip:"Final stable syllable -tion says /shən/. It turns verbs into nouns (act → action)."},
  "-sion":{sounds:[{ph:"/zhən/", ex:["vision","decision","television"]},{ph:"/shən/", ex:["mansion","mission","passion"]}], tip:"-sion after a vowel usually says /zhən/ (vision); after a consonant /shən/ (mansion)."},
  "-ture":{sounds:[{ph:"/chər/", ex:["picture","nature","future"]}], tip:"Final stable syllable -ture says /chər/: pic-ture, na-ture."},
  "-or":{sounds:[{ph:"/ə/ /er/", ex:["actor","sailor","doctor"]}], tip:"Suffix -or means 'one who' (act → actor). It sounds /ə/ at the end of a word."},
  "-ist":{sounds:[{ph:"/ĭst/", ex:["artist","dentist","tourist"]}], tip:"Suffix -ist means 'a person who' (art → artist)."},
  "-ish":{sounds:[{ph:"/ĭsh/", ex:["reddish","childish","foolish"]}], tip:"Suffix -ish means 'somewhat like' (red → reddish)."},
  "-y": {sounds:[{ph:"/ē/",  ex:["sunny","cloudy","sleepy"]}], tip:"Suffix -y means 'full of' or 'like' (sun → sunny). Watch the doubling and drop-e rules."},
  "-ness":{sounds:[{ph:"/nəs/", ex:["kindness","darkness","sadness"]}], tip:"Suffix -ness makes a noun meaning 'the state of being' (kind → kindness)."},
  "-ment":{sounds:[{ph:"/mənt/", ex:["payment","movement","treatment"]}], tip:"Suffix -ment makes a noun (pay → payment)."},
  "-able":{sounds:[{ph:"/əbəl/", ex:["readable","washable","comfortable"]}], tip:"Suffix -able means 'can be done' (read → readable)."},
  "-ible":{sounds:[{ph:"/əbəl/", ex:["visible","possible","terrible"]}], tip:"Suffix -ible also means 'can be'. Used mostly with Latin roots (visible, flexible)."},
  "uni-":{sounds:[{ph:"/yūnĭ/", ex:["unicorn","uniform","unicycle"]}], tip:"Prefix uni- means 'one'."},
  "bi-":{sounds:[{ph:"/bī/", ex:["bicycle","bilingual","biweekly"]}], tip:"Prefix bi- means 'two'."},
  "tri-":{sounds:[{ph:"/trī/", ex:["triangle","tricycle","triplets"]}], tip:"Prefix tri- means 'three'."},
  // ---- r-controlled ----
  "ar": {sounds:[{ph:"/ar/", ex:["car","farm","star"]},{ph:"/ə/ /er/", ex:["dollar","collar","sugar"]}], tip:"<b>ar</b> spells /ar/ (car). At the end of a longer word it is unstressed: /ə/ (dollar)."},
  "or": {sounds:[{ph:"/or/", ex:["fork","corn","for"]},{ph:"/ə/ /er/", ex:["doctor","actor","word"]}], tip:"<b>or</b> spells /or/ (fork). After w it says /er/ (word, work). At the end of a longer word: /ə/ (doctor)."},
  "ore":{sounds:[{ph:"/or/", ex:["more","store","shore"]}], tip:"<b>ore</b> spells /or/ at the end of a word (more, score)."},
  "er": {sounds:[{ph:"/er/", ex:["her","fern","verb"]},{ph:"/ə/", ex:["letter","sister","winter"]}], tip:"<b>er</b> spells /er/ (her, fern). At the end of a two-syllable word it is the relaxed schwa /ə/ (letter, sister)."},
  "ir": {sounds:[{ph:"/er/", ex:["bird","girl","first"]}], tip:"<b>ir</b> spells /er/ in the middle of a word (bird, shirt)."},
  "ur": {sounds:[{ph:"/er/", ex:["turn","burn","hurt"]}], tip:"<b>ur</b> spells /er/ (turn, nurse, fur)."},
  "wor":{sounds:[{ph:"/wer/", ex:["work","word","worm"]}], tip:"After w, <b>or</b> says /er/: work, world."},
  "air":{sounds:[{ph:"/air/", ex:["hair","chair","fair"]}], tip:"<b>air</b> spells /air/ (hair, pair)."},
  "are":{sounds:[{ph:"/air/", ex:["care","share","dare"]}], tip:"<b>are</b> spells /air/ at the end of a word (care, square)."},
  "ear":{sounds:[{ph:"/ear/", ex:["ear","hear","near"]},{ph:"/air/", ex:["bear","wear","pear"]},{ph:"/er/", ex:["earn","learn","early"]}], tip:"<b>ear</b> usually spells /ear/ (hear). Sometimes /air/ (bear, wear) or /er/ (learn)."},
  // ---- vowel teams ----
  "ai": {sounds:[{ph:"/ā/",  ex:["rain","tail","wait"]}], tip:"<b>ai</b> spells /ā/ at the beginning or middle of a word (rain, paint)."},
  "ay": {sounds:[{ph:"/ā/",  ex:["day","play","say"]}], tip:"<b>ay</b> spells /ā/ at the end of a word (day, stay)."},
  "ee": {sounds:[{ph:"/ē/",  ex:["see","tree","feet"]}], tip:"<b>ee</b> spells /ē/ (feet, green, bee)."},
  "ea": {sounds:[{ph:"/ē/",  ex:["eat","sea","team"]},{ph:"/ĕ/",  ex:["head","bread","ready"]},{ph:"/ā/",  ex:["great","break","steak"]}], tip:"<b>ea</b> usually spells /ē/ (eat). Sometimes /ĕ/ (head, bread) and rarely /ā/ (great, break)."},
  "ey": {sounds:[{ph:"/ē/",  ex:["key","monkey","money"]},{ph:"/ā/",  ex:["they","hey","prey"]}], tip:"<b>ey</b> spells /ē/ at the end of a word (key, monkey); sometimes /ā/ (they, grey)."},
  "oa": {sounds:[{ph:"/ō/",  ex:["boat","coat","road"]}], tip:"<b>oa</b> spells /ō/ in the middle of a word (boat, soap)."},
  "ow": {sounds:[{ph:"/ō/",  ex:["snow","grow","yellow"]},{ph:"/ow/", ex:["cow","down","town"]}], tip:"<b>ow</b> spells /ō/ (snow, show) or /ow/ (cow, town). Try both when reading."},
  "oe": {sounds:[{ph:"/ō/",  ex:["toe","goes","hoe"]}], tip:"<b>oe</b> spells /ō/ at the end of a word (toe, doe)."},
  "ie": {sounds:[{ph:"/ī/",  ex:["pie","tie","lie"]},{ph:"/ē/",  ex:["field","chief","piece"]}], tip:"<b>ie</b> spells /ī/ at the end of short words (pie); in the middle it often spells /ē/ (field)."},
  "igh":{sounds:[{ph:"/ī/",  ex:["high","night","light"]}], tip:"<b>igh</b> spells /ī/ (night, bright). The gh is silent."},
  "oo": {sounds:[{ph:"/oo/", ex:["book","look","good"]},{ph:"/ū/",  ex:["moon","food","zoo"]}], tip:"<b>oo</b> spells short /oo/ (book, foot) or long /ū/ (moon, zoo)."},
  "ew": {sounds:[{ph:"/ū/",  ex:["new","blew","drew"]},{ph:"/yū/", ex:["few","dew","view"]}], tip:"<b>ew</b> spells /ū/ (new, flew) or /yū/ (few) at the end of a word."},
  "ui": {sounds:[{ph:"/ū/",  ex:["fruit","suit","juice"]}], tip:"<b>ui</b> spells /ū/ (fruit, cruise)."},
  "ue": {sounds:[{ph:"/ū/",  ex:["blue","glue","true"]},{ph:"/yū/", ex:["cue","hue","rescue"]}], tip:"<b>ue</b> spells /ū/ (blue) or /yū/ (cue) at the end of a word."},
  "eu": {sounds:[{ph:"/ū/",  ex:["neutral","sleuth"]},{ph:"/yū/", ex:["feud","Europe"]}], tip:"<b>eu</b> is a rare spelling of /ū/ or /yū/."},
  "au": {sounds:[{ph:"/or/ /aw/", ex:["haul","fault","August"]}], tip:"<b>au</b> spells /aw/ (/or/ in AU/NZ English) in the middle of a word (haul, sauce)."},
  "aw": {sounds:[{ph:"/or/ /aw/", ex:["saw","paw","draw"]}], tip:"<b>aw</b> spells /aw/ at the end of a word (saw, claw) or before n or l (lawn, crawl)."},
  "augh":{sounds:[{ph:"/or/ /aw/", ex:["caught","taught","daughter"]}], tip:"<b>augh</b> spells /aw/ before t (caught, taught)."},
  "ough":{sounds:[{ph:"/or/ /aw/", ex:["thought","bought","fought"]},{ph:"/ō/",  ex:["though","dough","although"]}], tip:"<b>ough</b> spells /aw/ before t (bought). At the end of a word it usually spells /ō/ (dough). Also /ŭf/ in tough, rough, enough."},
  "oi": {sounds:[{ph:"/oi/", ex:["oil","coin","boil"]}], tip:"<b>oi</b> spells /oi/ in the middle of a word (coin, point)."},
  "oy": {sounds:[{ph:"/oi/", ex:["boy","toy","joy"]}], tip:"<b>oy</b> spells /oi/ at the end of a word (toy, enjoy)."},
  "ou": {sounds:[{ph:"/ow/", ex:["out","loud","house"]},{ph:"/ū/",  ex:["soup","you","group"]},{ph:"/ŭ/",  ex:["touch","young","cousin"]}], tip:"<b>ou</b> usually spells /ow/ (out, cloud). Sometimes /ū/ (soup) or /ŭ/ (touch, young)."},
  "our":{sounds:[{ph:"/or/", ex:["four","pour","your"]},{ph:"/ower/", ex:["our","hour","flour"]}], tip:"<b>our</b> spells /or/ in four, pour; /ow-er/ in our, hour."},
  "ei": {sounds:[{ph:"/ā/",  ex:["vein","rein","reindeer"]},{ph:"/ē/",  ex:["ceiling","receive","either"]}], tip:"<b>ei</b> can spell /ā/ (vein) or /ē/ (ceiling)."},
  "eigh":{sounds:[{ph:"/ā/",  ex:["eight","weigh","sleigh"]}], tip:"<b>eigh</b> spells /ā/ (eight, neighbour)."},
  "aigh":{sounds:[{ph:"/ā/",  ex:["straight"]}], tip:"<b>aigh</b> spells /ā/ in just one common word: straight."},
  // ---- VCC long vowel patterns ----
  "ild":{sounds:[{ph:"/īld/", ex:["wild","child","mild"]}], tip:"Before -ld the i is long: wild, child."},
  "old":{sounds:[{ph:"/ōld/", ex:["cold","gold","told"]}], tip:"Before -ld the o is long: cold, sold."},
  "ind":{sounds:[{ph:"/īnd/", ex:["find","kind","mind"]}], tip:"Before -nd the i is often long: find, kind."},
  "olt":{sounds:[{ph:"/ōlt/", ex:["bolt","colt","jolt"]}], tip:"Before -lt the o is long: bolt, colt."},
  "ost":{sounds:[{ph:"/ōst/", ex:["most","post","host"]}], tip:"Before -st the o is often long: most, post (but not cost, lost)."},
};
